// Code generated by protoc-gen-go.
// source: ethernet_controller_driver_bag_v2_type.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_drivers_media_eth_oper_ethernet_interface_interfaces_interface is a generated protocol buffer package.

It is generated from these files:
	ethernet_controller_driver_bag_v2_type.proto

It has these top-level messages:
	EthernetControllerDriverBagV2Type_KEYS
	EthernetControllerDriverBagV2Type
	EtherAutoneg_
	MacAddrType
	EtherMcastMacType_
	EthCtrlrPhyDomLaneAlarms
	EthCtrlrPhyLaneOptMonValidity
	EthCtrlrPhyLaneOptMon
	EthCtrlrPhyDomAlarms
	EthCtrlrPhyDomThresholdValidity
	EthCtrlrPhyDomThresholds
	EtherPhyDetails
	EthCtrlrAlarms
	EthCtrlrErrorCounters
	EtherBerSettings
	EthBerMonitoring
	EtherOpdSettings
	EthOpdMonitoring
	EthCtrlrUcastMacFilter
	EthCtrlrMcastMacFilter
	EtherFecDetails
	EtherPfcDetailsType
	ExtendedLoopbackType
	EthCtrlrPhyInfo
	EthCtrlrL1Info
	EthCtrlrMacInfo
	EthCtlrTransportInfo
*/
package cisco_ios_xr_drivers_media_eth_oper_ethernet_interface_interfaces_interface

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ethernet bag for driver state for the show controllers command
type EthernetControllerDriverBagV2Type_KEYS struct {
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName" json:"interface_name,omitempty"`
}

func (m *EthernetControllerDriverBagV2Type_KEYS) Reset() {
	*m = EthernetControllerDriverBagV2Type_KEYS{}
}
func (m *EthernetControllerDriverBagV2Type_KEYS) String() string { return proto.CompactTextString(m) }
func (*EthernetControllerDriverBagV2Type_KEYS) ProtoMessage()    {}
func (*EthernetControllerDriverBagV2Type_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *EthernetControllerDriverBagV2Type_KEYS) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

type EthernetControllerDriverBagV2Type struct {
	// Port Administrative State
	AdminState string `protobuf:"bytes,50,opt,name=admin_state,json=adminState" json:"admin_state,omitempty"`
	// Port Operational state - TRUE if up
	OperStateUp uint32 `protobuf:"varint,51,opt,name=oper_state_up,json=operStateUp" json:"oper_state_up,omitempty"`
	// PHY information
	PhyInfo *EthCtrlrPhyInfo `protobuf:"bytes,52,opt,name=phy_info,json=phyInfo" json:"phy_info,omitempty"`
	// Layer 1 information
	Layer1Info *EthCtrlrL1Info `protobuf:"bytes,53,opt,name=layer1_info,json=layer1Info" json:"layer1_info,omitempty"`
	// MAC Layer information
	MacInfo *EthCtrlrMacInfo `protobuf:"bytes,54,opt,name=mac_info,json=macInfo" json:"mac_info,omitempty"`
	// Transport state information
	TransportInfo *EthCtlrTransportInfo `protobuf:"bytes,55,opt,name=transport_info,json=transportInfo" json:"transport_info,omitempty"`
}

func (m *EthernetControllerDriverBagV2Type) Reset()         { *m = EthernetControllerDriverBagV2Type{} }
func (m *EthernetControllerDriverBagV2Type) String() string { return proto.CompactTextString(m) }
func (*EthernetControllerDriverBagV2Type) ProtoMessage()    {}
func (*EthernetControllerDriverBagV2Type) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

func (m *EthernetControllerDriverBagV2Type) GetAdminState() string {
	if m != nil {
		return m.AdminState
	}
	return ""
}

func (m *EthernetControllerDriverBagV2Type) GetOperStateUp() uint32 {
	if m != nil {
		return m.OperStateUp
	}
	return 0
}

func (m *EthernetControllerDriverBagV2Type) GetPhyInfo() *EthCtrlrPhyInfo {
	if m != nil {
		return m.PhyInfo
	}
	return nil
}

func (m *EthernetControllerDriverBagV2Type) GetLayer1Info() *EthCtrlrL1Info {
	if m != nil {
		return m.Layer1Info
	}
	return nil
}

func (m *EthernetControllerDriverBagV2Type) GetMacInfo() *EthCtrlrMacInfo {
	if m != nil {
		return m.MacInfo
	}
	return nil
}

func (m *EthernetControllerDriverBagV2Type) GetTransportInfo() *EthCtlrTransportInfo {
	if m != nil {
		return m.TransportInfo
	}
	return nil
}

type EtherAutoneg_ struct {
	// TRUE if autonegotiation is enabled
	AutonegEnabled int32 `protobuf:"zigzag32,1,opt,name=autoneg_enabled,json=autonegEnabled" json:"autoneg_enabled,omitempty"`
	// Validity mask: 0x1 speed, 0x2 duplex, 0x4 flowcontrol, 0x8 fec
	Mask uint32 `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	// Restricted speed (if relevant bit is set in mask)
	Speed string `protobuf:"bytes,3,opt,name=speed" json:"speed,omitempty"`
	// Restricted duplex (if relevant bit is set in mask)
	Duplex string `protobuf:"bytes,4,opt,name=duplex" json:"duplex,omitempty"`
	// Restricted flowcontrol (if relevant bit is set in mask)
	Flowcontrol string `protobuf:"bytes,5,opt,name=flowcontrol" json:"flowcontrol,omitempty"`
	// If true, configuration overrides negotiated settings.  If false, negotiated settings in effect
	ConfigOverride int32 `protobuf:"zigzag32,6,opt,name=config_override,json=configOverride" json:"config_override,omitempty"`
	// Restricted FEC (if revelevant bit is set in mask)
	Fec string `protobuf:"bytes,7,opt,name=fec" json:"fec,omitempty"`
}

func (m *EtherAutoneg_) Reset()                    { *m = EtherAutoneg_{} }
func (m *EtherAutoneg_) String() string            { return proto.CompactTextString(m) }
func (*EtherAutoneg_) ProtoMessage()               {}
func (*EtherAutoneg_) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EtherAutoneg_) GetAutonegEnabled() int32 {
	if m != nil {
		return m.AutonegEnabled
	}
	return 0
}

func (m *EtherAutoneg_) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *EtherAutoneg_) GetSpeed() string {
	if m != nil {
		return m.Speed
	}
	return ""
}

func (m *EtherAutoneg_) GetDuplex() string {
	if m != nil {
		return m.Duplex
	}
	return ""
}

func (m *EtherAutoneg_) GetFlowcontrol() string {
	if m != nil {
		return m.Flowcontrol
	}
	return ""
}

func (m *EtherAutoneg_) GetConfigOverride() int32 {
	if m != nil {
		return m.ConfigOverride
	}
	return 0
}

func (m *EtherAutoneg_) GetFec() string {
	if m != nil {
		return m.Fec
	}
	return ""
}

type MacAddrType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *MacAddrType) Reset()                    { *m = MacAddrType{} }
func (m *MacAddrType) String() string            { return proto.CompactTextString(m) }
func (*MacAddrType) ProtoMessage()               {}
func (*MacAddrType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MacAddrType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EtherMcastMacType_ struct {
	// MAC address
	MacAddress string `protobuf:"bytes,1,opt,name=mac_address,json=macAddress" json:"mac_address,omitempty"`
	// Mask for this MAC address
	Mask string `protobuf:"bytes,2,opt,name=mask" json:"mask,omitempty"`
}

func (m *EtherMcastMacType_) Reset()                    { *m = EtherMcastMacType_{} }
func (m *EtherMcastMacType_) String() string            { return proto.CompactTextString(m) }
func (*EtherMcastMacType_) ProtoMessage()               {}
func (*EtherMcastMacType_) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EtherMcastMacType_) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *EtherMcastMacType_) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

type EthCtrlrPhyDomLaneAlarms struct {
	// Transmit Laser Power Alarm
	TransmitLaserPower string `protobuf:"bytes,1,opt,name=transmit_laser_power,json=transmitLaserPower" json:"transmit_laser_power,omitempty"`
	// Received Optical Power Alarm
	ReceivedLaserPower string `protobuf:"bytes,2,opt,name=received_laser_power,json=receivedLaserPower" json:"received_laser_power,omitempty"`
	// Laser Bias Current Alarm
	LaserBiasCurrent string `protobuf:"bytes,3,opt,name=laser_bias_current,json=laserBiasCurrent" json:"laser_bias_current,omitempty"`
}

func (m *EthCtrlrPhyDomLaneAlarms) Reset()                    { *m = EthCtrlrPhyDomLaneAlarms{} }
func (m *EthCtrlrPhyDomLaneAlarms) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrPhyDomLaneAlarms) ProtoMessage()               {}
func (*EthCtrlrPhyDomLaneAlarms) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EthCtrlrPhyDomLaneAlarms) GetTransmitLaserPower() string {
	if m != nil {
		return m.TransmitLaserPower
	}
	return ""
}

func (m *EthCtrlrPhyDomLaneAlarms) GetReceivedLaserPower() string {
	if m != nil {
		return m.ReceivedLaserPower
	}
	return ""
}

func (m *EthCtrlrPhyDomLaneAlarms) GetLaserBiasCurrent() string {
	if m != nil {
		return m.LaserBiasCurrent
	}
	return ""
}

type EthCtrlrPhyLaneOptMonValidity struct {
	// The wavelength 'per lane' field is valid
	WavelengthValid int32 `protobuf:"zigzag32,1,opt,name=wavelength_valid,json=wavelengthValid" json:"wavelength_valid,omitempty"`
	// The transmit power 'per lane' field is valid
	TransmitPowerValid int32 `protobuf:"zigzag32,2,opt,name=transmit_power_valid,json=transmitPowerValid" json:"transmit_power_valid,omitempty"`
	// The receive power 'per lane' field is valid
	ReceivePowerValid int32 `protobuf:"zigzag32,3,opt,name=receive_power_valid,json=receivePowerValid" json:"receive_power_valid,omitempty"`
	// The laser bias 'per lane' field is valid
	LaserBiasValid int32 `protobuf:"zigzag32,4,opt,name=laser_bias_valid,json=laserBiasValid" json:"laser_bias_valid,omitempty"`
}

func (m *EthCtrlrPhyLaneOptMonValidity) Reset()                    { *m = EthCtrlrPhyLaneOptMonValidity{} }
func (m *EthCtrlrPhyLaneOptMonValidity) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrPhyLaneOptMonValidity) ProtoMessage()               {}
func (*EthCtrlrPhyLaneOptMonValidity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *EthCtrlrPhyLaneOptMonValidity) GetWavelengthValid() int32 {
	if m != nil {
		return m.WavelengthValid
	}
	return 0
}

func (m *EthCtrlrPhyLaneOptMonValidity) GetTransmitPowerValid() int32 {
	if m != nil {
		return m.TransmitPowerValid
	}
	return 0
}

func (m *EthCtrlrPhyLaneOptMonValidity) GetReceivePowerValid() int32 {
	if m != nil {
		return m.ReceivePowerValid
	}
	return 0
}

func (m *EthCtrlrPhyLaneOptMonValidity) GetLaserBiasValid() int32 {
	if m != nil {
		return m.LaserBiasValid
	}
	return 0
}

type EthCtrlrPhyLaneOptMon struct {
	// Center Wavelength (nm*1000)
	CenterWavelength uint32 `protobuf:"varint,1,opt,name=center_wavelength,json=centerWavelength" json:"center_wavelength,omitempty"`
	// Transmit Laser Power (dBm*1000)
	TransmitLaserPower int32 `protobuf:"zigzag32,2,opt,name=transmit_laser_power,json=transmitLaserPower" json:"transmit_laser_power,omitempty"`
	// Received Optical Power (dBm*1000)
	ReceivedLaserPower int32 `protobuf:"zigzag32,3,opt,name=received_laser_power,json=receivedLaserPower" json:"received_laser_power,omitempty"`
	// Laser Bias Current (uAmps)
	LaserBiasCurrent uint32 `protobuf:"varint,4,opt,name=laser_bias_current,json=laserBiasCurrent" json:"laser_bias_current,omitempty"`
	// Digital Optical Monitoring alarms
	DigOptMonAlarm *EthCtrlrPhyDomLaneAlarms `protobuf:"bytes,5,opt,name=dig_opt_mon_alarm,json=digOptMonAlarm" json:"dig_opt_mon_alarm,omitempty"`
	// Numerical identifier for this lane
	LaneId uint32 `protobuf:"varint,6,opt,name=lane_id,json=laneId" json:"lane_id,omitempty"`
}

func (m *EthCtrlrPhyLaneOptMon) Reset()                    { *m = EthCtrlrPhyLaneOptMon{} }
func (m *EthCtrlrPhyLaneOptMon) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrPhyLaneOptMon) ProtoMessage()               {}
func (*EthCtrlrPhyLaneOptMon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *EthCtrlrPhyLaneOptMon) GetCenterWavelength() uint32 {
	if m != nil {
		return m.CenterWavelength
	}
	return 0
}

func (m *EthCtrlrPhyLaneOptMon) GetTransmitLaserPower() int32 {
	if m != nil {
		return m.TransmitLaserPower
	}
	return 0
}

func (m *EthCtrlrPhyLaneOptMon) GetReceivedLaserPower() int32 {
	if m != nil {
		return m.ReceivedLaserPower
	}
	return 0
}

func (m *EthCtrlrPhyLaneOptMon) GetLaserBiasCurrent() uint32 {
	if m != nil {
		return m.LaserBiasCurrent
	}
	return 0
}

func (m *EthCtrlrPhyLaneOptMon) GetDigOptMonAlarm() *EthCtrlrPhyDomLaneAlarms {
	if m != nil {
		return m.DigOptMonAlarm
	}
	return nil
}

func (m *EthCtrlrPhyLaneOptMon) GetLaneId() uint32 {
	if m != nil {
		return m.LaneId
	}
	return 0
}

type EthCtrlrPhyDomAlarms struct {
	// Transceiver Temperature Alarm
	TransceiverTemperature string `protobuf:"bytes,1,opt,name=transceiver_temperature,json=transceiverTemperature" json:"transceiver_temperature,omitempty"`
	// Transceiver Voltage Alarm
	TransceiverVoltage string `protobuf:"bytes,2,opt,name=transceiver_voltage,json=transceiverVoltage" json:"transceiver_voltage,omitempty"`
	// Transmit Laser Power Alarm
	TransmitLaserPower string `protobuf:"bytes,3,opt,name=transmit_laser_power,json=transmitLaserPower" json:"transmit_laser_power,omitempty"`
	// Received Optical Power Alarm
	ReceivedLaserPower string `protobuf:"bytes,4,opt,name=received_laser_power,json=receivedLaserPower" json:"received_laser_power,omitempty"`
	// Laser Bias Current Alarm
	LaserBiasCurrent string `protobuf:"bytes,5,opt,name=laser_bias_current,json=laserBiasCurrent" json:"laser_bias_current,omitempty"`
}

func (m *EthCtrlrPhyDomAlarms) Reset()                    { *m = EthCtrlrPhyDomAlarms{} }
func (m *EthCtrlrPhyDomAlarms) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrPhyDomAlarms) ProtoMessage()               {}
func (*EthCtrlrPhyDomAlarms) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EthCtrlrPhyDomAlarms) GetTransceiverTemperature() string {
	if m != nil {
		return m.TransceiverTemperature
	}
	return ""
}

func (m *EthCtrlrPhyDomAlarms) GetTransceiverVoltage() string {
	if m != nil {
		return m.TransceiverVoltage
	}
	return ""
}

func (m *EthCtrlrPhyDomAlarms) GetTransmitLaserPower() string {
	if m != nil {
		return m.TransmitLaserPower
	}
	return ""
}

func (m *EthCtrlrPhyDomAlarms) GetReceivedLaserPower() string {
	if m != nil {
		return m.ReceivedLaserPower
	}
	return ""
}

func (m *EthCtrlrPhyDomAlarms) GetLaserBiasCurrent() string {
	if m != nil {
		return m.LaserBiasCurrent
	}
	return ""
}

type EthCtrlrPhyDomThresholdValidity struct {
	// The temperature fields are valid
	TemperatureValid int32 `protobuf:"zigzag32,1,opt,name=temperature_valid,json=temperatureValid" json:"temperature_valid,omitempty"`
	// The voltage fields are valid
	VoltageValid int32 `protobuf:"zigzag32,2,opt,name=voltage_valid,json=voltageValid" json:"voltage_valid,omitempty"`
	// The laser bias fields are valid
	LaserBiasValid int32 `protobuf:"zigzag32,3,opt,name=laser_bias_valid,json=laserBiasValid" json:"laser_bias_valid,omitempty"`
	// The transmit power fields are valid
	TransmitPowerValid int32 `protobuf:"zigzag32,4,opt,name=transmit_power_valid,json=transmitPowerValid" json:"transmit_power_valid,omitempty"`
	// The receive power fields are valid
	ReceivePowerValid int32 `protobuf:"zigzag32,5,opt,name=receive_power_valid,json=receivePowerValid" json:"receive_power_valid,omitempty"`
}

func (m *EthCtrlrPhyDomThresholdValidity) Reset()                    { *m = EthCtrlrPhyDomThresholdValidity{} }
func (m *EthCtrlrPhyDomThresholdValidity) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrPhyDomThresholdValidity) ProtoMessage()               {}
func (*EthCtrlrPhyDomThresholdValidity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EthCtrlrPhyDomThresholdValidity) GetTemperatureValid() int32 {
	if m != nil {
		return m.TemperatureValid
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholdValidity) GetVoltageValid() int32 {
	if m != nil {
		return m.VoltageValid
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholdValidity) GetLaserBiasValid() int32 {
	if m != nil {
		return m.LaserBiasValid
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholdValidity) GetTransmitPowerValid() int32 {
	if m != nil {
		return m.TransmitPowerValid
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholdValidity) GetReceivePowerValid() int32 {
	if m != nil {
		return m.ReceivePowerValid
	}
	return 0
}

type EthCtrlrPhyDomThresholds struct {
	// Field validity
	FieldValidity *EthCtrlrPhyDomThresholdValidity `protobuf:"bytes,1,opt,name=field_validity,json=fieldValidity" json:"field_validity,omitempty"`
	// Transceiver high temperature alarm threshold (mDegrees C)
	TransceiverTemperatureAlarmHigh int32 `protobuf:"zigzag32,2,opt,name=transceiver_temperature_alarm_high,json=transceiverTemperatureAlarmHigh" json:"transceiver_temperature_alarm_high,omitempty"`
	// Transceiver high temperature warning threshold (mDegrees C)
	TransceiverTemperatureWarningHigh int32 `protobuf:"zigzag32,3,opt,name=transceiver_temperature_warning_high,json=transceiverTemperatureWarningHigh" json:"transceiver_temperature_warning_high,omitempty"`
	// Transceiver low temperature warning threshold (mDegrees C)
	TransceiverTemperatureWarningLow int32 `protobuf:"zigzag32,4,opt,name=transceiver_temperature_warning_low,json=transceiverTemperatureWarningLow" json:"transceiver_temperature_warning_low,omitempty"`
	// Transceiver low temperature alarm threshold (mDegrees C)
	TransceiverTemperatureAlarmLow int32 `protobuf:"zigzag32,5,opt,name=transceiver_temperature_alarm_low,json=transceiverTemperatureAlarmLow" json:"transceiver_temperature_alarm_low,omitempty"`
	// Transceiver high voltage alarm threshold (mV)
	TransceiverVoltageAlarmHigh uint32 `protobuf:"varint,6,opt,name=transceiver_voltage_alarm_high,json=transceiverVoltageAlarmHigh" json:"transceiver_voltage_alarm_high,omitempty"`
	// Transceiver high voltage warning threshold (mV)
	TransceiverVoltageWarningHigh uint32 `protobuf:"varint,7,opt,name=transceiver_voltage_warning_high,json=transceiverVoltageWarningHigh" json:"transceiver_voltage_warning_high,omitempty"`
	// Transceiver low voltage warning threshold (mV)
	TransceiverVoltageWarningLow uint32 `protobuf:"varint,8,opt,name=transceiver_voltage_warning_low,json=transceiverVoltageWarningLow" json:"transceiver_voltage_warning_low,omitempty"`
	// Transceiver low voltage alarm threshold (mV)
	TransceiverVoltageAlarmLow uint32 `protobuf:"varint,9,opt,name=transceiver_voltage_alarm_low,json=transceiverVoltageAlarmLow" json:"transceiver_voltage_alarm_low,omitempty"`
	// Laser bias high alarm threshold (uA)
	LaserBiasAlarmHigh uint32 `protobuf:"varint,10,opt,name=laser_bias_alarm_high,json=laserBiasAlarmHigh" json:"laser_bias_alarm_high,omitempty"`
	// Laser bias high warning threshold (uA)
	LaserBiasWarningHigh uint32 `protobuf:"varint,11,opt,name=laser_bias_warning_high,json=laserBiasWarningHigh" json:"laser_bias_warning_high,omitempty"`
	// Laser bias low warning threshold (uA)
	LaserBiasWarningLow uint32 `protobuf:"varint,12,opt,name=laser_bias_warning_low,json=laserBiasWarningLow" json:"laser_bias_warning_low,omitempty"`
	// Laser bias low alarm threshold (uA)
	LaserBiasAlarmLow uint32 `protobuf:"varint,13,opt,name=laser_bias_alarm_low,json=laserBiasAlarmLow" json:"laser_bias_alarm_low,omitempty"`
	// High optical transmit power alarm threshold (uW)
	OpticalTransmitPowerAlarmHigh uint32 `protobuf:"varint,14,opt,name=optical_transmit_power_alarm_high,json=opticalTransmitPowerAlarmHigh" json:"optical_transmit_power_alarm_high,omitempty"`
	// High optical transmit power warning threshold (uW)
	OpticalTransmitPowerWarningHigh uint32 `protobuf:"varint,15,opt,name=optical_transmit_power_warning_high,json=opticalTransmitPowerWarningHigh" json:"optical_transmit_power_warning_high,omitempty"`
	// Low optical transmit power warning threshold (uW)
	OpticalTransmitPowerWarningLow uint32 `protobuf:"varint,16,opt,name=optical_transmit_power_warning_low,json=opticalTransmitPowerWarningLow" json:"optical_transmit_power_warning_low,omitempty"`
	// Low optical transmit power alarm threshold (uW)
	OpticalTransmitPowerAlarmLow uint32 `protobuf:"varint,17,opt,name=optical_transmit_power_alarm_low,json=opticalTransmitPowerAlarmLow" json:"optical_transmit_power_alarm_low,omitempty"`
	// High optical receive power alarm threshold (uW)
	OpticalReceivePowerAlarmHigh uint32 `protobuf:"varint,18,opt,name=optical_receive_power_alarm_high,json=opticalReceivePowerAlarmHigh" json:"optical_receive_power_alarm_high,omitempty"`
	// High optical receive power warning threshold (uW)
	OpticalReceivePowerWarningHigh uint32 `protobuf:"varint,19,opt,name=optical_receive_power_warning_high,json=opticalReceivePowerWarningHigh" json:"optical_receive_power_warning_high,omitempty"`
	// Low optical receive power warning threshold (uW)
	OpticalReceivePowerWarningLow uint32 `protobuf:"varint,20,opt,name=optical_receive_power_warning_low,json=opticalReceivePowerWarningLow" json:"optical_receive_power_warning_low,omitempty"`
	// Low optical receive power alarm threshold (uW)
	OpticalReceivePowerAlarmLow uint32 `protobuf:"varint,21,opt,name=optical_receive_power_alarm_low,json=opticalReceivePowerAlarmLow" json:"optical_receive_power_alarm_low,omitempty"`
}

func (m *EthCtrlrPhyDomThresholds) Reset()                    { *m = EthCtrlrPhyDomThresholds{} }
func (m *EthCtrlrPhyDomThresholds) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrPhyDomThresholds) ProtoMessage()               {}
func (*EthCtrlrPhyDomThresholds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EthCtrlrPhyDomThresholds) GetFieldValidity() *EthCtrlrPhyDomThresholdValidity {
	if m != nil {
		return m.FieldValidity
	}
	return nil
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverTemperatureAlarmHigh() int32 {
	if m != nil {
		return m.TransceiverTemperatureAlarmHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverTemperatureWarningHigh() int32 {
	if m != nil {
		return m.TransceiverTemperatureWarningHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverTemperatureWarningLow() int32 {
	if m != nil {
		return m.TransceiverTemperatureWarningLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverTemperatureAlarmLow() int32 {
	if m != nil {
		return m.TransceiverTemperatureAlarmLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverVoltageAlarmHigh() uint32 {
	if m != nil {
		return m.TransceiverVoltageAlarmHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverVoltageWarningHigh() uint32 {
	if m != nil {
		return m.TransceiverVoltageWarningHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverVoltageWarningLow() uint32 {
	if m != nil {
		return m.TransceiverVoltageWarningLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetTransceiverVoltageAlarmLow() uint32 {
	if m != nil {
		return m.TransceiverVoltageAlarmLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetLaserBiasAlarmHigh() uint32 {
	if m != nil {
		return m.LaserBiasAlarmHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetLaserBiasWarningHigh() uint32 {
	if m != nil {
		return m.LaserBiasWarningHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetLaserBiasWarningLow() uint32 {
	if m != nil {
		return m.LaserBiasWarningLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetLaserBiasAlarmLow() uint32 {
	if m != nil {
		return m.LaserBiasAlarmLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalTransmitPowerAlarmHigh() uint32 {
	if m != nil {
		return m.OpticalTransmitPowerAlarmHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalTransmitPowerWarningHigh() uint32 {
	if m != nil {
		return m.OpticalTransmitPowerWarningHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalTransmitPowerWarningLow() uint32 {
	if m != nil {
		return m.OpticalTransmitPowerWarningLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalTransmitPowerAlarmLow() uint32 {
	if m != nil {
		return m.OpticalTransmitPowerAlarmLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalReceivePowerAlarmHigh() uint32 {
	if m != nil {
		return m.OpticalReceivePowerAlarmHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalReceivePowerWarningHigh() uint32 {
	if m != nil {
		return m.OpticalReceivePowerWarningHigh
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalReceivePowerWarningLow() uint32 {
	if m != nil {
		return m.OpticalReceivePowerWarningLow
	}
	return 0
}

func (m *EthCtrlrPhyDomThresholds) GetOpticalReceivePowerAlarmLow() uint32 {
	if m != nil {
		return m.OpticalReceivePowerAlarmLow
	}
	return 0
}

type EtherPhyDetails struct {
	// Name of the port optics manufacturer
	Vendor string `protobuf:"bytes,1,opt,name=vendor" json:"vendor,omitempty"`
	// Part number for the port optics
	VendorPartNumber string `protobuf:"bytes,2,opt,name=vendor_part_number,json=vendorPartNumber" json:"vendor_part_number,omitempty"`
	// Serial number for the port optics
	VendorSerialNumber string `protobuf:"bytes,3,opt,name=vendor_serial_number,json=vendorSerialNumber" json:"vendor_serial_number,omitempty"`
	// The temperature of the transceiver (mDegrees C)
	TransceiverTemperature int32 `protobuf:"zigzag32,4,opt,name=transceiver_temperature,json=transceiverTemperature" json:"transceiver_temperature,omitempty"`
	// The input voltage to the transceiver (mV)
	TransceiverVoltage int32 `protobuf:"zigzag32,5,opt,name=transceiver_voltage,json=transceiverVoltage" json:"transceiver_voltage,omitempty"`
	// The transceiver transmit laser power (uW)
	TransceiverTxPower int32 `protobuf:"zigzag32,6,opt,name=transceiver_tx_power,json=transceiverTxPower" json:"transceiver_tx_power,omitempty"`
	// The transceiver receive optical power (uW)
	TransceiverRxPower int32 `protobuf:"zigzag32,7,opt,name=transceiver_rx_power,json=transceiverRxPower" json:"transceiver_rx_power,omitempty"`
	// The laser bias of the transceiver (uA)
	TransceiverTxBias int32 `protobuf:"zigzag32,8,opt,name=transceiver_tx_bias,json=transceiverTxBias" json:"transceiver_tx_bias,omitempty"`
	// Digital Optical Monitoring (per lane information)
	Lane []*EthCtrlrPhyLaneOptMon `protobuf:"bytes,9,rep,name=lane" json:"lane,omitempty"`
	// Digital Optical Monitoring (per lane information) validity
	LaneFieldValidity *EthCtrlrPhyLaneOptMonValidity `protobuf:"bytes,10,opt,name=lane_field_validity,json=laneFieldValidity" json:"lane_field_validity,omitempty"`
	// Digital Optical Monitoring alarm thresholds
	DigOptMonAlarmThresholds *EthCtrlrPhyDomThresholds `protobuf:"bytes,11,opt,name=dig_opt_mon_alarm_thresholds,json=digOptMonAlarmThresholds" json:"dig_opt_mon_alarm_thresholds,omitempty"`
	// Digital Optical Monitoring alarms
	DigOptMonAlarms *EthCtrlrPhyDomAlarms `protobuf:"bytes,12,opt,name=dig_opt_mon_alarms,json=digOptMonAlarms" json:"dig_opt_mon_alarms,omitempty"`
	// Wavelength of the optics being used in nm * 1000
	OpticsWavelength uint32 `protobuf:"varint,13,opt,name=optics_wavelength,json=opticsWavelength" json:"optics_wavelength,omitempty"`
	// Optics module type
	OpticsType string `protobuf:"bytes,14,opt,name=optics_type,json=opticsType" json:"optics_type,omitempty"`
	// Module revision number
	RevisionNumber string `protobuf:"bytes,15,opt,name=revision_number,json=revisionNumber" json:"revision_number,omitempty"`
}

func (m *EtherPhyDetails) Reset()                    { *m = EtherPhyDetails{} }
func (m *EtherPhyDetails) String() string            { return proto.CompactTextString(m) }
func (*EtherPhyDetails) ProtoMessage()               {}
func (*EtherPhyDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *EtherPhyDetails) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *EtherPhyDetails) GetVendorPartNumber() string {
	if m != nil {
		return m.VendorPartNumber
	}
	return ""
}

func (m *EtherPhyDetails) GetVendorSerialNumber() string {
	if m != nil {
		return m.VendorSerialNumber
	}
	return ""
}

func (m *EtherPhyDetails) GetTransceiverTemperature() int32 {
	if m != nil {
		return m.TransceiverTemperature
	}
	return 0
}

func (m *EtherPhyDetails) GetTransceiverVoltage() int32 {
	if m != nil {
		return m.TransceiverVoltage
	}
	return 0
}

func (m *EtherPhyDetails) GetTransceiverTxPower() int32 {
	if m != nil {
		return m.TransceiverTxPower
	}
	return 0
}

func (m *EtherPhyDetails) GetTransceiverRxPower() int32 {
	if m != nil {
		return m.TransceiverRxPower
	}
	return 0
}

func (m *EtherPhyDetails) GetTransceiverTxBias() int32 {
	if m != nil {
		return m.TransceiverTxBias
	}
	return 0
}

func (m *EtherPhyDetails) GetLane() []*EthCtrlrPhyLaneOptMon {
	if m != nil {
		return m.Lane
	}
	return nil
}

func (m *EtherPhyDetails) GetLaneFieldValidity() *EthCtrlrPhyLaneOptMonValidity {
	if m != nil {
		return m.LaneFieldValidity
	}
	return nil
}

func (m *EtherPhyDetails) GetDigOptMonAlarmThresholds() *EthCtrlrPhyDomThresholds {
	if m != nil {
		return m.DigOptMonAlarmThresholds
	}
	return nil
}

func (m *EtherPhyDetails) GetDigOptMonAlarms() *EthCtrlrPhyDomAlarms {
	if m != nil {
		return m.DigOptMonAlarms
	}
	return nil
}

func (m *EtherPhyDetails) GetOpticsWavelength() uint32 {
	if m != nil {
		return m.OpticsWavelength
	}
	return 0
}

func (m *EtherPhyDetails) GetOpticsType() string {
	if m != nil {
		return m.OpticsType
	}
	return ""
}

func (m *EtherPhyDetails) GetRevisionNumber() string {
	if m != nil {
		return m.RevisionNumber
	}
	return ""
}

type EthCtrlrAlarms struct {
	// Received Loss of Signal
	ReceivedLossOfSignalAlarm string `protobuf:"bytes,1,opt,name=received_loss_of_signal_alarm,json=receivedLossOfSignalAlarm" json:"received_loss_of_signal_alarm,omitempty"`
	// PCS Loss of Block Lock
	PcsLossOfBlockLockAlarm string `protobuf:"bytes,2,opt,name=pcs_loss_of_block_lock_alarm,json=pcsLossOfBlockLockAlarm" json:"pcs_loss_of_block_lock_alarm,omitempty"`
	// Local Fault
	LocalFaultAlarm string `protobuf:"bytes,3,opt,name=local_fault_alarm,json=localFaultAlarm" json:"local_fault_alarm,omitempty"`
	// Remote Fault
	RemoteFaultAlarm string `protobuf:"bytes,4,opt,name=remote_fault_alarm,json=remoteFaultAlarm" json:"remote_fault_alarm,omitempty"`
	// SD-BER
	SdBerAlarm string `protobuf:"bytes,5,opt,name=sd_ber_alarm,json=sdBerAlarm" json:"sd_ber_alarm,omitempty"`
	// SF-BER
	SfBerAlarm string `protobuf:"bytes,6,opt,name=sf_ber_alarm,json=sfBerAlarm" json:"sf_ber_alarm,omitempty"`
	// Loss of Synchronization Data
	LossOfSynchronizationDataAlarm string `protobuf:"bytes,7,opt,name=loss_of_synchronization_data_alarm,json=lossOfSynchronizationDataAlarm" json:"loss_of_synchronization_data_alarm,omitempty"`
	// Hi-BER
	HiBerAlarm string `protobuf:"bytes,8,opt,name=hi_ber_alarm,json=hiBerAlarm" json:"hi_ber_alarm,omitempty"`
	// Squelch
	SquelchAlarm string `protobuf:"bytes,9,opt,name=squelch_alarm,json=squelchAlarm" json:"squelch_alarm,omitempty"`
	// Rx OPD Alarm
	RxOpdAlarm string `protobuf:"bytes,10,opt,name=rx_opd_alarm,json=rxOpdAlarm" json:"rx_opd_alarm,omitempty"`
}

func (m *EthCtrlrAlarms) Reset()                    { *m = EthCtrlrAlarms{} }
func (m *EthCtrlrAlarms) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrAlarms) ProtoMessage()               {}
func (*EthCtrlrAlarms) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *EthCtrlrAlarms) GetReceivedLossOfSignalAlarm() string {
	if m != nil {
		return m.ReceivedLossOfSignalAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetPcsLossOfBlockLockAlarm() string {
	if m != nil {
		return m.PcsLossOfBlockLockAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetLocalFaultAlarm() string {
	if m != nil {
		return m.LocalFaultAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetRemoteFaultAlarm() string {
	if m != nil {
		return m.RemoteFaultAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetSdBerAlarm() string {
	if m != nil {
		return m.SdBerAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetSfBerAlarm() string {
	if m != nil {
		return m.SfBerAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetLossOfSynchronizationDataAlarm() string {
	if m != nil {
		return m.LossOfSynchronizationDataAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetHiBerAlarm() string {
	if m != nil {
		return m.HiBerAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetSquelchAlarm() string {
	if m != nil {
		return m.SquelchAlarm
	}
	return ""
}

func (m *EthCtrlrAlarms) GetRxOpdAlarm() string {
	if m != nil {
		return m.RxOpdAlarm
	}
	return ""
}

type EthCtrlrErrorCounters struct {
	// Sync-header error count
	SyncHeaderErrors uint64 `protobuf:"varint,1,opt,name=sync_header_errors,json=syncHeaderErrors" json:"sync_header_errors,omitempty"`
	// PCS BIP error count
	PcsbipErrors uint64 `protobuf:"varint,2,opt,name=pcsbip_errors,json=pcsbipErrors" json:"pcsbip_errors,omitempty"`
}

func (m *EthCtrlrErrorCounters) Reset()                    { *m = EthCtrlrErrorCounters{} }
func (m *EthCtrlrErrorCounters) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrErrorCounters) ProtoMessage()               {}
func (*EthCtrlrErrorCounters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *EthCtrlrErrorCounters) GetSyncHeaderErrors() uint64 {
	if m != nil {
		return m.SyncHeaderErrors
	}
	return 0
}

func (m *EthCtrlrErrorCounters) GetPcsbipErrors() uint64 {
	if m != nil {
		return m.PcsbipErrors
	}
	return 0
}

type EtherBerSettings struct {
	// BER threshold for signal to degrade
	SignalDegradeThreshold uint32 `protobuf:"varint,1,opt,name=signal_degrade_threshold,json=signalDegradeThreshold" json:"signal_degrade_threshold,omitempty"`
	// Report alarm to indicate signal degrade
	SignalDegradeAlarm int32 `protobuf:"zigzag32,2,opt,name=signal_degrade_alarm,json=signalDegradeAlarm" json:"signal_degrade_alarm,omitempty"`
	// BER threshold for signal to fail
	SignalFailThreshold uint32 `protobuf:"varint,3,opt,name=signal_fail_threshold,json=signalFailThreshold" json:"signal_fail_threshold,omitempty"`
	// Report alarm to indicate signal failure
	SignalFailAlarm int32 `protobuf:"zigzag32,4,opt,name=signal_fail_alarm,json=signalFailAlarm" json:"signal_fail_alarm,omitempty"`
	// Whether drivers should signal remote faults
	SignalRemoteFault int32 `protobuf:"zigzag32,5,opt,name=signal_remote_fault,json=signalRemoteFault" json:"signal_remote_fault,omitempty"`
}

func (m *EtherBerSettings) Reset()                    { *m = EtherBerSettings{} }
func (m *EtherBerSettings) String() string            { return proto.CompactTextString(m) }
func (*EtherBerSettings) ProtoMessage()               {}
func (*EtherBerSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *EtherBerSettings) GetSignalDegradeThreshold() uint32 {
	if m != nil {
		return m.SignalDegradeThreshold
	}
	return 0
}

func (m *EtherBerSettings) GetSignalDegradeAlarm() int32 {
	if m != nil {
		return m.SignalDegradeAlarm
	}
	return 0
}

func (m *EtherBerSettings) GetSignalFailThreshold() uint32 {
	if m != nil {
		return m.SignalFailThreshold
	}
	return 0
}

func (m *EtherBerSettings) GetSignalFailAlarm() int32 {
	if m != nil {
		return m.SignalFailAlarm
	}
	return 0
}

func (m *EtherBerSettings) GetSignalRemoteFault() int32 {
	if m != nil {
		return m.SignalRemoteFault
	}
	return 0
}

type EthBerMonitoring struct {
	// Whether or not BER monitoring is supported
	Supported int32 `protobuf:"zigzag32,1,opt,name=supported" json:"supported,omitempty"`
	// The BER monitoring settings to be applied
	Settings *EtherBerSettings `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
}

func (m *EthBerMonitoring) Reset()                    { *m = EthBerMonitoring{} }
func (m *EthBerMonitoring) String() string            { return proto.CompactTextString(m) }
func (*EthBerMonitoring) ProtoMessage()               {}
func (*EthBerMonitoring) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *EthBerMonitoring) GetSupported() int32 {
	if m != nil {
		return m.Supported
	}
	return 0
}

func (m *EthBerMonitoring) GetSettings() *EtherBerSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type EtherOpdSettings struct {
	// Rx-OPD alarm threshold set?
	ReceivedOpticalPowerDegradeThresholdSet int32 `protobuf:"zigzag32,1,opt,name=received_optical_power_degrade_threshold_set,json=receivedOpticalPowerDegradeThresholdSet" json:"received_optical_power_degrade_threshold_set,omitempty"`
	// Rx-OPD alarm threshold value
	ReceivedOpticalPowerDegradeThreshold int32 `protobuf:"zigzag32,2,opt,name=received_optical_power_degrade_threshold,json=receivedOpticalPowerDegradeThreshold" json:"received_optical_power_degrade_threshold,omitempty"`
}

func (m *EtherOpdSettings) Reset()                    { *m = EtherOpdSettings{} }
func (m *EtherOpdSettings) String() string            { return proto.CompactTextString(m) }
func (*EtherOpdSettings) ProtoMessage()               {}
func (*EtherOpdSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *EtherOpdSettings) GetReceivedOpticalPowerDegradeThresholdSet() int32 {
	if m != nil {
		return m.ReceivedOpticalPowerDegradeThresholdSet
	}
	return 0
}

func (m *EtherOpdSettings) GetReceivedOpticalPowerDegradeThreshold() int32 {
	if m != nil {
		return m.ReceivedOpticalPowerDegradeThreshold
	}
	return 0
}

type EthOpdMonitoring struct {
	// Whether or not OPD monitoring is supported
	Supported int32 `protobuf:"zigzag32,1,opt,name=supported" json:"supported,omitempty"`
	// The OPD monitoring settings to be applied
	Settings *EtherOpdSettings `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
}

func (m *EthOpdMonitoring) Reset()                    { *m = EthOpdMonitoring{} }
func (m *EthOpdMonitoring) String() string            { return proto.CompactTextString(m) }
func (*EthOpdMonitoring) ProtoMessage()               {}
func (*EthOpdMonitoring) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *EthOpdMonitoring) GetSupported() int32 {
	if m != nil {
		return m.Supported
	}
	return 0
}

func (m *EthOpdMonitoring) GetSettings() *EtherOpdSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type EthCtrlrUcastMacFilter struct {
	// MAC addresses in the unicast ingress destination MAC filter
	UnicastMacAddresses []*MacAddrType `protobuf:"bytes,1,rep,name=unicast_mac_addresses,json=unicastMacAddresses" json:"unicast_mac_addresses,omitempty"`
}

func (m *EthCtrlrUcastMacFilter) Reset()                    { *m = EthCtrlrUcastMacFilter{} }
func (m *EthCtrlrUcastMacFilter) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrUcastMacFilter) ProtoMessage()               {}
func (*EthCtrlrUcastMacFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *EthCtrlrUcastMacFilter) GetUnicastMacAddresses() []*MacAddrType {
	if m != nil {
		return m.UnicastMacAddresses
	}
	return nil
}

type EthCtrlrMcastMacFilter struct {
	// Whether the port is in multicast promiscuous mode
	MulticastPromiscuous uint32 `protobuf:"varint,1,opt,name=multicast_promiscuous,json=multicastPromiscuous" json:"multicast_promiscuous,omitempty"`
	// MAC addresses in the multicast ingress destination MAC filter
	MulticastMacAddresses []*EtherMcastMacType_ `protobuf:"bytes,2,rep,name=multicast_mac_addresses,json=multicastMacAddresses" json:"multicast_mac_addresses,omitempty"`
}

func (m *EthCtrlrMcastMacFilter) Reset()                    { *m = EthCtrlrMcastMacFilter{} }
func (m *EthCtrlrMcastMacFilter) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrMcastMacFilter) ProtoMessage()               {}
func (*EthCtrlrMcastMacFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *EthCtrlrMcastMacFilter) GetMulticastPromiscuous() uint32 {
	if m != nil {
		return m.MulticastPromiscuous
	}
	return 0
}

func (m *EthCtrlrMcastMacFilter) GetMulticastMacAddresses() []*EtherMcastMacType_ {
	if m != nil {
		return m.MulticastMacAddresses
	}
	return nil
}

type EtherFecDetails struct {
	// Port operational FEC type
	Fec string `protobuf:"bytes,1,opt,name=fec" json:"fec,omitempty"`
	// Corrected codeword error count
	CorrectedCodewordCount uint64 `protobuf:"varint,2,opt,name=corrected_codeword_count,json=correctedCodewordCount" json:"corrected_codeword_count,omitempty"`
	// Uncorrected codeword error count
	UncorrectedCodewordCount uint64 `protobuf:"varint,3,opt,name=uncorrected_codeword_count,json=uncorrectedCodewordCount" json:"uncorrected_codeword_count,omitempty"`
}

func (m *EtherFecDetails) Reset()                    { *m = EtherFecDetails{} }
func (m *EtherFecDetails) String() string            { return proto.CompactTextString(m) }
func (*EtherFecDetails) ProtoMessage()               {}
func (*EtherFecDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *EtherFecDetails) GetFec() string {
	if m != nil {
		return m.Fec
	}
	return ""
}

func (m *EtherFecDetails) GetCorrectedCodewordCount() uint64 {
	if m != nil {
		return m.CorrectedCodewordCount
	}
	return 0
}

func (m *EtherFecDetails) GetUncorrectedCodewordCount() uint64 {
	if m != nil {
		return m.UncorrectedCodewordCount
	}
	return 0
}

type EtherPfcDetailsType struct {
	// Port operational priority flow control
	PriorityFlowcontrol string `protobuf:"bytes,1,opt,name=priority_flowcontrol,json=priorityFlowcontrol" json:"priority_flowcontrol,omitempty"`
	// Priority bitmap
	PriorityEnabledBitmap uint32 `protobuf:"varint,2,opt,name=priority_enabled_bitmap,json=priorityEnabledBitmap" json:"priority_enabled_bitmap,omitempty"`
	// RX Frame counts
	RxFrames []uint64 `protobuf:"varint,3,rep,packed,name=rx_frames,json=rxFrames" json:"rx_frames,omitempty"`
	// TX Frame counts
	TxFrames []uint64 `protobuf:"varint,4,rep,packed,name=tx_frames,json=txFrames" json:"tx_frames,omitempty"`
}

func (m *EtherPfcDetailsType) Reset()                    { *m = EtherPfcDetailsType{} }
func (m *EtherPfcDetailsType) String() string            { return proto.CompactTextString(m) }
func (*EtherPfcDetailsType) ProtoMessage()               {}
func (*EtherPfcDetailsType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *EtherPfcDetailsType) GetPriorityFlowcontrol() string {
	if m != nil {
		return m.PriorityFlowcontrol
	}
	return ""
}

func (m *EtherPfcDetailsType) GetPriorityEnabledBitmap() uint32 {
	if m != nil {
		return m.PriorityEnabledBitmap
	}
	return 0
}

func (m *EtherPfcDetailsType) GetRxFrames() []uint64 {
	if m != nil {
		return m.RxFrames
	}
	return nil
}

func (m *EtherPfcDetailsType) GetTxFrames() []uint64 {
	if m != nil {
		return m.TxFrames
	}
	return nil
}

type ExtendedLoopbackType struct {
	// Level
	Level uint32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	// Port operational loopback
	Loopback string `protobuf:"bytes,2,opt,name=loopback" json:"loopback,omitempty"`
}

func (m *ExtendedLoopbackType) Reset()                    { *m = ExtendedLoopbackType{} }
func (m *ExtendedLoopbackType) String() string            { return proto.CompactTextString(m) }
func (*ExtendedLoopbackType) ProtoMessage()               {}
func (*ExtendedLoopbackType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ExtendedLoopbackType) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ExtendedLoopbackType) GetLoopback() string {
	if m != nil {
		return m.Loopback
	}
	return ""
}

type EthCtrlrPhyInfo struct {
	// Port media type
	MediaType string `protobuf:"bytes,1,opt,name=media_type,json=mediaType" json:"media_type,omitempty"`
	// Presence of PHY
	PhyPresent string `protobuf:"bytes,2,opt,name=phy_present,json=phyPresent" json:"phy_present,omitempty"`
	// Details about the PHY
	PhyDetails *EtherPhyDetails `protobuf:"bytes,3,opt,name=phy_details,json=phyDetails" json:"phy_details,omitempty"`
	// Port operational loopback
	Loopback string `protobuf:"bytes,4,opt,name=loopback" json:"loopback,omitempty"`
	// Forward Error Correction information
	FecDetails *EtherFecDetails `protobuf:"bytes,5,opt,name=fec_details,json=fecDetails" json:"fec_details,omitempty"`
	// Port operational extended loopback
	ExtendedLoopback []*ExtendedLoopbackType `protobuf:"bytes,6,rep,name=extended_loopback,json=extendedLoopback" json:"extended_loopback,omitempty"`
}

func (m *EthCtrlrPhyInfo) Reset()                    { *m = EthCtrlrPhyInfo{} }
func (m *EthCtrlrPhyInfo) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrPhyInfo) ProtoMessage()               {}
func (*EthCtrlrPhyInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *EthCtrlrPhyInfo) GetMediaType() string {
	if m != nil {
		return m.MediaType
	}
	return ""
}

func (m *EthCtrlrPhyInfo) GetPhyPresent() string {
	if m != nil {
		return m.PhyPresent
	}
	return ""
}

func (m *EthCtrlrPhyInfo) GetPhyDetails() *EtherPhyDetails {
	if m != nil {
		return m.PhyDetails
	}
	return nil
}

func (m *EthCtrlrPhyInfo) GetLoopback() string {
	if m != nil {
		return m.Loopback
	}
	return ""
}

func (m *EthCtrlrPhyInfo) GetFecDetails() *EtherFecDetails {
	if m != nil {
		return m.FecDetails
	}
	return nil
}

func (m *EthCtrlrPhyInfo) GetExtendedLoopback() []*ExtendedLoopbackType {
	if m != nil {
		return m.ExtendedLoopback
	}
	return nil
}

type EthCtrlrL1Info struct {
	// Link state
	LinkState string `protobuf:"bytes,1,opt,name=link_state,json=linkState" json:"link_state,omitempty"`
	// State of the LED
	LedState string `protobuf:"bytes,2,opt,name=led_state,json=ledState" json:"led_state,omitempty"`
	// Port autonegotiation configuration settings
	Autoneg *EtherAutoneg_ `protobuf:"bytes,3,opt,name=autoneg" json:"autoneg,omitempty"`
	// Port operational speed
	Speed string `protobuf:"bytes,4,opt,name=speed" json:"speed,omitempty"`
	// Port operational duplexity
	Duplex string `protobuf:"bytes,5,opt,name=duplex" json:"duplex,omitempty"`
	// Port operational flow control
	Flowcontrol string `protobuf:"bytes,6,opt,name=flowcontrol" json:"flowcontrol,omitempty"`
	// Port operational inter-packet-gap
	Ipg string `protobuf:"bytes,7,opt,name=ipg" json:"ipg,omitempty"`
	// Current alarms
	CurrentAlarms *EthCtrlrAlarms `protobuf:"bytes,8,opt,name=current_alarms,json=currentAlarms" json:"current_alarms,omitempty"`
	// Previous alarms
	PreviousAlarms *EthCtrlrAlarms `protobuf:"bytes,9,opt,name=previous_alarms,json=previousAlarms" json:"previous_alarms,omitempty"`
	// Statistics for detected errors
	ErrorCounts *EthCtrlrErrorCounters `protobuf:"bytes,10,opt,name=error_counts,json=errorCounts" json:"error_counts,omitempty"`
	// BER monitoring details
	BerMonitoring *EthBerMonitoring `protobuf:"bytes,11,opt,name=ber_monitoring,json=berMonitoring" json:"ber_monitoring,omitempty"`
	// OPD monitoring details
	OpdMonitoring *EthOpdMonitoring `protobuf:"bytes,12,opt,name=opd_monitoring,json=opdMonitoring" json:"opd_monitoring,omitempty"`
	// Laser Squelch - TRUE if enabled
	LaserSquelchEnabled uint32 `protobuf:"varint,13,opt,name=laser_squelch_enabled,json=laserSquelchEnabled" json:"laser_squelch_enabled,omitempty"`
	// Bandwidth utilization (hundredths of a percent)
	BandwidthUtilization uint32 `protobuf:"varint,14,opt,name=bandwidth_utilization,json=bandwidthUtilization" json:"bandwidth_utilization,omitempty"`
	// Priority flow control information
	PfcInfo *EtherPfcDetailsType `protobuf:"bytes,15,opt,name=pfc_info,json=pfcInfo" json:"pfc_info,omitempty"`
	// Port operational bandwidth
	Bandwidth uint64 `protobuf:"varint,16,opt,name=bandwidth" json:"bandwidth,omitempty"`
}

func (m *EthCtrlrL1Info) Reset()                    { *m = EthCtrlrL1Info{} }
func (m *EthCtrlrL1Info) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrL1Info) ProtoMessage()               {}
func (*EthCtrlrL1Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *EthCtrlrL1Info) GetLinkState() string {
	if m != nil {
		return m.LinkState
	}
	return ""
}

func (m *EthCtrlrL1Info) GetLedState() string {
	if m != nil {
		return m.LedState
	}
	return ""
}

func (m *EthCtrlrL1Info) GetAutoneg() *EtherAutoneg_ {
	if m != nil {
		return m.Autoneg
	}
	return nil
}

func (m *EthCtrlrL1Info) GetSpeed() string {
	if m != nil {
		return m.Speed
	}
	return ""
}

func (m *EthCtrlrL1Info) GetDuplex() string {
	if m != nil {
		return m.Duplex
	}
	return ""
}

func (m *EthCtrlrL1Info) GetFlowcontrol() string {
	if m != nil {
		return m.Flowcontrol
	}
	return ""
}

func (m *EthCtrlrL1Info) GetIpg() string {
	if m != nil {
		return m.Ipg
	}
	return ""
}

func (m *EthCtrlrL1Info) GetCurrentAlarms() *EthCtrlrAlarms {
	if m != nil {
		return m.CurrentAlarms
	}
	return nil
}

func (m *EthCtrlrL1Info) GetPreviousAlarms() *EthCtrlrAlarms {
	if m != nil {
		return m.PreviousAlarms
	}
	return nil
}

func (m *EthCtrlrL1Info) GetErrorCounts() *EthCtrlrErrorCounters {
	if m != nil {
		return m.ErrorCounts
	}
	return nil
}

func (m *EthCtrlrL1Info) GetBerMonitoring() *EthBerMonitoring {
	if m != nil {
		return m.BerMonitoring
	}
	return nil
}

func (m *EthCtrlrL1Info) GetOpdMonitoring() *EthOpdMonitoring {
	if m != nil {
		return m.OpdMonitoring
	}
	return nil
}

func (m *EthCtrlrL1Info) GetLaserSquelchEnabled() uint32 {
	if m != nil {
		return m.LaserSquelchEnabled
	}
	return 0
}

func (m *EthCtrlrL1Info) GetBandwidthUtilization() uint32 {
	if m != nil {
		return m.BandwidthUtilization
	}
	return 0
}

func (m *EthCtrlrL1Info) GetPfcInfo() *EtherPfcDetailsType {
	if m != nil {
		return m.PfcInfo
	}
	return nil
}

func (m *EthCtrlrL1Info) GetBandwidth() uint64 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

type EthCtrlrMacInfo struct {
	// Port operational MTU
	Mtu uint32 `protobuf:"varint,1,opt,name=mtu" json:"mtu,omitempty"`
	// Port operational MRU
	Mru uint32 `protobuf:"varint,2,opt,name=mru" json:"mru,omitempty"`
	// Port Burned-In MAC address
	BurnedInMacAddress string `protobuf:"bytes,3,opt,name=burned_in_mac_address,json=burnedInMacAddress" json:"burned_in_mac_address,omitempty"`
	// Port operational MAC address
	OperationalMacAddress *MacAddrType `protobuf:"bytes,4,opt,name=operational_mac_address,json=operationalMacAddress" json:"operational_mac_address,omitempty"`
	// Port unicast MAC filter information
	UnicastMacFilters *EthCtrlrUcastMacFilter `protobuf:"bytes,5,opt,name=unicast_mac_filters,json=unicastMacFilters" json:"unicast_mac_filters,omitempty"`
	// Port multicast MAC filter information
	MulticastMacFilters *EthCtrlrMcastMacFilter `protobuf:"bytes,6,opt,name=multicast_mac_filters,json=multicastMacFilters" json:"multicast_mac_filters,omitempty"`
}

func (m *EthCtrlrMacInfo) Reset()                    { *m = EthCtrlrMacInfo{} }
func (m *EthCtrlrMacInfo) String() string            { return proto.CompactTextString(m) }
func (*EthCtrlrMacInfo) ProtoMessage()               {}
func (*EthCtrlrMacInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *EthCtrlrMacInfo) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *EthCtrlrMacInfo) GetMru() uint32 {
	if m != nil {
		return m.Mru
	}
	return 0
}

func (m *EthCtrlrMacInfo) GetBurnedInMacAddress() string {
	if m != nil {
		return m.BurnedInMacAddress
	}
	return ""
}

func (m *EthCtrlrMacInfo) GetOperationalMacAddress() *MacAddrType {
	if m != nil {
		return m.OperationalMacAddress
	}
	return nil
}

func (m *EthCtrlrMacInfo) GetUnicastMacFilters() *EthCtrlrUcastMacFilter {
	if m != nil {
		return m.UnicastMacFilters
	}
	return nil
}

func (m *EthCtrlrMacInfo) GetMulticastMacFilters() *EthCtrlrMcastMacFilter {
	if m != nil {
		return m.MulticastMacFilters
	}
	return nil
}

type EthCtlrTransportInfo struct {
	// Maintenance Mode - TRUE if enabled
	MaintenanceModeEnabled uint32 `protobuf:"varint,1,opt,name=maintenance_mode_enabled,json=maintenanceModeEnabled" json:"maintenance_mode_enabled,omitempty"`
	// AINS Soak status
	AinsStatus string `protobuf:"bytes,2,opt,name=ains_status,json=ainsStatus" json:"ains_status,omitempty"`
	// Total duration (seconds) of AINS soak timer
	TotalDuration uint32 `protobuf:"varint,3,opt,name=total_duration,json=totalDuration" json:"total_duration,omitempty"`
	// Remaining duration (seconds) of AINS soak timer
	RemainingDuration uint32 `protobuf:"varint,4,opt,name=remaining_duration,json=remainingDuration" json:"remaining_duration,omitempty"`
}

func (m *EthCtlrTransportInfo) Reset()                    { *m = EthCtlrTransportInfo{} }
func (m *EthCtlrTransportInfo) String() string            { return proto.CompactTextString(m) }
func (*EthCtlrTransportInfo) ProtoMessage()               {}
func (*EthCtlrTransportInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *EthCtlrTransportInfo) GetMaintenanceModeEnabled() uint32 {
	if m != nil {
		return m.MaintenanceModeEnabled
	}
	return 0
}

func (m *EthCtlrTransportInfo) GetAinsStatus() string {
	if m != nil {
		return m.AinsStatus
	}
	return ""
}

func (m *EthCtlrTransportInfo) GetTotalDuration() uint32 {
	if m != nil {
		return m.TotalDuration
	}
	return 0
}

func (m *EthCtlrTransportInfo) GetRemainingDuration() uint32 {
	if m != nil {
		return m.RemainingDuration
	}
	return 0
}

func init() {
	proto.RegisterType((*EthernetControllerDriverBagV2Type_KEYS)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ethernet_controller_driver_bag_v2_type_KEYS")
	proto.RegisterType((*EthernetControllerDriverBagV2Type)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ethernet_controller_driver_bag_v2_type")
	proto.RegisterType((*EtherAutoneg_)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ether_autoneg_")
	proto.RegisterType((*MacAddrType)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.mac_addr_type")
	proto.RegisterType((*EtherMcastMacType_)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ether_mcast_mac_type_")
	proto.RegisterType((*EthCtrlrPhyDomLaneAlarms)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_phy_dom_lane_alarms")
	proto.RegisterType((*EthCtrlrPhyLaneOptMonValidity)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_phy_lane_opt_mon_validity")
	proto.RegisterType((*EthCtrlrPhyLaneOptMon)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_phy_lane_opt_mon")
	proto.RegisterType((*EthCtrlrPhyDomAlarms)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_phy_dom_alarms")
	proto.RegisterType((*EthCtrlrPhyDomThresholdValidity)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_phy_dom_threshold_validity")
	proto.RegisterType((*EthCtrlrPhyDomThresholds)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_phy_dom_thresholds")
	proto.RegisterType((*EtherPhyDetails)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ether_phy_details")
	proto.RegisterType((*EthCtrlrAlarms)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_alarms")
	proto.RegisterType((*EthCtrlrErrorCounters)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_error_counters")
	proto.RegisterType((*EtherBerSettings)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ether_ber_settings")
	proto.RegisterType((*EthBerMonitoring)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ber_monitoring")
	proto.RegisterType((*EtherOpdSettings)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ether_opd_settings")
	proto.RegisterType((*EthOpdMonitoring)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_opd_monitoring")
	proto.RegisterType((*EthCtrlrUcastMacFilter)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_ucast_mac_filter")
	proto.RegisterType((*EthCtrlrMcastMacFilter)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_mcast_mac_filter")
	proto.RegisterType((*EtherFecDetails)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ether_fec_details")
	proto.RegisterType((*EtherPfcDetailsType)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.ether_pfc_details_type")
	proto.RegisterType((*ExtendedLoopbackType)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.extended_loopback_type")
	proto.RegisterType((*EthCtrlrPhyInfo)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_phy_info")
	proto.RegisterType((*EthCtrlrL1Info)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_l1_info")
	proto.RegisterType((*EthCtrlrMacInfo)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctrlr_mac_info")
	proto.RegisterType((*EthCtlrTransportInfo)(nil), "cisco_ios_xr_drivers_media_eth_oper.ethernet_interface.interfaces.interface.eth_ctlr_transport_info")
}

func init() { proto.RegisterFile("ethernet_controller_driver_bag_v2_type.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2812 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x3a, 0xcb, 0x6f, 0x24, 0x47,
	0xf9, 0xea, 0x9d, 0xf1, 0x63, 0xbe, 0xf1, 0xd8, 0x33, 0xe5, 0xd7, 0xfc, 0x36, 0xbb, 0x6b, 0xa7,
	0x37, 0xf9, 0xc5, 0x24, 0x8b, 0xc3, 0x7a, 0x49, 0xc2, 0x01, 0x24, 0xb2, 0x0f, 0x93, 0x4d, 0xbc,
	0xd9, 0x55, 0xdb, 0xd9, 0x08, 0x50, 0x68, 0xd5, 0x74, 0xd7, 0xcc, 0x14, 0xdb, 0xdd, 0xd5, 0xa9,
	0xae, 0xf1, 0x23, 0x91, 0xc8, 0x25, 0x20, 0x24, 0x10, 0x8a, 0x22, 0xf1, 0x10, 0x08, 0x89, 0x6b,
	0x0e, 0x08, 0x71, 0xe3, 0xc2, 0x3f, 0x00, 0xff, 0x00, 0x87, 0x5c, 0xb8, 0x70, 0xe4, 0xc4, 0x1f,
	0x80, 0xea, 0xd1, 0xdd, 0xd5, 0x63, 0x8f, 0xb3, 0x2b, 0xed, 0x44, 0x5c, 0xac, 0xe9, 0xef, 0x55,
	0xdf, 0xb3, 0xea, 0xfb, 0xaa, 0x0c, 0xd7, 0x88, 0x18, 0x12, 0x9e, 0x10, 0xe1, 0x07, 0x2c, 0x11,
	0x9c, 0x45, 0x11, 0xe1, 0x7e, 0xc8, 0xe9, 0x21, 0xe1, 0x7e, 0x0f, 0x0f, 0xfc, 0xc3, 0x1d, 0x5f,
	0x9c, 0xa4, 0x64, 0x3b, 0xe5, 0x4c, 0x30, 0xf4, 0x56, 0x40, 0xb3, 0x80, 0xf9, 0x94, 0x65, 0xfe,
	0x71, 0x4e, 0x96, 0xf9, 0x31, 0x09, 0x29, 0xf6, 0x89, 0x18, 0xfa, 0x2c, 0x25, 0x7c, 0xbb, 0x90,
	0x48, 0x13, 0x41, 0x78, 0x1f, 0x07, 0x64, 0xbb, 0xf8, 0x95, 0x95, 0x3f, 0xdd, 0x03, 0x78, 0xe9,
	0xf1, 0x16, 0xf7, 0xdf, 0xba, 0xf3, 0xdd, 0x7d, 0xf4, 0x3c, 0x2c, 0x16, 0xbc, 0x7e, 0x82, 0x63,
	0xd2, 0x75, 0x36, 0x9d, 0xad, 0x86, 0xd7, 0x2a, 0xa0, 0x6f, 0xe3, 0x98, 0xb8, 0xff, 0xa9, 0xc3,
	0xff, 0x3f, 0x9e, 0x58, 0xb4, 0x01, 0x4d, 0x1c, 0xc6, 0x34, 0xf1, 0x33, 0x81, 0x05, 0xe9, 0xee,
	0x28, 0x71, 0xa0, 0x40, 0xfb, 0x12, 0x82, 0x5c, 0x68, 0x49, 0x8b, 0x34, 0xde, 0x1f, 0xa5, 0xdd,
	0x1b, 0x9b, 0xce, 0x56, 0xcb, 0x6b, 0x4a, 0xa0, 0xa2, 0x78, 0x27, 0x45, 0x1f, 0xc0, 0x7c, 0x3a,
	0x3c, 0xf1, 0x69, 0xd2, 0x67, 0xdd, 0xaf, 0x6f, 0x3a, 0x5b, 0xcd, 0x1d, 0x7f, 0xfb, 0x29, 0x7a,
	0x49, 0xd2, 0xf9, 0x81, 0xe0, 0x11, 0xf7, 0xf3, 0x65, 0xbc, 0xb9, 0x74, 0x78, 0x72, 0x37, 0xe9,
	0x33, 0xf4, 0x11, 0x34, 0x23, 0x7c, 0x42, 0xf8, 0x75, 0xbd, 0xfc, 0x2b, 0x6a, 0xf9, 0x1f, 0x4c,
	0x69, 0xf9, 0x48, 0xaf, 0xe2, 0x81, 0x5e, 0x52, 0x29, 0xf0, 0x01, 0xcc, 0xc7, 0x38, 0xd0, 0xab,
	0xbf, 0x3a, 0x55, 0xe3, 0xf3, 0x65, 0xbc, 0xb9, 0x18, 0x07, 0x6a, 0xed, 0x9f, 0x39, 0xb0, 0x28,
	0x38, 0x4e, 0xb2, 0x94, 0x71, 0xa1, 0x55, 0x78, 0x4d, 0xa9, 0x10, 0x4e, 0x41, 0x85, 0x88, 0xfb,
	0xd5, 0xb5, 0xbc, 0x56, 0xf1, 0x2d, 0xb5, 0x71, 0xff, 0xe1, 0xc0, 0xa2, 0x12, 0xe9, 0xe3, 0x91,
	0x60, 0x09, 0x19, 0xf8, 0xe8, 0x05, 0x58, 0xca, 0x7f, 0x93, 0x04, 0xf7, 0x22, 0x12, 0xaa, 0x8c,
	0xed, 0x78, 0x8b, 0x06, 0x7c, 0x47, 0x43, 0x11, 0x82, 0x7a, 0x8c, 0xb3, 0x47, 0xdd, 0x0b, 0x2a,
	0xbb, 0xd4, 0x6f, 0xb4, 0x02, 0x33, 0x59, 0x4a, 0x48, 0xd8, 0xad, 0xa9, 0xac, 0xd4, 0x1f, 0x68,
	0x0d, 0x66, 0xc3, 0x51, 0x1a, 0x91, 0xe3, 0x6e, 0x5d, 0x81, 0xcd, 0x17, 0xda, 0x84, 0x66, 0x3f,
	0x62, 0x47, 0x26, 0xdd, 0xbb, 0x33, 0x0a, 0x69, 0x83, 0xa4, 0x32, 0x01, 0x4b, 0xfa, 0x74, 0xe0,
	0xb3, 0x43, 0xc2, 0x39, 0x0d, 0x49, 0x77, 0x56, 0x2b, 0xa3, 0xc1, 0xf7, 0x0d, 0x14, 0xb5, 0xa1,
	0xd6, 0x27, 0x41, 0x77, 0x4e, 0x89, 0x90, 0x3f, 0xdd, 0xe7, 0xa1, 0x25, 0xbd, 0x8f, 0xc3, 0x90,
	0xeb, 0xba, 0x59, 0x81, 0x99, 0x43, 0x1c, 0x8d, 0xf2, 0x02, 0xd4, 0x1f, 0xee, 0x1e, 0xac, 0x6a,
	0x07, 0xc4, 0x01, 0xce, 0x84, 0x0a, 0x98, 0x2a, 0x5e, 0x59, 0x66, 0x39, 0x3f, 0xc9, 0x32, 0xc3,
	0x04, 0x31, 0x0e, 0x5e, 0xd7, 0x90, 0x8a, 0xfd, 0x0d, 0x6d, 0xbf, 0xfb, 0x67, 0x07, 0x2e, 0x57,
	0x53, 0x3f, 0x64, 0xb1, 0x1f, 0xe1, 0x84, 0xf8, 0x38, 0xc2, 0x3c, 0xce, 0xd0, 0xd7, 0x60, 0x45,
	0x85, 0x20, 0xa6, 0xc2, 0x8f, 0x70, 0x46, 0xb8, 0x9f, 0xb2, 0x23, 0xc2, 0x8d, 0x7c, 0x94, 0xe3,
	0xf6, 0x24, 0xea, 0x81, 0xc4, 0x48, 0x0e, 0x4e, 0x02, 0x42, 0x0f, 0x49, 0x58, 0xe1, 0xd0, 0xeb,
	0xa2, 0x1c, 0x67, 0x71, 0x5c, 0x03, 0xa4, 0x09, 0x7b, 0x14, 0x67, 0x7e, 0x30, 0xe2, 0x9c, 0x24,
	0xc2, 0x84, 0xa4, 0xad, 0x30, 0x37, 0x29, 0xce, 0x6e, 0x69, 0xb8, 0xfb, 0xb9, 0x03, 0x57, 0xab,
	0x3a, 0x2b, 0x7d, 0x59, 0x2a, 0xfc, 0x98, 0x25, 0xfe, 0x21, 0x8e, 0x68, 0x48, 0xc5, 0x09, 0xfa,
	0x0a, 0xb4, 0x8f, 0xf0, 0x21, 0x89, 0x48, 0x32, 0x10, 0x43, 0x0d, 0x36, 0x99, 0xb1, 0x54, 0xc2,
	0x1f, 0x4a, 0x70, 0xc5, 0x48, 0xa5, 0xac, 0x21, 0xbf, 0xa0, 0xc8, 0x0b, 0x23, 0x95, 0xb6, 0x9a,
	0x63, 0x1b, 0x96, 0x8d, 0x21, 0x15, 0x86, 0x9a, 0x62, 0xe8, 0x18, 0x94, 0x45, 0xbf, 0x05, 0x6d,
	0xcb, 0x44, 0x4d, 0x5c, 0xd7, 0x99, 0x51, 0x18, 0xa8, 0x28, 0xdd, 0x9f, 0xd7, 0xe0, 0xe2, 0x64,
	0xf3, 0xd0, 0x4b, 0xd0, 0x09, 0x88, 0x2c, 0x1b, 0xbf, 0x34, 0x42, 0x99, 0xd5, 0xf2, 0xda, 0x1a,
	0xf1, 0x6e, 0x01, 0x9f, 0x18, 0xbc, 0x31, 0xbb, 0x1e, 0x23, 0x78, 0xda, 0xb0, 0xc7, 0x0f, 0x5e,
	0x5d, 0x6b, 0x34, 0x1e, 0x3c, 0xf4, 0x4b, 0x07, 0x3a, 0xa1, 0x2c, 0x0f, 0x13, 0x2d, 0x95, 0x65,
	0xaa, 0x92, 0x9a, 0x3b, 0x3f, 0x9c, 0xe2, 0x8e, 0x3e, 0x96, 0xd6, 0xde, 0x62, 0x48, 0x07, 0xf7,
	0x53, 0x71, 0x8f, 0x25, 0xaf, 0x4b, 0x00, 0x5a, 0x87, 0x39, 0x85, 0xa6, 0xa1, 0x2a, 0xd8, 0x96,
	0x37, 0x2b, 0x3f, 0xef, 0x86, 0xee, 0xaf, 0x2e, 0x40, 0xf7, 0xb4, 0x28, 0x53, 0x1c, 0xaf, 0xc1,
	0xba, 0xf2, 0xa1, 0x72, 0x0a, 0xf7, 0x05, 0x89, 0x53, 0xc2, 0xb1, 0x18, 0xf1, 0xbc, 0x68, 0xd7,
	0x2c, 0xf4, 0x41, 0x89, 0x45, 0x2f, 0xc3, 0xb2, 0xcd, 0x78, 0xc8, 0x22, 0x81, 0x07, 0x24, 0x2f,
	0x11, 0x0b, 0xf5, 0x50, 0x63, 0x26, 0x46, 0xb2, 0xf6, 0xc4, 0x65, 0x58, 0x7f, 0xc2, 0x32, 0x9c,
	0x99, 0x50, 0x86, 0x1f, 0x5f, 0x80, 0xe7, 0x4e, 0x3b, 0x46, 0x0c, 0x39, 0xc9, 0x86, 0x2c, 0x0a,
	0xcb, 0x3a, 0x7c, 0x09, 0x3a, 0x96, 0x63, 0x2a, 0x85, 0xd8, 0xb6, 0x10, 0xba, 0x4e, 0xae, 0x42,
	0xcb, 0x38, 0xa3, 0x52, 0x82, 0x0b, 0x06, 0x38, 0xb9, 0x98, 0x6a, 0x67, 0x15, 0xd3, 0xc4, 0xc2,
	0xae, 0x3f, 0x69, 0x61, 0xcf, 0x4c, 0x28, 0x6c, 0xf7, 0xb3, 0x05, 0xb8, 0x74, 0x8e, 0x1b, 0x32,
	0xf4, 0x1b, 0x07, 0x16, 0xfb, 0x94, 0x58, 0x1e, 0x51, 0xc6, 0x37, 0x77, 0xde, 0x9f, 0x72, 0xba,
	0x9f, 0x0e, 0x85, 0xd7, 0x52, 0x8a, 0x3c, 0xcc, 0x23, 0xf3, 0x16, 0xb8, 0x13, 0xd2, 0x57, 0x27,
	0xb8, 0x3f, 0xa4, 0x83, 0xa1, 0x89, 0xc0, 0xc6, 0xd9, 0x99, 0xac, 0xaa, 0xe7, 0x0d, 0x3a, 0x18,
	0xa2, 0xfb, 0xf0, 0xdc, 0x24, 0x61, 0x47, 0x98, 0x27, 0x34, 0x19, 0x68, 0x71, 0x3a, 0x50, 0xcf,
	0x9e, 0x2d, 0xee, 0x5d, 0x4d, 0xa9, 0x04, 0xde, 0x83, 0xab, 0x5f, 0x24, 0x30, 0x62, 0x47, 0x26,
	0x94, 0x9b, 0xe7, 0xca, 0xdb, 0x63, 0x47, 0xe8, 0x2e, 0x3c, 0x7b, 0xbe, 0xb1, 0x52, 0x98, 0x0e,
	0xf3, 0x95, 0x73, 0x6c, 0x95, 0xa2, 0x6e, 0xc1, 0x95, 0x33, 0xaa, 0xd7, 0xf6, 0x99, 0xde, 0x43,
	0x9e, 0x39, 0x5d, 0xc8, 0xa5, 0xbf, 0xbe, 0x03, 0x9b, 0x67, 0x09, 0xa9, 0xf8, 0x6a, 0x4e, 0x89,
	0xb9, 0x7c, 0x5a, 0x8c, 0xed, 0xa7, 0x3b, 0xb0, 0x71, 0x9e, 0x20, 0x69, 0xd6, 0xbc, 0x92, 0x73,
	0x69, 0xa2, 0x1c, 0x69, 0xd4, 0xeb, 0x70, 0x79, 0xb2, 0x51, 0x52, 0x48, 0x43, 0x09, 0xb9, 0x38,
	0xc1, 0x26, 0x29, 0xe2, 0x3a, 0xac, 0x5a, 0x75, 0x69, 0xb9, 0x03, 0x14, 0x2b, 0x2a, 0x8a, 0xb3,
	0xf4, 0xc2, 0x2b, 0xb0, 0x6e, 0xb1, 0x54, 0x8c, 0x6f, 0x2a, 0xa6, 0x95, 0x82, 0xc9, 0xb6, 0xf9,
	0x06, 0xac, 0x9d, 0xc1, 0x26, 0xb5, 0x5c, 0x50, 0x5c, 0xcb, 0xe3, 0x5c, 0x52, 0xbd, 0x97, 0x61,
	0xe5, 0x94, 0x7a, 0x92, 0xa5, 0xa5, 0x58, 0x3a, 0x55, 0xed, 0x24, 0xc3, 0x1b, 0xf0, 0x2c, 0x4b,
	0x05, 0x0d, 0x70, 0xe4, 0x8f, 0xed, 0x22, 0x96, 0x6d, 0x8b, 0x3a, 0x46, 0x86, 0xf0, 0xc0, 0xde,
	0x51, 0x4a, 0x33, 0xf7, 0xe0, 0xea, 0x04, 0x49, 0x15, 0x93, 0x97, 0x94, 0xac, 0x8d, 0xb3, 0x64,
	0xd9, 0xd6, 0xbf, 0x09, 0xee, 0x17, 0x48, 0x93, 0x66, 0xb5, 0x95, 0xb0, 0x2b, 0xe7, 0x08, 0x93,
	0x36, 0xee, 0xc2, 0xe6, 0xb9, 0x36, 0x4a, 0x49, 0x1d, 0x9d, 0x3e, 0x13, 0x4d, 0x1c, 0x93, 0x53,
	0xdd, 0x3f, 0x2d, 0x57, 0xa1, 0x8a, 0x1c, 0xcf, 0xda, 0x4b, 0x4b, 0x4f, 0x59, 0xb6, 0x55, 0xe5,
	0x54, 0x1c, 0xb5, 0x5c, 0xb1, 0xcd, 0x96, 0x64, 0xfb, 0xc9, 0x8a, 0xdf, 0xd9, 0xb2, 0xa4, 0x71,
	0x2b, 0x95, 0xf8, 0x9d, 0x21, 0x4a, 0x5a, 0x77, 0x1b, 0x36, 0xce, 0xb3, 0x4e, 0xca, 0x59, 0xd5,
	0x25, 0x3f, 0xc9, 0xb8, 0x3d, 0x76, 0xe4, 0xfe, 0x73, 0x1e, 0x3a, 0xba, 0x79, 0x57, 0x7b, 0x34,
	0x11, 0x98, 0x46, 0x99, 0x9c, 0x36, 0x0e, 0x49, 0x12, 0xb2, 0xbc, 0xa7, 0x36, 0x5f, 0xf2, 0x38,
	0xd6, 0xbf, 0xfc, 0x14, 0x73, 0xe1, 0x27, 0xa3, 0xb8, 0x57, 0x74, 0xd1, 0x6d, 0x8d, 0x79, 0x80,
	0xb9, 0x78, 0x5b, 0xc1, 0xe5, 0x49, 0x67, 0xa8, 0x33, 0xc2, 0x29, 0x8e, 0x72, 0x7a, 0xd3, 0x20,
	0x68, 0xdc, 0xbe, 0x42, 0x19, 0x8e, 0x73, 0x9a, 0x17, 0xbd, 0xa7, 0x3e, 0x61, 0xf3, 0x32, 0x63,
	0x9d, 0xa9, 0x67, 0x37, 0x2f, 0xf9, 0x4a, 0xc7, 0xa6, 0x15, 0x99, 0x3d, 0xc5, 0x71, 0x70, 0x5c,
	0x34, 0x2f, 0x36, 0x07, 0xcf, 0x39, 0xe6, 0x4e, 0x71, 0x78, 0x86, 0x63, 0xbb, 0xaa, 0x94, 0x38,
	0x56, 0x55, 0xae, 0x76, 0xbe, 0x8e, 0xd7, 0xa9, 0x2c, 0x21, 0x6b, 0x1c, 0x7d, 0x08, 0x75, 0xd9,
	0xe1, 0x75, 0x1b, 0x9b, 0xb5, 0xad, 0xe6, 0xce, 0x60, 0x8a, 0x67, 0xb1, 0xdd, 0xbe, 0x7b, 0x6a,
	0x51, 0xf4, 0x07, 0x07, 0x96, 0x15, 0x78, 0xac, 0x31, 0x00, 0xd5, 0x18, 0xa4, 0x5f, 0x92, 0x32,
	0x65, 0x5f, 0xd0, 0x91, 0xe0, 0xdd, 0x4a, 0x6f, 0xf0, 0x99, 0x03, 0x97, 0x4e, 0x35, 0xea, 0x56,
	0x5f, 0xa3, 0xb6, 0xe7, 0xe6, 0x0e, 0xfd, 0xb2, 0x9a, 0x98, 0xcc, 0xeb, 0x56, 0x5b, 0xf6, 0x83,
	0xb2, 0xc5, 0xfa, 0xd4, 0x01, 0x74, 0x4a, 0xd7, 0x4c, 0x1d, 0x05, 0xcd, 0x1d, 0x32, 0x65, 0x0d,
	0xcd, 0x40, 0xb1, 0x54, 0xd5, 0x2e, 0x93, 0x6d, 0xaf, 0xda, 0x0b, 0x32, 0x7b, 0x50, 0xd3, 0x47,
	0x4d, 0x5b, 0x23, 0xac, 0x41, 0x6d, 0x03, 0x9a, 0x86, 0x58, 0x0e, 0xf3, 0xea, 0x4c, 0x69, 0x78,
	0xa0, 0x41, 0x07, 0x27, 0x29, 0x41, 0x2f, 0xc0, 0x12, 0x27, 0x87, 0x34, 0xa3, 0x2c, 0xc9, 0x2b,
	0x7b, 0x49, 0x11, 0x2d, 0xe6, 0x60, 0x5d, 0xd5, 0xee, 0xbf, 0x6a, 0xd0, 0x2e, 0x95, 0x34, 0x73,
	0xca, 0xb7, 0xe1, 0x72, 0x39, 0x0b, 0xb0, 0x2c, 0xf3, 0x59, 0xdf, 0xcf, 0xe8, 0x20, 0xc1, 0x91,
	0x19, 0xc0, 0xf4, 0xce, 0xf3, 0x7f, 0xc5, 0x50, 0xc0, 0xb2, 0xec, 0x7e, 0x7f, 0x5f, 0x51, 0xe8,
	0xf9, 0xe8, 0x5b, 0x70, 0x29, 0x0d, 0xb2, 0x82, 0xb9, 0x17, 0xb1, 0xe0, 0x91, 0xaf, 0xfe, 0x68,
	0x01, 0x7a, 0x5b, 0x5a, 0x4f, 0x83, 0x4c, 0xf3, 0xde, 0x94, 0xb8, 0x3d, 0x16, 0x3c, 0xd2, 0xec,
	0x2f, 0x42, 0x27, 0x62, 0x72, 0xf7, 0xec, 0xe3, 0x51, 0x24, 0x0c, 0x8f, 0xde, 0x9a, 0x96, 0x14,
	0x62, 0x57, 0xc2, 0x35, 0xed, 0x35, 0x40, 0x9c, 0xc4, 0x4c, 0x90, 0x0a, 0xb1, 0x1e, 0x5b, 0xda,
	0x1a, 0x63, 0x51, 0x6f, 0xc2, 0x42, 0x16, 0xfa, 0xbd, 0x7c, 0x2b, 0x36, 0xe3, 0x0a, 0x64, 0xe1,
	0x4d, 0xb3, 0xf1, 0x2a, 0x8a, 0xbe, 0x45, 0x31, 0x6b, 0x28, 0xfa, 0x05, 0xc5, 0x9b, 0xe0, 0x16,
	0x5e, 0x39, 0x49, 0x82, 0x21, 0x67, 0x09, 0xfd, 0x00, 0x0b, 0xe9, 0xeb, 0x10, 0x0b, 0x6c, 0xf8,
	0xf4, 0x5d, 0xcd, 0x95, 0x48, 0xfb, 0xa6, 0x4a, 0x77, 0x1b, 0x0b, 0x5c, 0xac, 0x36, 0xa4, 0xd6,
	0x6a, 0xf3, 0x7a, 0xb5, 0x21, 0x2d, 0x56, 0xbb, 0x0a, 0xad, 0xec, 0xfd, 0x11, 0x89, 0x82, 0xa1,
	0x21, 0x69, 0x28, 0x92, 0x05, 0x03, 0x2c, 0xc4, 0xf0, 0x63, 0x9f, 0xa5, 0xa1, 0xa1, 0x01, 0x2d,
	0x86, 0x1f, 0xdf, 0x4f, 0x43, 0x45, 0xe1, 0xc6, 0xf6, 0x5c, 0x4a, 0x38, 0x67, 0xdc, 0x0f, 0xd8,
	0x48, 0x26, 0x6a, 0x26, 0x5d, 0x28, 0x0d, 0xf1, 0x87, 0x04, 0x87, 0xc4, 0x60, 0xf5, 0x95, 0x50,
	0xdd, 0x6b, 0x4b, 0xcc, 0x1b, 0x0a, 0x71, 0x47, 0xc1, 0xa5, 0x42, 0x69, 0x90, 0xf5, 0x68, 0x9a,
	0x13, 0x5e, 0x50, 0x84, 0x0b, 0x1a, 0xa8, 0x89, 0xdc, 0x4f, 0x2e, 0x00, 0xd2, 0x67, 0x97, 0xb4,
	0x2d, 0x23, 0x42, 0xd0, 0x64, 0x90, 0xa1, 0x6f, 0x40, 0xd7, 0x24, 0x52, 0x48, 0x06, 0x1c, 0x87,
	0xa4, 0xac, 0x58, 0x73, 0x2b, 0xb1, 0xa6, 0xf1, 0xb7, 0x35, 0xba, 0xa8, 0x5a, 0xb9, 0xc5, 0x8f,
	0x71, 0x96, 0x99, 0xd4, 0xf1, 0x50, 0x85, 0x4b, 0xfb, 0x64, 0x07, 0x56, 0x0d, 0x47, 0x1f, 0xd3,
	0xc8, 0x5a, 0xa8, 0xa6, 0x7b, 0x3e, 0x8d, 0xdc, 0xc5, 0x34, 0x2a, 0x57, 0x79, 0x11, 0x3a, 0x36,
	0x4f, 0x99, 0x4b, 0x1d, 0x6f, 0xa9, 0xa4, 0xd7, 0xf2, 0xb7, 0xc1, 0x88, 0xf0, 0xed, 0xfc, 0xcb,
	0x47, 0x3f, 0x8d, 0xf2, 0xca, 0xfc, 0x73, 0xff, 0xe4, 0x28, 0x97, 0x28, 0x87, 0xc4, 0x2c, 0xa1,
	0x82, 0x71, 0x9a, 0x0c, 0xd0, 0x25, 0x68, 0x64, 0xa3, 0x34, 0x65, 0x5c, 0x14, 0x57, 0x91, 0x25,
	0x00, 0x7d, 0x08, 0xf3, 0xb9, 0xf3, 0x94, 0xa9, 0x53, 0xb8, 0xcb, 0x1d, 0x8b, 0x91, 0x57, 0x2c,
	0xe8, 0xfe, 0xdd, 0xc9, 0x83, 0x28, 0x33, 0xab, 0x08, 0xe2, 0x7b, 0x70, 0xad, 0xd8, 0x1e, 0xf2,
	0x36, 0x47, 0xb7, 0x37, 0xa7, 0x82, 0x2a, 0x99, 0x8c, 0x51, 0x2f, 0xe4, 0x3c, 0xf7, 0x35, 0x8b,
	0x3a, 0x87, 0xc7, 0xc3, 0xbc, 0x4f, 0x04, 0x7a, 0x08, 0x5b, 0x8f, 0x2b, 0xde, 0x44, 0xff, 0xb9,
	0xc7, 0x11, 0x5d, 0xf8, 0x5f, 0xda, 0xf2, 0x3f, 0xe6, 0x7f, 0xdb, 0xbd, 0x96, 0xff, 0xff, 0xe8,
	0xd8, 0x77, 0x7b, 0xa3, 0xe2, 0x06, 0xb7, 0x4f, 0x23, 0x41, 0x38, 0xfa, 0x85, 0x03, 0xab, 0xa3,
	0x84, 0x16, 0x60, 0x73, 0x97, 0x4b, 0x64, 0xe9, 0xca, 0x2e, 0xe5, 0x7b, 0x4f, 0x55, 0xd3, 0xca,
	0x6d, 0xb3, 0xb7, 0x6c, 0x16, 0xbe, 0x57, 0x5c, 0x18, 0x93, 0xcc, 0xfd, 0x77, 0x45, 0xdf, 0x78,
	0x5c, 0xdf, 0x1b, 0xb0, 0x1a, 0x8f, 0x22, 0xa1, 0x15, 0x4e, 0x39, 0x8b, 0x69, 0x16, 0x8c, 0xd8,
	0x28, 0x33, 0x95, 0xbf, 0x52, 0x20, 0x1f, 0x94, 0x38, 0xf4, 0x5b, 0x07, 0xd6, 0x4b, 0xae, 0xaa,
	0x99, 0x17, 0x94, 0x99, 0xbd, 0x29, 0x04, 0x64, 0xec, 0xb6, 0xdc, 0x2b, 0x15, 0xaf, 0x18, 0xfc,
	0x7b, 0x27, 0xef, 0xd0, 0xfb, 0x24, 0x28, 0x3a, 0x74, 0x73, 0x59, 0xef, 0x14, 0x97, 0xf5, 0x72,
	0xdb, 0x0b, 0x18, 0xe7, 0x24, 0x10, 0x24, 0xf4, 0x03, 0x16, 0x92, 0x23, 0xc6, 0x43, 0xbd, 0xff,
	0x9a, 0xdd, 0x73, 0xad, 0xc0, 0xdf, 0x32, 0xe8, 0x5b, 0x12, 0x8b, 0xbe, 0x09, 0x17, 0x47, 0xc9,
	0x44, 0xde, 0x9a, 0xe2, 0xed, 0x5a, 0x14, 0x15, 0x6e, 0xf7, 0xaf, 0x0e, 0xac, 0x99, 0x09, 0xa2,
	0x5f, 0xe8, 0xa7, 0x9f, 0x0b, 0xae, 0xc3, 0x4a, 0xca, 0x29, 0xe3, 0x54, 0x9c, 0xf8, 0xf6, 0x2b,
	0x85, 0xd6, 0x7a, 0x39, 0xc7, 0xed, 0x5a, 0xaf, 0x15, 0xaf, 0xc2, 0x7a, 0xc1, 0x62, 0xde, 0x4e,
	0xfc, 0x1e, 0x15, 0x31, 0x4e, 0xcd, 0x23, 0xc9, 0x6a, 0x8e, 0x36, 0x6f, 0x28, 0x37, 0x15, 0x12,
	0x3d, 0x03, 0x0d, 0x7e, 0xec, 0xf7, 0x39, 0x8e, 0x49, 0xd6, 0xad, 0x6d, 0xd6, 0xb6, 0xea, 0xde,
	0x3c, 0x3f, 0xde, 0x55, 0xdf, 0x12, 0x29, 0x0a, 0x64, 0x5d, 0x23, 0x85, 0x41, 0xba, 0x6f, 0xc2,
	0x1a, 0x39, 0x16, 0x24, 0x09, 0x55, 0x23, 0xc2, 0xd2, 0x1e, 0x0e, 0x1e, 0x15, 0xaf, 0x1d, 0x11,
	0x39, 0x24, 0x91, 0xc9, 0x1d, 0xfd, 0x81, 0x2e, 0xc2, 0x7c, 0x4e, 0x66, 0x5a, 0x8c, 0xe2, 0xdb,
	0xfd, 0x71, 0x5d, 0x97, 0x7f, 0xf5, 0xd9, 0x0e, 0x5d, 0x06, 0xd0, 0x99, 0xa2, 0x3a, 0x29, 0x6d,
	0x7d, 0x43, 0x41, 0x0e, 0xcc, 0x6b, 0xa4, 0x24, 0x4d, 0x39, 0xc9, 0x88, 0x09, 0x56, 0xc3, 0x83,
	0x74, 0x78, 0xf2, 0x40, 0x43, 0xd0, 0x47, 0x9a, 0xc0, 0xf8, 0x56, 0x45, 0x64, 0x0a, 0xaf, 0x7d,
	0xd5, 0x19, 0x50, 0x29, 0x70, 0xdb, 0x64, 0x9b, 0x6d, 0x73, 0xbd, 0x6a, 0xb3, 0x54, 0xce, 0x4a,
	0x4c, 0x73, 0x6f, 0x3e, 0x0d, 0xe5, 0xac, 0x55, 0x3c, 0xe8, 0x93, 0x20, 0x57, 0xee, 0x13, 0x59,
	0x20, 0xe3, 0x11, 0xec, 0xce, 0xaa, 0xba, 0x0d, 0x9e, 0xae, 0x1e, 0x67, 0xe6, 0x89, 0xd7, 0xce,
	0xe1, 0x7b, 0x79, 0x1e, 0x7c, 0xde, 0x50, 0x35, 0x5b, 0x7d, 0x3f, 0x95, 0x69, 0x10, 0xd1, 0xe4,
	0x91, 0x79, 0x74, 0x36, 0x69, 0x20, 0x21, 0xfa, 0xcd, 0xf9, 0x19, 0x68, 0xc8, 0x6c, 0xd7, 0xd8,
	0x3c, 0xb3, 0x48, 0xa8, 0x91, 0x23, 0x98, 0x33, 0x6f, 0x87, 0x26, 0xfc, 0xdf, 0x9f, 0x82, 0x87,
	0xf3, 0x47, 0x4b, 0x2f, 0x5f, 0xab, 0x7c, 0x8c, 0xac, 0x9f, 0xfd, 0x18, 0x39, 0x73, 0xde, 0x63,
	0xe4, 0xec, 0xe9, 0xc7, 0xc8, 0x36, 0xd4, 0x68, 0x3a, 0xc8, 0xdf, 0x18, 0x69, 0x3a, 0x40, 0x1f,
	0x3b, 0xb0, 0x68, 0xee, 0xf5, 0xf3, 0x21, 0x69, 0x5e, 0x19, 0xf8, 0xde, 0x94, 0x86, 0x24, 0x33,
	0x1c, 0xb5, 0xcc, 0xa2, 0x66, 0x34, 0xfa, 0x89, 0x03, 0x4b, 0xa9, 0x9c, 0x5b, 0xd8, 0x28, 0xcb,
	0xf5, 0x68, 0x7c, 0x19, 0x7a, 0x2c, 0xe6, 0xab, 0x1a, 0x45, 0x7e, 0xea, 0xc0, 0x82, 0xd5, 0x3a,
	0x67, 0x66, 0x00, 0x9f, 0xd6, 0xc8, 0x58, 0xed, 0xd2, 0xbd, 0xa6, 0xfa, 0x56, 0x1b, 0xbb, 0xf2,
	0xc9, 0x62, 0xb5, 0x91, 0x34, 0x13, 0xf6, 0xd3, 0x7f, 0xea, 0xaf, 0x2e, 0xe3, 0xb5, 0x7a, 0x84,
	0xdf, 0x2b, 0xdb, 0x27, 0xa9, 0x48, 0xb5, 0xa3, 0x32, 0x83, 0xf4, 0xd3, 0x57, 0xa4, 0xba, 0x8c,
	0xd7, 0x62, 0x69, 0x68, 0x29, 0xb2, 0x93, 0xdf, 0x26, 0xe7, 0xd3, 0x52, 0xfe, 0xbc, 0xdf, 0xb2,
	0xae, 0x78, 0xf7, 0x35, 0x2e, 0x7f, 0xe3, 0xbf, 0x01, 0xab, 0x3d, 0x9c, 0x84, 0x47, 0x34, 0x14,
	0x43, 0x7f, 0x24, 0x68, 0x64, 0xe6, 0x33, 0x73, 0x4b, 0xbb, 0x52, 0x20, 0xdf, 0x29, 0x71, 0xe8,
	0x47, 0x30, 0x2f, 0x4f, 0x53, 0xf5, 0xbf, 0x0d, 0x4b, 0xca, 0xd4, 0x60, 0x1a, 0xdb, 0xfd, 0xd8,
	0x81, 0xed, 0xcd, 0xa5, 0x7d, 0xfd, 0x2f, 0x16, 0x97, 0xa0, 0x51, 0xe8, 0xa5, 0x6e, 0x6d, 0xeb,
	0x5e, 0x09, 0x70, 0xff, 0x52, 0x39, 0xe6, 0xf2, 0x7f, 0xd0, 0x90, 0xc5, 0x1d, 0x8b, 0x91, 0x39,
	0x2d, 0xe5, 0x4f, 0x05, 0xe1, 0x23, 0x73, 0x72, 0xcb, 0x9f, 0xe8, 0x3a, 0xac, 0xf6, 0x46, 0x3c,
	0x21, 0xa1, 0x4f, 0x13, 0xbb, 0xd3, 0xca, 0x2f, 0x05, 0x35, 0xf2, 0x6e, 0x52, 0xb6, 0x40, 0xe8,
	0x53, 0x07, 0xd6, 0x99, 0xba, 0xe9, 0xa3, 0x4c, 0x4e, 0x42, 0x36, 0x57, 0x5d, 0xf9, 0x66, 0x9a,
	0x4d, 0xe8, 0xaa, 0xb5, 0xb4, 0xa5, 0xd4, 0xaf, 0x1d, 0x58, 0xb6, 0xfb, 0x62, 0xdd, 0x7e, 0xe6,
	0xc7, 0xdf, 0xb4, 0xee, 0xee, 0xc6, 0xdb, 0x73, 0xaf, 0x53, 0xb6, 0xc8, 0xbb, 0x5a, 0x03, 0xf4,
	0x3b, 0xc7, 0x6e, 0x81, 0x6d, 0xdd, 0x66, 0xa7, 0xaa, 0xdb, 0x78, 0x2b, 0xee, 0x2d, 0xdb, 0xfd,
	0xac, 0xd1, 0xce, 0xfd, 0x9b, 0x03, 0xeb, 0x13, 0xfe, 0xb1, 0x46, 0x76, 0xb0, 0x31, 0x96, 0xa2,
	0x13, 0x9c, 0x04, 0xc4, 0x8f, 0x59, 0x48, 0x2a, 0xff, 0x3f, 0xd3, 0xf2, 0xd6, 0x2c, 0xfc, 0x3d,
	0x16, 0x92, 0xbc, 0xc6, 0x36, 0xa0, 0x89, 0x69, 0x92, 0xa9, 0xb3, 0x73, 0x94, 0xe5, 0x1d, 0x94,
	0x04, 0xed, 0x2b, 0x08, 0x7a, 0x1e, 0x16, 0x05, 0x13, 0x72, 0xb0, 0x1f, 0xe9, 0x60, 0x9a, 0x01,
	0xbd, 0xa5, 0xa0, 0xb7, 0x0d, 0x10, 0x7d, 0x55, 0xdd, 0xf3, 0x60, 0xaa, 0x6e, 0xe2, 0x0b, 0x52,
	0xfd, 0x8f, 0x03, 0x9d, 0x02, 0x93, 0x93, 0xf7, 0x66, 0xd5, 0xff, 0xc6, 0xdd, 0xf8, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x80, 0xab, 0x20, 0xb7, 0x4b, 0x27, 0x00, 0x00,
}
