// Code generated by protoc-gen-go.
// source: bgp_config_relatives_bag.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_bgp_oper_bgp_config_instances_config_instance_config_vrfs_config_vrf_configuration_users_configuration_user is a generated protocol buffer package.

It is generated from these files:
	bgp_config_relatives_bag.proto

It has these top-level messages:
	BgpConfigRelativesBag_KEYS
	BgpConfigRelativesBag
	IPV4TunnelAddressType
	IPV4MDTAddressType
	RTConstraintAddressType
	IPV6AddressType
	BgpIpv4SrpolicyAddrT
	BgpIpv6SrpolicyAddrT
	BgpL2VpnAddrT
	L2VPNEVPNAddressType
	BgpL2VpnMspwAddrT
	IPV6MVPNAddressType
	IPV4MVPNAddressType
	LS_LSAddressType
	IPv4FlowspecAddressType
	IPv6FlowspecAddressType
	BgpAddrtype
	BgpConfigEntid_
	BgpConfigEntid_Item
	BgpConfigEntp
*/
package cisco_ios_xr_ipv4_bgp_oper_bgp_config_instances_config_instance_config_vrfs_config_vrf_configuration_users_configuration_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BGP config ancestors/children information
type BgpConfigRelativesBag_KEYS struct {
	InstanceName    string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
	VrfName         string `protobuf:"bytes,2,opt,name=vrf_name,json=vrfName" json:"vrf_name,omitempty"`
	EntityType      string `protobuf:"bytes,3,opt,name=entity_type,json=entityType" json:"entity_type,omitempty"`
	NeighborAddress string `protobuf:"bytes,4,opt,name=neighbor_address,json=neighborAddress" json:"neighbor_address,omitempty"`
	EntityName      string `protobuf:"bytes,5,opt,name=entity_name,json=entityName" json:"entity_name,omitempty"`
}

func (m *BgpConfigRelativesBag_KEYS) Reset()                    { *m = BgpConfigRelativesBag_KEYS{} }
func (m *BgpConfigRelativesBag_KEYS) String() string            { return proto.CompactTextString(m) }
func (*BgpConfigRelativesBag_KEYS) ProtoMessage()               {}
func (*BgpConfigRelativesBag_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BgpConfigRelativesBag_KEYS) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *BgpConfigRelativesBag_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *BgpConfigRelativesBag_KEYS) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *BgpConfigRelativesBag_KEYS) GetNeighborAddress() string {
	if m != nil {
		return m.NeighborAddress
	}
	return ""
}

func (m *BgpConfigRelativesBag_KEYS) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

type BgpConfigRelativesBag struct {
	// Neighbor Address
	NeighborAddress *BgpAddrtype `protobuf:"bytes,50,opt,name=neighbor_address,json=neighborAddress" json:"neighbor_address,omitempty"`
	// Entity/group name
	GroupName string `protobuf:"bytes,51,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
	// Entity type
	ConfigurationType string `protobuf:"bytes,52,opt,name=configuration_type,json=configurationType" json:"configuration_type,omitempty"`
	// AF identifier
	AddressFamilyIdentifier uint32 `protobuf:"varint,53,opt,name=address_family_identifier,json=addressFamilyIdentifier" json:"address_family_identifier,omitempty"`
	// AF-independent relatives
	AfIndependentRelatives *BgpConfigEntid_ `protobuf:"bytes,54,opt,name=af_independent_relatives,json=afIndependentRelatives" json:"af_independent_relatives,omitempty"`
	// AF-dependent relatives
	AfDependentRelatives []*BgpConfigEntp `protobuf:"bytes,55,rep,name=af_dependent_relatives,json=afDependentRelatives" json:"af_dependent_relatives,omitempty"`
}

func (m *BgpConfigRelativesBag) Reset()                    { *m = BgpConfigRelativesBag{} }
func (m *BgpConfigRelativesBag) String() string            { return proto.CompactTextString(m) }
func (*BgpConfigRelativesBag) ProtoMessage()               {}
func (*BgpConfigRelativesBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BgpConfigRelativesBag) GetNeighborAddress() *BgpAddrtype {
	if m != nil {
		return m.NeighborAddress
	}
	return nil
}

func (m *BgpConfigRelativesBag) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *BgpConfigRelativesBag) GetConfigurationType() string {
	if m != nil {
		return m.ConfigurationType
	}
	return ""
}

func (m *BgpConfigRelativesBag) GetAddressFamilyIdentifier() uint32 {
	if m != nil {
		return m.AddressFamilyIdentifier
	}
	return 0
}

func (m *BgpConfigRelativesBag) GetAfIndependentRelatives() *BgpConfigEntid_ {
	if m != nil {
		return m.AfIndependentRelatives
	}
	return nil
}

func (m *BgpConfigRelativesBag) GetAfDependentRelatives() []*BgpConfigEntp {
	if m != nil {
		return m.AfDependentRelatives
	}
	return nil
}

// IPV4Tunnel Address type
type IPV4TunnelAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4TunnelAddressType) Reset()                    { *m = IPV4TunnelAddressType{} }
func (m *IPV4TunnelAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4TunnelAddressType) ProtoMessage()               {}
func (*IPV4TunnelAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IPV4TunnelAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4MDT Address type
type IPV4MDTAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4MDTAddressType) Reset()                    { *m = IPV4MDTAddressType{} }
func (m *IPV4MDTAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4MDTAddressType) ProtoMessage()               {}
func (*IPV4MDTAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IPV4MDTAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4 RTConstraint Address type
type RTConstraintAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *RTConstraintAddressType) Reset()                    { *m = RTConstraintAddressType{} }
func (m *RTConstraintAddressType) String() string            { return proto.CompactTextString(m) }
func (*RTConstraintAddressType) ProtoMessage()               {}
func (*RTConstraintAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RTConstraintAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV6 Address type
type IPV6AddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV6AddressType) Reset()                    { *m = IPV6AddressType{} }
func (m *IPV6AddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV6AddressType) ProtoMessage()               {}
func (*IPV6AddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IPV6AddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpIpv4SrpolicyAddrT struct {
	Ipv4SrpolicyAddress []byte `protobuf:"bytes,1,opt,name=ipv4_srpolicy_address,json=ipv4SrpolicyAddress,proto3" json:"ipv4_srpolicy_address,omitempty"`
}

func (m *BgpIpv4SrpolicyAddrT) Reset()                    { *m = BgpIpv4SrpolicyAddrT{} }
func (m *BgpIpv4SrpolicyAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpIpv4SrpolicyAddrT) ProtoMessage()               {}
func (*BgpIpv4SrpolicyAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BgpIpv4SrpolicyAddrT) GetIpv4SrpolicyAddress() []byte {
	if m != nil {
		return m.Ipv4SrpolicyAddress
	}
	return nil
}

type BgpIpv6SrpolicyAddrT struct {
	Ipv6SrpolicyAddress []byte `protobuf:"bytes,1,opt,name=ipv6_srpolicy_address,json=ipv6SrpolicyAddress,proto3" json:"ipv6_srpolicy_address,omitempty"`
}

func (m *BgpIpv6SrpolicyAddrT) Reset()                    { *m = BgpIpv6SrpolicyAddrT{} }
func (m *BgpIpv6SrpolicyAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpIpv6SrpolicyAddrT) ProtoMessage()               {}
func (*BgpIpv6SrpolicyAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BgpIpv6SrpolicyAddrT) GetIpv6SrpolicyAddress() []byte {
	if m != nil {
		return m.Ipv6SrpolicyAddress
	}
	return nil
}

type BgpL2VpnAddrT struct {
	L2VpnAddress []byte `protobuf:"bytes,1,opt,name=l2vpn_address,json=l2vpnAddress,proto3" json:"l2vpn_address,omitempty"`
}

func (m *BgpL2VpnAddrT) Reset()                    { *m = BgpL2VpnAddrT{} }
func (m *BgpL2VpnAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpL2VpnAddrT) ProtoMessage()               {}
func (*BgpL2VpnAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BgpL2VpnAddrT) GetL2VpnAddress() []byte {
	if m != nil {
		return m.L2VpnAddress
	}
	return nil
}

// L2VPN EVPN Address type
type L2VPNEVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *L2VPNEVPNAddressType) Reset()                    { *m = L2VPNEVPNAddressType{} }
func (m *L2VPNEVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*L2VPNEVPNAddressType) ProtoMessage()               {}
func (*L2VPNEVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *L2VPNEVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpL2VpnMspwAddrT struct {
	L2VpnAddress []byte `protobuf:"bytes,1,opt,name=l2vpn_address,json=l2vpnAddress,proto3" json:"l2vpn_address,omitempty"`
}

func (m *BgpL2VpnMspwAddrT) Reset()                    { *m = BgpL2VpnMspwAddrT{} }
func (m *BgpL2VpnMspwAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpL2VpnMspwAddrT) ProtoMessage()               {}
func (*BgpL2VpnMspwAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BgpL2VpnMspwAddrT) GetL2VpnAddress() []byte {
	if m != nil {
		return m.L2VpnAddress
	}
	return nil
}

// IPV6 MVPN Address type
type IPV6MVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV6MVPNAddressType) Reset()                    { *m = IPV6MVPNAddressType{} }
func (m *IPV6MVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV6MVPNAddressType) ProtoMessage()               {}
func (*IPV6MVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IPV6MVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4 MVPN Address type
type IPV4MVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4MVPNAddressType) Reset()                    { *m = IPV4MVPNAddressType{} }
func (m *IPV4MVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4MVPNAddressType) ProtoMessage()               {}
func (*IPV4MVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IPV4MVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// LINKSTATE LINKSTATE Address type
type LS_LSAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *LS_LSAddressType) Reset()                    { *m = LS_LSAddressType{} }
func (m *LS_LSAddressType) String() string            { return proto.CompactTextString(m) }
func (*LS_LSAddressType) ProtoMessage()               {}
func (*LS_LSAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LS_LSAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPv4 Flowspec Address type
type IPv4FlowspecAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPv4FlowspecAddressType) Reset()                    { *m = IPv4FlowspecAddressType{} }
func (m *IPv4FlowspecAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPv4FlowspecAddressType) ProtoMessage()               {}
func (*IPv4FlowspecAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IPv4FlowspecAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPv6 Flowspec Address type
type IPv6FlowspecAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPv6FlowspecAddressType) Reset()                    { *m = IPv6FlowspecAddressType{} }
func (m *IPv6FlowspecAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPv6FlowspecAddressType) ProtoMessage()               {}
func (*IPv6FlowspecAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IPv6FlowspecAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpAddrtype struct {
	Afi string `protobuf:"bytes,1,opt,name=afi" json:"afi,omitempty"`
	// IPv4 Addr
	Ipv4Address string `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address" json:"ipv4_address,omitempty"`
	// IPv4 Mcast Addr
	Ipv4McastAddress string `protobuf:"bytes,3,opt,name=ipv4_mcast_address,json=ipv4McastAddress" json:"ipv4_mcast_address,omitempty"`
	// IPv4 Label Addr
	Ipv4LabelAddress string `protobuf:"bytes,4,opt,name=ipv4_label_address,json=ipv4LabelAddress" json:"ipv4_label_address,omitempty"`
	// IPv4 Tunnel
	Ipv4TunnelAddress *IPV4TunnelAddressType `protobuf:"bytes,5,opt,name=ipv4_tunnel_address,json=ipv4TunnelAddress" json:"ipv4_tunnel_address,omitempty"`
	// IPv4 MDT Addr
	Ipv4MdtAddress *IPV4MDTAddressType `protobuf:"bytes,6,opt,name=ipv4_mdt_address,json=ipv4MdtAddress" json:"ipv4_mdt_address,omitempty"`
	// IPv4 VPN Addr
	Ipv4VpnAddress string `protobuf:"bytes,7,opt,name=ipv4_vpn_address,json=ipv4VpnAddress" json:"ipv4_vpn_address,omitempty"`
	// IPv4 VPN Mcast Addr
	Ipv4VpnaMcastddress string `protobuf:"bytes,8,opt,name=ipv4_vpna_mcastddress,json=ipv4VpnaMcastddress" json:"ipv4_vpna_mcastddress,omitempty"`
	// IPV6 Addr
	Ipv6Address *IPV6AddressType `protobuf:"bytes,9,opt,name=ipv6_address,json=ipv6Address" json:"ipv6_address,omitempty"`
	// IPV6 Mcast Addr
	Ipv6McastAddress *IPV6AddressType `protobuf:"bytes,10,opt,name=ipv6_mcast_address,json=ipv6McastAddress" json:"ipv6_mcast_address,omitempty"`
	// IPv6 Label Addr
	Ipv6LabelAddress *IPV6AddressType `protobuf:"bytes,11,opt,name=ipv6_label_address,json=ipv6LabelAddress" json:"ipv6_label_address,omitempty"`
	// IPv6 VPN Addr
	Ipv6VpnAddress *IPV6AddressType `protobuf:"bytes,12,opt,name=ipv6_vpn_address,json=ipv6VpnAddress" json:"ipv6_vpn_address,omitempty"`
	// IPv6 VPN Mcast Addr
	Ipv6VpnMcastAddress *IPV6AddressType `protobuf:"bytes,13,opt,name=ipv6_vpn_mcast_address,json=ipv6VpnMcastAddress" json:"ipv6_vpn_mcast_address,omitempty"`
	// L2VPN VPLS Addr
	L2VpnvplsAddress *BgpL2VpnAddrT `protobuf:"bytes,14,opt,name=l2_vpnvpls_address,json=l2VpnvplsAddress" json:"l2_vpnvpls_address,omitempty"`
	// RT Constrt Addr
	RtConstraintAddress *RTConstraintAddressType `protobuf:"bytes,15,opt,name=rt_constraint_address,json=rtConstraintAddress" json:"rt_constraint_address,omitempty"`
	// MVPN addr
	Ipv6MvpnAddress *IPV6MVPNAddressType `protobuf:"bytes,16,opt,name=ipv6_mvpn_address,json=ipv6MvpnAddress" json:"ipv6_mvpn_address,omitempty"`
	// MVPN4 addr
	Ipv4MvpnAddress *IPV4MVPNAddressType `protobuf:"bytes,17,opt,name=ipv4_mvpn_address,json=ipv4MvpnAddress" json:"ipv4_mvpn_address,omitempty"`
	// L2VPN EVPN Addr
	L2VpnEvpnAddress *L2VPNEVPNAddressType `protobuf:"bytes,18,opt,name=l2_vpn_evpn_address,json=l2VpnEvpnAddress" json:"l2_vpn_evpn_address,omitempty"`
	// LINKSTATE LINKSTATE Addr
	LsLsAddress *LS_LSAddressType `protobuf:"bytes,19,opt,name=ls_ls_address,json=lsLsAddress" json:"ls_ls_address,omitempty"`
	// L2VPN MSPW Addr
	L2VpnMspwAddress *BgpL2VpnMspwAddrT `protobuf:"bytes,20,opt,name=l2_vpn_mspw_address,json=l2VpnMspwAddress" json:"l2_vpn_mspw_address,omitempty"`
	// IPV4 Flowspec Addr
	Ipv4FlowspecAddress *IPv4FlowspecAddressType `protobuf:"bytes,21,opt,name=ipv4_flowspec_address,json=ipv4FlowspecAddress" json:"ipv4_flowspec_address,omitempty"`
	// IPV6 Flowspec Addr
	Ipv6FlowspecAddress *IPv6FlowspecAddressType `protobuf:"bytes,22,opt,name=ipv6_flowspec_address,json=ipv6FlowspecAddress" json:"ipv6_flowspec_address,omitempty"`
	// IPV4 VPN Flowspec Addr
	Ipv4VpnFlowspecAddress *IPv4FlowspecAddressType `protobuf:"bytes,23,opt,name=ipv4_vpn_flowspec_address,json=ipv4VpnFlowspecAddress" json:"ipv4_vpn_flowspec_address,omitempty"`
	// IPV6 VPN Flowspec Addr
	Ipv6VpnFlowspecAddress *IPv6FlowspecAddressType `protobuf:"bytes,24,opt,name=ipv6_vpn_flowspec_address,json=ipv6VpnFlowspecAddress" json:"ipv6_vpn_flowspec_address,omitempty"`
	// IPV4 Policy Addr
	Ipv4SrPolicyAddress *BgpIpv4SrpolicyAddrT `protobuf:"bytes,25,opt,name=ipv4_sr_policy_address,json=ipv4SrPolicyAddress" json:"ipv4_sr_policy_address,omitempty"`
	// IPV6 Policy Addr
	Ipv6SrPolicyAddress *BgpIpv6SrpolicyAddrT `protobuf:"bytes,26,opt,name=ipv6_sr_policy_address,json=ipv6SrPolicyAddress" json:"ipv6_sr_policy_address,omitempty"`
}

func (m *BgpAddrtype) Reset()                    { *m = BgpAddrtype{} }
func (m *BgpAddrtype) String() string            { return proto.CompactTextString(m) }
func (*BgpAddrtype) ProtoMessage()               {}
func (*BgpAddrtype) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *BgpAddrtype) GetAfi() string {
	if m != nil {
		return m.Afi
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4McastAddress() string {
	if m != nil {
		return m.Ipv4McastAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4LabelAddress() string {
	if m != nil {
		return m.Ipv4LabelAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4TunnelAddress() *IPV4TunnelAddressType {
	if m != nil {
		return m.Ipv4TunnelAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4MdtAddress() *IPV4MDTAddressType {
	if m != nil {
		return m.Ipv4MdtAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4VpnAddress() string {
	if m != nil {
		return m.Ipv4VpnAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4VpnaMcastddress() string {
	if m != nil {
		return m.Ipv4VpnaMcastddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv6Address() *IPV6AddressType {
	if m != nil {
		return m.Ipv6Address
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6McastAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6McastAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6LabelAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6LabelAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6VpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnMcastAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6VpnMcastAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnvplsAddress() *BgpL2VpnAddrT {
	if m != nil {
		return m.L2VpnvplsAddress
	}
	return nil
}

func (m *BgpAddrtype) GetRtConstraintAddress() *RTConstraintAddressType {
	if m != nil {
		return m.RtConstraintAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6MvpnAddress() *IPV6MVPNAddressType {
	if m != nil {
		return m.Ipv6MvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4MvpnAddress() *IPV4MVPNAddressType {
	if m != nil {
		return m.Ipv4MvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnEvpnAddress() *L2VPNEVPNAddressType {
	if m != nil {
		return m.L2VpnEvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetLsLsAddress() *LS_LSAddressType {
	if m != nil {
		return m.LsLsAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnMspwAddress() *BgpL2VpnMspwAddrT {
	if m != nil {
		return m.L2VpnMspwAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4FlowspecAddress() *IPv4FlowspecAddressType {
	if m != nil {
		return m.Ipv4FlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6FlowspecAddress() *IPv6FlowspecAddressType {
	if m != nil {
		return m.Ipv6FlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4VpnFlowspecAddress() *IPv4FlowspecAddressType {
	if m != nil {
		return m.Ipv4VpnFlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnFlowspecAddress() *IPv6FlowspecAddressType {
	if m != nil {
		return m.Ipv6VpnFlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4SrPolicyAddress() *BgpIpv4SrpolicyAddrT {
	if m != nil {
		return m.Ipv4SrPolicyAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6SrPolicyAddress() *BgpIpv6SrpolicyAddrT {
	if m != nil {
		return m.Ipv6SrPolicyAddress
	}
	return nil
}

type BgpConfigEntid_ struct {
	// Next entry in the list
	BgpConfigEntid_ []*BgpConfigEntid_Item `protobuf:"bytes,1,rep,name=bgp_config_entid_,json=bgpConfigEntid" json:"bgp_config_entid_,omitempty"`
}

func (m *BgpConfigEntid_) Reset()                    { *m = BgpConfigEntid_{} }
func (m *BgpConfigEntid_) String() string            { return proto.CompactTextString(m) }
func (*BgpConfigEntid_) ProtoMessage()               {}
func (*BgpConfigEntid_) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *BgpConfigEntid_) GetBgpConfigEntid_() []*BgpConfigEntid_Item {
	if m != nil {
		return m.BgpConfigEntid_
	}
	return nil
}

type BgpConfigEntid_Item struct {
	// Address family identfier
	AddressFamilyIdentifier uint32 `protobuf:"varint,1,opt,name=address_family_identifier,json=addressFamilyIdentifier" json:"address_family_identifier,omitempty"`
	// Entity type
	ConfigurationType string `protobuf:"bytes,2,opt,name=configuration_type,json=configurationType" json:"configuration_type,omitempty"`
	// Neighbor Address
	NeighborAddress *BgpAddrtype `protobuf:"bytes,3,opt,name=neighbor_address,json=neighborAddress" json:"neighbor_address,omitempty"`
	// Group name
	GroupName string `protobuf:"bytes,4,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
}

func (m *BgpConfigEntid_Item) Reset()                    { *m = BgpConfigEntid_Item{} }
func (m *BgpConfigEntid_Item) String() string            { return proto.CompactTextString(m) }
func (*BgpConfigEntid_Item) ProtoMessage()               {}
func (*BgpConfigEntid_Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *BgpConfigEntid_Item) GetAddressFamilyIdentifier() uint32 {
	if m != nil {
		return m.AddressFamilyIdentifier
	}
	return 0
}

func (m *BgpConfigEntid_Item) GetConfigurationType() string {
	if m != nil {
		return m.ConfigurationType
	}
	return ""
}

func (m *BgpConfigEntid_Item) GetNeighborAddress() *BgpAddrtype {
	if m != nil {
		return m.NeighborAddress
	}
	return nil
}

func (m *BgpConfigEntid_Item) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type BgpConfigEntp struct {
	Value *BgpConfigEntid_ `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *BgpConfigEntp) Reset()                    { *m = BgpConfigEntp{} }
func (m *BgpConfigEntp) String() string            { return proto.CompactTextString(m) }
func (*BgpConfigEntp) ProtoMessage()               {}
func (*BgpConfigEntp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *BgpConfigEntp) GetValue() *BgpConfigEntid_ {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*BgpConfigRelativesBag_KEYS)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_config_relatives_bag_KEYS")
	proto.RegisterType((*BgpConfigRelativesBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_config_relatives_bag")
	proto.RegisterType((*IPV4TunnelAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.IPV4TunnelAddressType")
	proto.RegisterType((*IPV4MDTAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.IPV4MDTAddressType")
	proto.RegisterType((*RTConstraintAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.RTConstraintAddressType")
	proto.RegisterType((*IPV6AddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.IPV6AddressType")
	proto.RegisterType((*BgpIpv4SrpolicyAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_ipv4_srpolicy_addr_t")
	proto.RegisterType((*BgpIpv6SrpolicyAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_ipv6_srpolicy_addr_t")
	proto.RegisterType((*BgpL2VpnAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_l2vpn_addr_t")
	proto.RegisterType((*L2VPNEVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.L2VPNEVPNAddressType")
	proto.RegisterType((*BgpL2VpnMspwAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_l2vpn_mspw_addr_t")
	proto.RegisterType((*IPV6MVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.IPV6MVPNAddressType")
	proto.RegisterType((*IPV4MVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.IPV4MVPNAddressType")
	proto.RegisterType((*LS_LSAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.LS_LSAddressType")
	proto.RegisterType((*IPv4FlowspecAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.IPv4FlowspecAddressType")
	proto.RegisterType((*IPv6FlowspecAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.IPv6FlowspecAddressType")
	proto.RegisterType((*BgpAddrtype)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_addrtype")
	proto.RegisterType((*BgpConfigEntid_)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_config_entid_")
	proto.RegisterType((*BgpConfigEntid_Item)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_config_entid__item")
	proto.RegisterType((*BgpConfigEntp)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.config_instances.config_instance.config_vrfs.config_vrf.configuration_users.configuration_user.bgp_config_entp")
}

func init() { proto.RegisterFile("bgp_config_relatives_bag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xd7, 0xb4, 0xdb, 0xdd, 0xed, 0x4b, 0xda, 0xa6, 0x93, 0x36, 0x4d, 0x91, 0x16, 0x4a, 0xf6,
	0x40, 0x80, 0xdd, 0x22, 0x65, 0x83, 0x57, 0x42, 0x5c, 0xd0, 0x6e, 0x57, 0xaa, 0x68, 0xab, 0xc8,
	0xad, 0x22, 0x71, 0x1a, 0x39, 0xc9, 0x38, 0x58, 0x72, 0x6c, 0xcb, 0xe3, 0xa6, 0xf4, 0xc0, 0x27,
	0x40, 0x5a, 0xfe, 0xc3, 0x47, 0xe0, 0x8e, 0x90, 0x10, 0xe2, 0x9f, 0x10, 0xec, 0x69, 0xe1, 0xc2,
	0x85, 0x0b, 0x1f, 0x83, 0x0b, 0x37, 0x34, 0xcf, 0x7f, 0x62, 0x3b, 0x4e, 0x1b, 0x4e, 0x9d, 0xbd,
	0xd9, 0xef, 0xfd, 0x66, 0xe6, 0xfd, 0xde, 0xbc, 0xf7, 0xfc, 0xf2, 0x02, 0xcf, 0xf7, 0x86, 0x1e,
	0xeb, 0xbb, 0x8e, 0x69, 0x0d, 0x99, 0xcf, 0x6d, 0x23, 0xb0, 0xc6, 0x5c, 0xb0, 0x9e, 0x31, 0xdc,
	0xf5, 0x7c, 0x37, 0x70, 0xe9, 0xfb, 0x7d, 0x4b, 0xf4, 0x5d, 0x66, 0xb9, 0x82, 0xbd, 0xe7, 0x33,
	0xcb, 0x1b, 0xb7, 0x99, 0x5c, 0xe1, 0x7a, 0xdc, 0xdf, 0xed, 0x0d, 0xbd, 0xdd, 0x68, 0xa9, 0xe5,
	0x88, 0xc0, 0x70, 0xfa, 0x5c, 0xe4, 0x05, 0xf1, 0xfb, 0xd8, 0x37, 0x45, 0xea, 0x39, 0x7a, 0x3c,
	0xf5, 0x8d, 0xc0, 0x72, 0x1d, 0x76, 0x2a, 0xb8, 0x2f, 0x0a, 0x64, 0x8d, 0xdf, 0x09, 0xdc, 0x9a,
	0x65, 0x21, 0x7b, 0x7b, 0xef, 0x9d, 0x63, 0x7a, 0x1b, 0x56, 0xe2, 0xb3, 0x98, 0x63, 0x8c, 0x78,
	0x9d, 0xec, 0x90, 0xe6, 0xb2, 0x5e, 0x8e, 0x85, 0x47, 0xc6, 0x88, 0xd3, 0x6d, 0xb8, 0x39, 0xf6,
	0xcd, 0x50, 0xbf, 0x80, 0xfa, 0x1b, 0x63, 0xdf, 0x44, 0xd5, 0x0b, 0x50, 0xe2, 0x4e, 0x60, 0x05,
	0xe7, 0x2c, 0x38, 0xf7, 0x78, 0x7d, 0x11, 0xb5, 0x10, 0x8a, 0x4e, 0xce, 0x3d, 0x4e, 0x5f, 0x86,
	0x8a, 0xc3, 0xad, 0xe1, 0xbb, 0x3d, 0xd7, 0x67, 0xc6, 0x60, 0xe0, 0x73, 0x21, 0xea, 0xd7, 0x10,
	0xb5, 0x16, 0xcb, 0xdf, 0x0a, 0xc5, 0xa9, 0xbd, 0xf0, 0xa4, 0xa5, 0xf4, 0x5e, 0xf2, 0xb0, 0xc6,
	0x3f, 0x4b, 0x50, 0x9f, 0x45, 0x87, 0x7e, 0x4b, 0x0a, 0x4e, 0x6a, 0xed, 0x90, 0x66, 0xa9, 0xf5,
	0x01, 0xd9, 0xbd, 0xd2, 0x7b, 0x90, 0x47, 0xa0, 0x49, 0xd2, 0x47, 0xd3, 0xbc, 0x6f, 0x01, 0x0c,
	0x7d, 0xf7, 0xd4, 0x0b, 0x69, 0xdf, 0x43, 0xda, 0xcb, 0x28, 0x41, 0x17, 0xdf, 0x05, 0x9a, 0xdd,
	0x12, 0x3d, 0xdd, 0x46, 0xd8, 0x7a, 0x46, 0x83, 0x0e, 0x7f, 0x03, 0xb6, 0x23, 0xf6, 0xcc, 0x34,
	0x46, 0x96, 0x7d, 0xce, 0xac, 0x81, 0xf4, 0xa1, 0x69, 0x71, 0xbf, 0xfe, 0xfa, 0x0e, 0x69, 0xae,
	0xe8, 0x5b, 0x11, 0xe0, 0x11, 0xea, 0xf7, 0x13, 0x35, 0x7d, 0x4a, 0xa0, 0x6e, 0x98, 0xcc, 0x72,
	0x06, 0xdc, 0xe3, 0x8e, 0x94, 0x4f, 0x9c, 0x5c, 0xd7, 0xd0, 0x97, 0x1f, 0xa9, 0xe0, 0xcb, 0x68,
	0x95, 0xb4, 0x7b, 0xc0, 0xf4, 0x9a, 0x61, 0xee, 0x4f, 0x2c, 0xd6, 0x63, 0x83, 0xe9, 0x13, 0x02,
	0x35, 0xc3, 0x64, 0x45, 0x5c, 0xee, 0xef, 0x2c, 0x36, 0x4b, 0xad, 0xc7, 0x6a, 0x71, 0xf1, 0xf4,
	0x0d, 0xc3, 0x7c, 0x38, 0xc5, 0xa3, 0x71, 0x17, 0x36, 0xf7, 0x3b, 0xdd, 0xf6, 0xc9, 0xa9, 0xe3,
	0x70, 0x3b, 0x0a, 0x1a, 0xbc, 0xea, 0x0d, 0x58, 0x1a, 0x1b, 0xf6, 0x69, 0x9c, 0xb4, 0xe1, 0x4b,
	0xe3, 0x15, 0xa0, 0x12, 0x7e, 0xf8, 0xf0, 0xe4, 0x72, 0xec, 0x6b, 0xb0, 0xa5, 0x9f, 0x3c, 0x70,
	0x1d, 0x11, 0xf8, 0x86, 0xe5, 0x04, 0x97, 0x2f, 0x78, 0x09, 0xd6, 0xf6, 0x3b, 0x5d, 0xed, 0x72,
	0xe0, 0x51, 0x98, 0xaa, 0xe8, 0x52, 0xe1, 0x7b, 0xae, 0x6d, 0xf5, 0xcf, 0x31, 0x07, 0x58, 0x40,
	0x5b, 0xb0, 0x39, 0x2d, 0x97, 0xe9, 0x2a, 0x77, 0x28, 0xeb, 0x55, 0xa9, 0x3c, 0x8e, 0x74, 0xd1,
	0x49, 0xa9, 0xfd, 0xb4, 0x19, 0xfb, 0x69, 0x17, 0xed, 0xa7, 0xe5, 0xf7, 0xbb, 0x0f, 0x15, 0xb9,
	0x9f, 0xdd, 0x1a, 0x7b, 0x4e, 0xbc, 0xcf, 0x6d, 0x58, 0x99, 0xbc, 0x4f, 0xd6, 0x97, 0x51, 0x18,
	0x2f, 0xbc, 0x03, 0x1b, 0x07, 0xad, 0x6e, 0xe7, 0x68, 0xaf, 0xdb, 0x39, 0xba, 0xdc, 0x0d, 0x6f,
	0xc2, 0xe6, 0xe4, 0x98, 0x91, 0xf0, 0xce, 0xfe, 0xd7, 0x59, 0xaf, 0x42, 0x55, 0x7a, 0xfb, 0x70,
	0xae, 0xa3, 0x42, 0x70, 0x7b, 0x3e, 0x70, 0x13, 0x2a, 0x07, 0xc7, 0xec, 0xe0, 0x78, 0xae, 0x10,
	0xd9, 0xef, 0x8c, 0xdb, 0x8f, 0x6c, 0xf7, 0x4c, 0x78, 0xbc, 0x3f, 0xef, 0x02, 0x6d, 0xfe, 0x05,
	0xff, 0xee, 0x40, 0x39, 0x5d, 0x21, 0x69, 0x05, 0x16, 0x0d, 0xd3, 0x8a, 0x40, 0xf2, 0x91, 0xbe,
	0x08, 0x65, 0x8c, 0x98, 0xd8, 0x59, 0xe1, 0x57, 0xa8, 0x24, 0x65, 0x71, 0x15, 0xbd, 0x03, 0x14,
	0x21, 0xa3, 0xbe, 0x21, 0x82, 0x04, 0x18, 0x7e, 0x90, 0x2a, 0x52, 0x73, 0x28, 0x15, 0x79, 0xb4,
	0x6d, 0xf4, 0xb8, 0x9d, 0xfb, 0x30, 0x21, 0xfa, 0x40, 0x2a, 0x62, 0xf4, 0x13, 0x02, 0x18, 0x94,
	0x2c, 0xc0, 0x1c, 0x4c, 0xf0, 0x4b, 0x58, 0x12, 0x3f, 0xbb, 0xea, 0x32, 0x52, 0x58, 0x1d, 0xf4,
	0x75, 0x69, 0x47, 0x46, 0x4c, 0x7f, 0x20, 0x50, 0x09, 0x9d, 0x34, 0x98, 0xb8, 0xe8, 0x3a, 0x92,
	0xf8, 0x58, 0x05, 0x12, 0xd9, 0x9a, 0xa5, 0xaf, 0xe2, 0xb5, 0x0d, 0x92, 0x4b, 0x6b, 0x46, 0xd6,
	0xa7, 0xd3, 0xe6, 0x06, 0x5e, 0x19, 0x22, 0xbb, 0x49, 0xe2, 0x24, 0x15, 0x66, 0xec, 0x39, 0x46,
	0x18, 0x11, 0x11, 0xfc, 0x26, 0xc2, 0xab, 0x11, 0xdc, 0x38, 0x9c, 0xa8, 0xe8, 0xd7, 0x04, 0x83,
	0x4c, 0x4b, 0xb6, 0x5e, 0x46, 0xc7, 0x3c, 0x56, 0xc0, 0x31, 0xe9, 0x7a, 0x8b, 0x51, 0x1f, 0x0b,
	0xe8, 0x8f, 0x04, 0x03, 0x59, 0xcb, 0x85, 0x3d, 0xa8, 0x69, 0xba, 0xbc, 0x3e, 0x2d, 0x93, 0x87,
	0x89, 0xfd, 0xd9, 0x44, 0x2c, 0x29, 0x6c, 0x7f, 0xa6, 0x32, 0x7c, 0x17, 0x66, 0x94, 0x96, 0x89,
	0xc9, 0xb2, 0x9a, 0xd6, 0xcb, 0x24, 0xd1, 0x52, 0x49, 0xf2, 0x1b, 0x81, 0x5a, 0x62, 0x7b, 0x36,
	0x7e, 0x56, 0xd4, 0x64, 0x50, 0x8d, 0x18, 0x64, 0x42, 0xe8, 0x27, 0x02, 0xd4, 0x6e, 0x49, 0x12,
	0x63, 0xcf, 0x16, 0x09, 0x85, 0x55, 0xa4, 0xf0, 0xa1, 0x0a, 0x2d, 0x5e, 0xba, 0xc9, 0xd0, 0x2b,
	0x76, 0xab, 0x1b, 0x9a, 0x1a, 0x13, 0x78, 0x4a, 0x60, 0xd3, 0x0f, 0x64, 0x23, 0x18, 0xb5, 0x61,
	0x09, 0x87, 0x35, 0xe4, 0xf0, 0xc5, 0x55, 0x73, 0x98, 0xd1, 0x22, 0xea, 0x55, 0x3f, 0x98, 0x52,
	0xd0, 0x9f, 0x09, 0xac, 0x87, 0x15, 0x29, 0x9d, 0x12, 0x15, 0x64, 0xf2, 0x89, 0x0a, 0x01, 0x95,
	0x6b, 0x90, 0xf4, 0x35, 0x2c, 0x4a, 0x93, 0xae, 0x2b, 0x66, 0xd0, 0xce, 0x32, 0x58, 0x57, 0x86,
	0x41, 0xbb, 0x88, 0x41, 0x3b, 0xcd, 0xe0, 0x57, 0x02, 0xd5, 0x30, 0x25, 0x18, 0x4f, 0x73, 0xa0,
	0xc8, 0xe1, 0xd3, 0xab, 0xe6, 0x50, 0xd4, 0x3f, 0x47, 0x79, 0xb1, 0x97, 0x62, 0xf1, 0x0d, 0x81,
	0x15, 0x5b, 0xb0, 0x54, 0x4e, 0x57, 0xd5, 0xc8, 0xe9, 0x7c, 0xe7, 0xac, 0x97, 0x6c, 0x71, 0x20,
	0x52, 0x65, 0x35, 0x76, 0x7e, 0xd2, 0xf0, 0x4b, 0xe3, 0x37, 0xd4, 0x68, 0x16, 0x0b, 0x7f, 0x8e,
	0x44, 0xde, 0x3f, 0x14, 0xde, 0x59, 0xba, 0x2a, 0xa1, 0x71, 0x66, 0xd4, 0xc8, 0x27, 0x44, 0x36,
	0xd5, 0xa8, 0x4a, 0x33, 0x7e, 0x95, 0x84, 0xcd, 0x5d, 0x4e, 0x11, 0xb3, 0xd1, 0xa6, 0xd9, 0xd4,
	0x94, 0x61, 0xa3, 0xcd, 0x62, 0x93, 0x57, 0xd0, 0x3f, 0x09, 0x6c, 0x27, 0x9d, 0xf0, 0x14, 0xa3,
	0x2d, 0xb5, 0xef, 0xa7, 0x16, 0x35, 0xdf, 0x33, 0x48, 0x69, 0xc5, 0xa4, 0xea, 0x6a, 0x5f, 0x53,
	0x2d, 0xea, 0x4c, 0xf2, 0xa4, 0xfe, 0x08, 0x7b, 0xac, 0x36, 0x13, 0x3e, 0xcb, 0x0d, 0x27, 0xb6,
	0x91, 0xd1, 0x97, 0x2a, 0xd4, 0x83, 0xa2, 0x29, 0x4d, 0x3c, 0x86, 0xe9, 0xa4, 0xc7, 0x26, 0x31,
	0x1f, 0xad, 0x80, 0xcf, 0x73, 0x4a, 0xf1, 0xd1, 0x0a, 0xf9, 0x68, 0x39, 0x3e, 0x8d, 0xbf, 0x08,
	0xac, 0x4f, 0x4d, 0x14, 0xe9, 0x2f, 0x45, 0xd2, 0x3a, 0xc1, 0xa1, 0xe1, 0xe7, 0xca, 0x0d, 0x40,
	0x99, 0x15, 0xf0, 0x91, 0xbe, 0xda, 0x1b, 0x7a, 0x0f, 0x50, 0xbc, 0x27, 0xa5, 0x8d, 0xbf, 0x17,
	0xa0, 0x56, 0x0c, 0xbd, 0x78, 0x44, 0x4c, 0x2e, 0x1e, 0x11, 0x17, 0x4f, 0xa3, 0x17, 0x66, 0x4d,
	0xa3, 0x0b, 0xa7, 0xf2, 0x8b, 0xcf, 0xde, 0x54, 0xfe, 0x5a, 0x6e, 0x2a, 0xdf, 0xf8, 0x9e, 0xc0,
	0x5a, 0x6e, 0x7c, 0x4b, 0xbf, 0x22, 0xe9, 0xf9, 0x96, 0x92, 0xb3, 0xf2, 0xd0, 0xbe, 0xde, 0x75,
	0xfc, 0x7b, 0xea, 0xde, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xbb, 0x75, 0x23, 0xc0, 0x1a,
	0x00, 0x00,
}
