// Code generated by protoc-gen-go.
// source: ipv6_nd_if_entry.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_interfaces_bundle_interface is a generated protocol buffer package.

It is generated from these files:
	ipv6_nd_if_entry.proto

It has these top-level messages:
	Ipv6NdIfEntry_KEYS
	Ipv6NdIfEntry
	Ipv6NdIfParams
	Ipv6NdAddr
	Ipv6NdGspnode
*/
package cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_interfaces_bundle_interface

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Detailed Info of ND IPv6 Interface entry
type Ipv6NdIfEntry_KEYS struct {
	NodeName      string `protobuf:"bytes,1,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	InterfaceName string `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName" json:"interface_name,omitempty"`
}

func (m *Ipv6NdIfEntry_KEYS) Reset()                    { *m = Ipv6NdIfEntry_KEYS{} }
func (m *Ipv6NdIfEntry_KEYS) String() string            { return proto.CompactTextString(m) }
func (*Ipv6NdIfEntry_KEYS) ProtoMessage()               {}
func (*Ipv6NdIfEntry_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ipv6NdIfEntry_KEYS) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Ipv6NdIfEntry_KEYS) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

type Ipv6NdIfEntry struct {
	// Parent interface name
	ParentInterfaceName string `protobuf:"bytes,50,opt,name=parent_interface_name,json=parentInterfaceName" json:"parent_interface_name,omitempty"`
	// Interface type
	Iftype uint32 `protobuf:"varint,51,opt,name=iftype" json:"iftype,omitempty"`
	// MTU
	Mtu uint32 `protobuf:"varint,52,opt,name=mtu" json:"mtu,omitempty"`
	// etype
	Etype uint32 `protobuf:"varint,53,opt,name=etype" json:"etype,omitempty"`
	// vlan tag/id/ucv
	VlanTag uint32 `protobuf:"varint,54,opt,name=vlan_tag,json=vlanTag" json:"vlan_tag,omitempty"`
	// mac address size
	MacAddrSize uint32 `protobuf:"varint,55,opt,name=mac_addr_size,json=macAddrSize" json:"mac_addr_size,omitempty"`
	// mac address
	MacAddr string `protobuf:"bytes,56,opt,name=mac_addr,json=macAddr" json:"mac_addr,omitempty"`
	// If true, interface is enabled
	IsInterfaceEnabled bool `protobuf:"varint,57,opt,name=is_interface_enabled,json=isInterfaceEnabled" json:"is_interface_enabled,omitempty"`
	// If true, IPv6 is enabled
	IsIpv6Enabled bool `protobuf:"varint,58,opt,name=is_ipv6_enabled,json=isIpv6Enabled" json:"is_ipv6_enabled,omitempty"`
	// If true, MPLS is enabled
	IsMplsEnabled bool `protobuf:"varint,59,opt,name=is_mpls_enabled,json=isMplsEnabled" json:"is_mpls_enabled,omitempty"`
	// ND interface parameters
	NdParameters *Ipv6NdIfParams `protobuf:"bytes,60,opt,name=nd_parameters,json=ndParameters" json:"nd_parameters,omitempty"`
	// List of ND global addresses
	GlobalAddressList []*Ipv6NdAddr `protobuf:"bytes,61,rep,name=global_address_list,json=globalAddressList" json:"global_address_list,omitempty"`
	// Link local address
	LocalAddress *Ipv6NdAddr `protobuf:"bytes,62,opt,name=local_address,json=localAddress" json:"local_address,omitempty"`
	// List of member links
	MemberLinkList []uint32 `protobuf:"varint,63,rep,packed,name=member_link_list,json=memberLinkList" json:"member_link_list,omitempty"`
	// List of member nodes
	MemberNodeList []*Ipv6NdGspnode `protobuf:"bytes,64,rep,name=member_node_list,json=memberNodeList" json:"member_node_list,omitempty"`
}

func (m *Ipv6NdIfEntry) Reset()                    { *m = Ipv6NdIfEntry{} }
func (m *Ipv6NdIfEntry) String() string            { return proto.CompactTextString(m) }
func (*Ipv6NdIfEntry) ProtoMessage()               {}
func (*Ipv6NdIfEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Ipv6NdIfEntry) GetParentInterfaceName() string {
	if m != nil {
		return m.ParentInterfaceName
	}
	return ""
}

func (m *Ipv6NdIfEntry) GetIftype() uint32 {
	if m != nil {
		return m.Iftype
	}
	return 0
}

func (m *Ipv6NdIfEntry) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *Ipv6NdIfEntry) GetEtype() uint32 {
	if m != nil {
		return m.Etype
	}
	return 0
}

func (m *Ipv6NdIfEntry) GetVlanTag() uint32 {
	if m != nil {
		return m.VlanTag
	}
	return 0
}

func (m *Ipv6NdIfEntry) GetMacAddrSize() uint32 {
	if m != nil {
		return m.MacAddrSize
	}
	return 0
}

func (m *Ipv6NdIfEntry) GetMacAddr() string {
	if m != nil {
		return m.MacAddr
	}
	return ""
}

func (m *Ipv6NdIfEntry) GetIsInterfaceEnabled() bool {
	if m != nil {
		return m.IsInterfaceEnabled
	}
	return false
}

func (m *Ipv6NdIfEntry) GetIsIpv6Enabled() bool {
	if m != nil {
		return m.IsIpv6Enabled
	}
	return false
}

func (m *Ipv6NdIfEntry) GetIsMplsEnabled() bool {
	if m != nil {
		return m.IsMplsEnabled
	}
	return false
}

func (m *Ipv6NdIfEntry) GetNdParameters() *Ipv6NdIfParams {
	if m != nil {
		return m.NdParameters
	}
	return nil
}

func (m *Ipv6NdIfEntry) GetGlobalAddressList() []*Ipv6NdAddr {
	if m != nil {
		return m.GlobalAddressList
	}
	return nil
}

func (m *Ipv6NdIfEntry) GetLocalAddress() *Ipv6NdAddr {
	if m != nil {
		return m.LocalAddress
	}
	return nil
}

func (m *Ipv6NdIfEntry) GetMemberLinkList() []uint32 {
	if m != nil {
		return m.MemberLinkList
	}
	return nil
}

func (m *Ipv6NdIfEntry) GetMemberNodeList() []*Ipv6NdGspnode {
	if m != nil {
		return m.MemberNodeList
	}
	return nil
}

// Detailed Info of ND IPv6 Interface
type Ipv6NdIfParams struct {
	// If true, DAD (D.. A.. D..) is enabled otherwise it is disabled
	IsDadEnabled bool `protobuf:"varint,1,opt,name=is_dad_enabled,json=isDadEnabled" json:"is_dad_enabled,omitempty"`
	// DAD attempt count
	DadAttempts uint32 `protobuf:"varint,2,opt,name=dad_attempts,json=dadAttempts" json:"dad_attempts,omitempty"`
	// ICMP redirect flag
	IsIcmPv6Redirect bool `protobuf:"varint,3,opt,name=is_icm_pv6_redirect,json=isIcmPv6Redirect" json:"is_icm_pv6_redirect,omitempty"`
	// Flag used for utilising DHCP
	IsDhcpManaged bool `protobuf:"varint,4,opt,name=is_dhcp_managed,json=isDhcpManaged" json:"is_dhcp_managed,omitempty"`
	// Flag used to manage routable address
	IsRouteAddressManaged bool `protobuf:"varint,5,opt,name=is_route_address_managed,json=isRouteAddressManaged" json:"is_route_address_managed,omitempty"`
	// Suppress flag
	IsSuppressed bool `protobuf:"varint,6,opt,name=is_suppressed,json=isSuppressed" json:"is_suppressed,omitempty"`
	// unicast RA send flag
	SendUnicastRa bool `protobuf:"varint,7,opt,name=send_unicast_ra,json=sendUnicastRa" json:"send_unicast_ra,omitempty"`
	// ND retransmit interval in msec
	NdRetransmitInterval uint32 `protobuf:"varint,8,opt,name=nd_retransmit_interval,json=ndRetransmitInterval" json:"nd_retransmit_interval,omitempty"`
	// ND router advertisement minimum transmit interval in sec
	NdMinTransmitInterval uint32 `protobuf:"varint,9,opt,name=nd_min_transmit_interval,json=ndMinTransmitInterval" json:"nd_min_transmit_interval,omitempty"`
	// ND router advertisement maximum transmit interval in sec
	NdMaxTransmitInterval uint32 `protobuf:"varint,10,opt,name=nd_max_transmit_interval,json=ndMaxTransmitInterval" json:"nd_max_transmit_interval,omitempty"`
	// ND router advertisement life time in sec
	NdAdvertisementLifetime uint32 `protobuf:"varint,11,opt,name=nd_advertisement_lifetime,json=ndAdvertisementLifetime" json:"nd_advertisement_lifetime,omitempty"`
	// Time to reach ND in msec
	NdReachableTime uint32 `protobuf:"varint,12,opt,name=nd_reachable_time,json=ndReachableTime" json:"nd_reachable_time,omitempty"`
	// Completed adjacency limit per interface
	NdCacheLimit uint32 `protobuf:"varint,13,opt,name=nd_cache_limit,json=ndCacheLimit" json:"nd_cache_limit,omitempty"`
	// Completed PROTO entry Count
	CompleteProtocolCount uint32 `protobuf:"varint,14,opt,name=complete_protocol_count,json=completeProtocolCount" json:"complete_protocol_count,omitempty"`
	// Completed GLEAN entry count
	CompleteGleanCount uint32 `protobuf:"varint,15,opt,name=complete_glean_count,json=completeGleanCount" json:"complete_glean_count,omitempty"`
	// Incomplete PROTO entry count
	IncompleteProtocolCount uint32 `protobuf:"varint,16,opt,name=incomplete_protocol_count,json=incompleteProtocolCount" json:"incomplete_protocol_count,omitempty"`
	// Incomplete GLEAN entry count
	IncompleteGleanCount uint32 `protobuf:"varint,17,opt,name=incomplete_glean_count,json=incompleteGleanCount" json:"incomplete_glean_count,omitempty"`
	// Dropped PROTO entry request count
	DroppedProtocolReqCount uint32 `protobuf:"varint,18,opt,name=dropped_protocol_req_count,json=droppedProtocolReqCount" json:"dropped_protocol_req_count,omitempty"`
	// Dropped GLEAN entry lequest count
	DroppedGleanReqCount uint32 `protobuf:"varint,19,opt,name=dropped_glean_req_count,json=droppedGleanReqCount" json:"dropped_glean_req_count,omitempty"`
}

func (m *Ipv6NdIfParams) Reset()                    { *m = Ipv6NdIfParams{} }
func (m *Ipv6NdIfParams) String() string            { return proto.CompactTextString(m) }
func (*Ipv6NdIfParams) ProtoMessage()               {}
func (*Ipv6NdIfParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ipv6NdIfParams) GetIsDadEnabled() bool {
	if m != nil {
		return m.IsDadEnabled
	}
	return false
}

func (m *Ipv6NdIfParams) GetDadAttempts() uint32 {
	if m != nil {
		return m.DadAttempts
	}
	return 0
}

func (m *Ipv6NdIfParams) GetIsIcmPv6Redirect() bool {
	if m != nil {
		return m.IsIcmPv6Redirect
	}
	return false
}

func (m *Ipv6NdIfParams) GetIsDhcpManaged() bool {
	if m != nil {
		return m.IsDhcpManaged
	}
	return false
}

func (m *Ipv6NdIfParams) GetIsRouteAddressManaged() bool {
	if m != nil {
		return m.IsRouteAddressManaged
	}
	return false
}

func (m *Ipv6NdIfParams) GetIsSuppressed() bool {
	if m != nil {
		return m.IsSuppressed
	}
	return false
}

func (m *Ipv6NdIfParams) GetSendUnicastRa() bool {
	if m != nil {
		return m.SendUnicastRa
	}
	return false
}

func (m *Ipv6NdIfParams) GetNdRetransmitInterval() uint32 {
	if m != nil {
		return m.NdRetransmitInterval
	}
	return 0
}

func (m *Ipv6NdIfParams) GetNdMinTransmitInterval() uint32 {
	if m != nil {
		return m.NdMinTransmitInterval
	}
	return 0
}

func (m *Ipv6NdIfParams) GetNdMaxTransmitInterval() uint32 {
	if m != nil {
		return m.NdMaxTransmitInterval
	}
	return 0
}

func (m *Ipv6NdIfParams) GetNdAdvertisementLifetime() uint32 {
	if m != nil {
		return m.NdAdvertisementLifetime
	}
	return 0
}

func (m *Ipv6NdIfParams) GetNdReachableTime() uint32 {
	if m != nil {
		return m.NdReachableTime
	}
	return 0
}

func (m *Ipv6NdIfParams) GetNdCacheLimit() uint32 {
	if m != nil {
		return m.NdCacheLimit
	}
	return 0
}

func (m *Ipv6NdIfParams) GetCompleteProtocolCount() uint32 {
	if m != nil {
		return m.CompleteProtocolCount
	}
	return 0
}

func (m *Ipv6NdIfParams) GetCompleteGleanCount() uint32 {
	if m != nil {
		return m.CompleteGleanCount
	}
	return 0
}

func (m *Ipv6NdIfParams) GetIncompleteProtocolCount() uint32 {
	if m != nil {
		return m.IncompleteProtocolCount
	}
	return 0
}

func (m *Ipv6NdIfParams) GetIncompleteGleanCount() uint32 {
	if m != nil {
		return m.IncompleteGleanCount
	}
	return 0
}

func (m *Ipv6NdIfParams) GetDroppedProtocolReqCount() uint32 {
	if m != nil {
		return m.DroppedProtocolReqCount
	}
	return 0
}

func (m *Ipv6NdIfParams) GetDroppedGleanReqCount() uint32 {
	if m != nil {
		return m.DroppedGleanReqCount
	}
	return 0
}

// List of IPv6 ND Addresses
type Ipv6NdAddr struct {
	// IPv6 address
	Ipv6Address string `protobuf:"bytes,1,opt,name=ipv6_address,json=ipv6Address" json:"ipv6_address,omitempty"`
}

func (m *Ipv6NdAddr) Reset()                    { *m = Ipv6NdAddr{} }
func (m *Ipv6NdAddr) String() string            { return proto.CompactTextString(m) }
func (*Ipv6NdAddr) ProtoMessage()               {}
func (*Ipv6NdAddr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Ipv6NdAddr) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

// GSP node info
type Ipv6NdGspnode struct {
	// Node Name
	NodeName string `protobuf:"bytes,1,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	// Number of links on the node
	TotalLinks uint32 `protobuf:"varint,2,opt,name=total_links,json=totalLinks" json:"total_links,omitempty"`
}

func (m *Ipv6NdGspnode) Reset()                    { *m = Ipv6NdGspnode{} }
func (m *Ipv6NdGspnode) String() string            { return proto.CompactTextString(m) }
func (*Ipv6NdGspnode) ProtoMessage()               {}
func (*Ipv6NdGspnode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Ipv6NdGspnode) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Ipv6NdGspnode) GetTotalLinks() uint32 {
	if m != nil {
		return m.TotalLinks
	}
	return 0
}

func init() {
	proto.RegisterType((*Ipv6NdIfEntry_KEYS)(nil), "cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_interfaces.bundle_interface.ipv6_nd_if_entry_KEYS")
	proto.RegisterType((*Ipv6NdIfEntry)(nil), "cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_interfaces.bundle_interface.ipv6_nd_if_entry")
	proto.RegisterType((*Ipv6NdIfParams)(nil), "cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_interfaces.bundle_interface.ipv6_nd_if_params")
	proto.RegisterType((*Ipv6NdAddr)(nil), "cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_interfaces.bundle_interface.ipv6_nd_addr")
	proto.RegisterType((*Ipv6NdGspnode)(nil), "cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_interfaces.bundle_interface.ipv6_nd_gspnode")
}

func init() { proto.RegisterFile("ipv6_nd_if_entry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 950 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcb, 0x6e, 0x1b, 0x37,
	0x17, 0xc6, 0xfc, 0xfe, 0xe3, 0x0b, 0xa5, 0x91, 0x65, 0xfa, 0x92, 0x71, 0xbb, 0xa8, 0xaa, 0xa6,
	0x85, 0x50, 0xa0, 0x42, 0xeb, 0x38, 0x4a, 0xeb, 0xf4, 0x66, 0x24, 0x41, 0x61, 0xd4, 0x4e, 0x8d,
	0xb1, 0xbb, 0x28, 0xb2, 0x20, 0xa8, 0xe1, 0xb1, 0x4c, 0x64, 0xc8, 0x99, 0x90, 0x94, 0x60, 0xe7,
	0x21, 0xba, 0x29, 0x50, 0xa0, 0x4f, 0xd3, 0xd7, 0xe9, 0x63, 0x14, 0x3c, 0x9c, 0x19, 0x29, 0x76,
	0xd3, 0x5d, 0xbd, 0x31, 0xcc, 0xef, 0xc2, 0xf3, 0xf1, 0x76, 0x34, 0x64, 0x47, 0x96, 0xb3, 0x11,
	0xd3, 0x82, 0xc9, 0x0b, 0x06, 0xda, 0x99, 0xeb, 0x61, 0x69, 0x0a, 0x57, 0xd0, 0x97, 0x99, 0xb4,
	0x59, 0xc1, 0x64, 0x61, 0xd9, 0x95, 0x61, 0xb5, 0xa8, 0x28, 0xc1, 0x0c, 0xc3, 0xa0, 0x10, 0xc0,
	0x84, 0xd7, 0xcc, 0xc0, 0x5c, 0x0f, 0xfd, 0xd0, 0xe2, 0xdf, 0xe1, 0x78, 0xaa, 0x45, 0x0e, 0x4c,
	0x6a, 0x07, 0xe6, 0x82, 0x67, 0x60, 0x6f, 0x21, 0xfd, 0x97, 0x64, 0xfb, 0x66, 0x59, 0xf6, 0xe3,
	0xf3, 0x5f, 0xce, 0xe8, 0xfb, 0x64, 0x0d, 0x27, 0xd6, 0x5c, 0x41, 0x12, 0xf5, 0xa2, 0xc1, 0x5a,
	0xba, 0xea, 0x81, 0x17, 0x5c, 0x01, 0xfd, 0x98, 0x74, 0x9a, 0x29, 0x82, 0xe2, 0x7f, 0xa8, 0x88,
	0x1b, 0xd4, 0xcb, 0xfa, 0x7f, 0xad, 0x90, 0xee, 0xcd, 0xd9, 0xe9, 0x1e, 0xd9, 0x2e, 0xb9, 0x01,
	0xed, 0xd8, 0x8d, 0x29, 0xf6, 0x70, 0x8a, 0xcd, 0x40, 0x1e, 0x2d, 0x4e, 0x44, 0x77, 0xc8, 0xb2,
	0xbc, 0x70, 0xd7, 0x25, 0x24, 0x0f, 0x7b, 0xd1, 0x20, 0x4e, 0xab, 0x11, 0xed, 0x92, 0x25, 0xe5,
	0xa6, 0xc9, 0x3e, 0x82, 0xfe, 0x5f, 0xba, 0x45, 0xee, 0x01, 0x0a, 0x1f, 0x21, 0x16, 0x06, 0x74,
	0x97, 0xac, 0xce, 0x72, 0xae, 0x99, 0xe3, 0x93, 0x64, 0x84, 0xc4, 0x8a, 0x1f, 0x9f, 0xf3, 0x09,
	0xed, 0x93, 0x58, 0xf1, 0x8c, 0x71, 0x21, 0x0c, 0xb3, 0xf2, 0x0d, 0x24, 0x8f, 0x91, 0x6f, 0x29,
	0x9e, 0x1d, 0x0a, 0x61, 0xce, 0xe4, 0x1b, 0xb4, 0xd7, 0x9a, 0xe4, 0x4b, 0x4c, 0xb9, 0x52, 0xd1,
	0xf4, 0x73, 0xb2, 0x25, 0xed, 0xc2, 0x4a, 0x40, 0xf3, 0x71, 0x0e, 0x22, 0xf9, 0xaa, 0x17, 0x0d,
	0x56, 0x53, 0x2a, 0x6d, 0xb3, 0x90, 0xe7, 0x81, 0xa1, 0x9f, 0x90, 0x75, 0xef, 0xf0, 0xdb, 0x52,
	0x8b, 0x0f, 0x50, 0x1c, 0x4b, 0x7b, 0x54, 0xce, 0x46, 0x6f, 0xeb, 0x54, 0x99, 0xdb, 0x46, 0xf7,
	0xa4, 0xd6, 0x9d, 0x94, 0xb9, 0xad, 0x75, 0xbf, 0x45, 0x24, 0xd6, 0x82, 0x95, 0xdc, 0x70, 0x05,
	0x0e, 0x8c, 0x4d, 0xbe, 0xee, 0x45, 0x83, 0xd6, 0x9e, 0x1e, 0xfe, 0x87, 0xf7, 0x66, 0xb8, 0x70,
	0xac, 0x58, 0xd9, 0xa6, 0x6d, 0x2d, 0x4e, 0x9b, 0x0c, 0xf4, 0x8f, 0x88, 0x6c, 0x4e, 0xf2, 0x62,
	0xcc, 0x73, 0xdc, 0x36, 0xb0, 0x96, 0xe5, 0xd2, 0xba, 0xe4, 0x9b, 0xde, 0xd2, 0xa0, 0xb5, 0x27,
	0xef, 0x24, 0x9b, 0x2f, 0x9c, 0x6e, 0x84, 0x14, 0x87, 0x21, 0xc4, 0xb1, 0xb4, 0x8e, 0xfe, 0x1a,
	0x91, 0x38, 0x2f, 0xb2, 0x79, 0xb4, 0xe4, 0x5b, 0xdc, 0xb1, 0x3b, 0x4c, 0xd5, 0xc6, 0xfa, 0x55,
	0x28, 0x3a, 0x20, 0x5d, 0x05, 0x6a, 0x0c, 0x86, 0xe5, 0x52, 0xbf, 0x0a, 0x1b, 0xf5, 0x5d, 0x6f,
	0x69, 0x10, 0xa7, 0x9d, 0x80, 0x1f, 0x4b, 0xfd, 0x0a, 0xa3, 0xff, 0x1e, 0x35, 0x52, 0x0c, 0x83,
	0xd2, 0xef, 0x71, 0x4f, 0xf3, 0x3b, 0x49, 0x3f, 0xb1, 0xa5, 0xb7, 0xd4, 0xc1, 0x5e, 0x14, 0x02,
	0x7c, 0xb0, 0xfe, 0x9f, 0x2b, 0x64, 0xe3, 0xd6, 0x9d, 0xa0, 0x0f, 0x48, 0x47, 0x5a, 0x26, 0xb8,
	0x68, 0xae, 0x70, 0x84, 0x57, 0xb8, 0x2d, 0xed, 0x33, 0x2e, 0xea, 0x1b, 0xfc, 0x21, 0x69, 0x7b,
	0x09, 0x77, 0x0e, 0x54, 0xe9, 0x2c, 0xf6, 0x92, 0x38, 0x6d, 0x09, 0x2e, 0x0e, 0x2b, 0x88, 0x7e,
	0x46, 0x36, 0xfd, 0xa3, 0xc9, 0x14, 0xf3, 0x35, 0x0c, 0x08, 0x69, 0x20, 0x73, 0xc9, 0x12, 0xce,
	0xd6, 0x95, 0xf6, 0x28, 0x53, 0xa7, 0xb3, 0x51, 0x5a, 0xe1, 0xd5, 0xdb, 0x11, 0x97, 0x59, 0xc9,
	0x14, 0xd7, 0x7c, 0x02, 0x22, 0xf9, 0x7f, 0xfd, 0x76, 0x9e, 0x5d, 0x66, 0xe5, 0x49, 0x00, 0xe9,
	0x63, 0x92, 0x48, 0xcb, 0x4c, 0x31, 0x75, 0xd0, 0x5c, 0xd3, 0xda, 0x70, 0x0f, 0x0d, 0xdb, 0xd2,
	0xa6, 0x9e, 0xae, 0x8e, 0xaa, 0x36, 0x7e, 0x44, 0x62, 0x69, 0x99, 0x9d, 0x96, 0xa5, 0x47, 0x41,
	0x24, 0xcb, 0xf5, 0xba, 0xce, 0x1a, 0xcc, 0xa7, 0xb0, 0xa0, 0x05, 0x9b, 0x6a, 0x99, 0x71, 0xeb,
	0x98, 0xe1, 0xc9, 0x4a, 0x48, 0xe1, 0xe1, 0x9f, 0x03, 0x9a, 0x72, 0xba, 0x4f, 0x76, 0xb4, 0x60,
	0x06, 0x9c, 0xe1, 0xda, 0x2a, 0x59, 0x35, 0xc6, 0x19, 0xcf, 0x93, 0x55, 0xdc, 0x89, 0x2d, 0x2d,
	0xd2, 0x86, 0x3c, 0xaa, 0x38, 0x9f, 0x5d, 0x0b, 0xa6, 0xa4, 0x66, 0xb7, 0x7d, 0x6b, 0xe8, 0xdb,
	0xd6, 0xe2, 0x44, 0xea, 0xf3, 0x77, 0x18, 0xf9, 0xd5, 0x3f, 0x18, 0x49, 0x63, 0xe4, 0x57, 0xb7,
	0x8c, 0x07, 0x64, 0x17, 0xef, 0xef, 0x0c, 0x8c, 0x93, 0x16, 0x94, 0xef, 0xe1, 0xb9, 0xbc, 0x00,
	0x27, 0x15, 0x24, 0x2d, 0x74, 0xde, 0xd7, 0xe2, 0x70, 0x91, 0x3f, 0xae, 0x68, 0xfa, 0x29, 0xd9,
	0xc0, 0x35, 0xf2, 0xec, 0xd2, 0x1f, 0x3a, 0x43, 0x4f, 0x1b, 0x3d, 0xeb, 0x7e, 0x79, 0x15, 0x7e,
	0xee, 0xb5, 0x0f, 0x48, 0x47, 0x0b, 0x96, 0xf1, 0xec, 0xd2, 0x5f, 0x70, 0x25, 0x5d, 0x12, 0xa3,
	0xb0, 0xad, 0xc5, 0x53, 0x0f, 0x1e, 0x7b, 0x8c, 0x8e, 0xc8, 0xfd, 0xac, 0x50, 0x65, 0x0e, 0x0e,
	0x18, 0xfe, 0x50, 0x66, 0x45, 0xce, 0xb2, 0x62, 0xaa, 0x5d, 0xd2, 0x09, 0xab, 0xa8, 0xe9, 0xd3,
	0x8a, 0x7d, 0xea, 0x49, 0xdf, 0xb1, 0x1b, 0xdf, 0x24, 0x07, 0xae, 0x2b, 0xd3, 0x3a, 0x9a, 0x68,
	0xcd, 0xfd, 0xe0, 0xa9, 0xe0, 0x38, 0x20, 0xbb, 0x52, 0xbf, 0xab, 0x56, 0x37, 0xac, 0x7b, 0x2e,
	0x78, 0xbb, 0xda, 0x3e, 0xd9, 0x59, 0xf0, 0x2e, 0xd6, 0xdb, 0x08, 0x67, 0x3b, 0x67, 0x17, 0x2a,
	0x3e, 0x21, 0xef, 0x09, 0x53, 0x94, 0x25, 0x88, 0x79, 0x39, 0x03, 0xaf, 0x2b, 0x27, 0x0d, 0x25,
	0x2b, 0x45, 0x5d, 0x2f, 0x85, 0xd7, 0xc1, 0xfc, 0x88, 0xd4, 0x54, 0x55, 0x6f, 0xee, 0xdc, 0x0c,
	0x35, 0x2b, 0x1a, 0x0b, 0xd6, 0xb6, 0xfe, 0x17, 0xa4, 0xbd, 0xd8, 0xa2, 0xfc, 0xab, 0xc4, 0x71,
	0xdd, 0x23, 0xc3, 0x37, 0x40, 0xcb, 0x63, 0xd5, 0x63, 0xe8, 0xff, 0x44, 0xd6, 0x6f, 0xf4, 0x85,
	0x7f, 0xff, 0x6c, 0xf8, 0x80, 0xb4, 0x5c, 0xe1, 0x78, 0x8e, 0x6d, 0xae, 0x7e, 0xe7, 0x04, 0x21,
	0xdf, 0xe1, 0xec, 0x78, 0x19, 0x57, 0xfb, 0xf0, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x01,
	0xed, 0xc7, 0x0b, 0x09, 0x00, 0x00,
}
