// Code generated by protoc-gen-go.
// source: bgp_vrf_info_bag.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_standby_vrfs_vrf_information is a generated protocol buffer package.

It is generated from these files:
	bgp_vrf_info_bag.proto

It has these top-level messages:
	BgpVrfInfoBag_KEYS
	BgpVrfInfoBag
*/
package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_standby_vrfs_vrf_information

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BGP VRF information bag
type BgpVrfInfoBag_KEYS struct {
	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
	VrfName      string `protobuf:"bytes,2,opt,name=vrf_name,json=vrfName" json:"vrf_name,omitempty"`
}

func (m *BgpVrfInfoBag_KEYS) Reset()                    { *m = BgpVrfInfoBag_KEYS{} }
func (m *BgpVrfInfoBag_KEYS) String() string            { return proto.CompactTextString(m) }
func (*BgpVrfInfoBag_KEYS) ProtoMessage()               {}
func (*BgpVrfInfoBag_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BgpVrfInfoBag_KEYS) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *BgpVrfInfoBag_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

type BgpVrfInfoBag struct {
	// Route Distinguisher
	RouteDistinguisher string `protobuf:"bytes,50,opt,name=route_distinguisher,json=routeDistinguisher" json:"route_distinguisher,omitempty"`
}

func (m *BgpVrfInfoBag) Reset()                    { *m = BgpVrfInfoBag{} }
func (m *BgpVrfInfoBag) String() string            { return proto.CompactTextString(m) }
func (*BgpVrfInfoBag) ProtoMessage()               {}
func (*BgpVrfInfoBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BgpVrfInfoBag) GetRouteDistinguisher() string {
	if m != nil {
		return m.RouteDistinguisher
	}
	return ""
}

func init() {
	proto.RegisterType((*BgpVrfInfoBag_KEYS)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.information.bgp_vrf_info_bag_KEYS")
	proto.RegisterType((*BgpVrfInfoBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.information.bgp_vrf_info_bag")
}

func init() { proto.RegisterFile("bgp_vrf_info_bag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x3f, 0x4b, 0x06, 0x31,
	0x0c, 0xc6, 0x79, 0x1d, 0xfc, 0x53, 0x14, 0xa4, 0xa2, 0x9c, 0x9b, 0x9c, 0x8b, 0x53, 0x05, 0xf5,
	0x1b, 0xa8, 0x93, 0xe0, 0xa0, 0xc3, 0xe1, 0x14, 0xda, 0xbb, 0xb6, 0x66, 0xb8, 0xa6, 0xa4, 0xbd,
	0xa2, 0xdf, 0x5e, 0x5a, 0xf0, 0x78, 0xb9, 0x25, 0x79, 0xc8, 0x2f, 0xcf, 0x13, 0x22, 0xae, 0x8c,
	0x8f, 0x50, 0xd8, 0x01, 0x06, 0x47, 0x60, 0xb4, 0x57, 0x91, 0x29, 0x93, 0x1c, 0x46, 0x4c, 0x23,
	0x01, 0x52, 0x82, 0x1f, 0x06, 0x8c, 0xe5, 0x09, 0xea, 0x26, 0x45, 0xcb, 0xca, 0xf8, 0xa8, 0x30,
	0xa4, 0xac, 0xc3, 0x68, 0xd3, 0xaa, 0x56, 0x01, 0xb5, 0x4d, 0xe6, 0x57, 0x15, 0x76, 0xa9, 0x16,
	0x55, 0xb3, 0x79, 0xd6, 0x19, 0x29, 0xf4, 0x83, 0xb8, 0xdc, 0x9e, 0x84, 0xb7, 0xd7, 0xaf, 0x4f,
	0x79, 0x2b, 0xce, 0xd6, 0x84, 0xa0, 0x67, 0xdb, 0xed, 0x6e, 0x76, 0x77, 0x27, 0x1f, 0xa7, 0xff,
	0xc3, 0x77, 0x3d, 0x5b, 0x79, 0x2d, 0x8e, 0xab, 0xb3, 0xf1, 0x83, 0xc6, 0x8f, 0x0a, 0xbb, 0x8a,
	0xfa, 0x67, 0x71, 0xbe, 0x0d, 0x96, 0xf7, 0xe2, 0x82, 0x69, 0xc9, 0x16, 0x26, 0x4c, 0x19, 0x83,
	0x5f, 0x30, 0x7d, 0x5b, 0xee, 0x1e, 0x9a, 0x53, 0x36, 0xf4, 0xb2, 0x4f, 0xcc, 0x61, 0xfb, 0xfe,
	0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x46, 0xb4, 0xb8, 0x17, 0x01, 0x00, 0x00,
}
