// Code generated by protoc-gen-go.
// source: bgp_upderr_proc_bag.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_update_inbound_error_process is a generated protocol buffer package.

It is generated from these files:
	bgp_upderr_proc_bag.proto

It has these top-level messages:
	BgpUpderrProcBag_KEYS
	BgpUpderrProcBag
	BgpTimespec
*/
package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_update_inbound_error_process

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BGP Update error-handling Process information
type BgpUpderrProcBag_KEYS struct {
	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
}

func (m *BgpUpderrProcBag_KEYS) Reset()                    { *m = BgpUpderrProcBag_KEYS{} }
func (m *BgpUpderrProcBag_KEYS) String() string            { return proto.CompactTextString(m) }
func (*BgpUpderrProcBag_KEYS) ProtoMessage()               {}
func (*BgpUpderrProcBag_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BgpUpderrProcBag_KEYS) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

type BgpUpderrProcBag struct {
	// Is basic error-handling for EBGP enabled
	UpdateErrorHandlingBasicEbgp bool `protobuf:"varint,50,opt,name=update_error_handling_basic_ebgp,json=updateErrorHandlingBasicEbgp" json:"update_error_handling_basic_ebgp,omitempty"`
	// Is basic error-handling for IBGP enabled
	UpdateErrorHandlingBasicIbgp bool `protobuf:"varint,51,opt,name=update_error_handling_basic_ibgp,json=updateErrorHandlingBasicIbgp" json:"update_error_handling_basic_ibgp,omitempty"`
	// Is extended error-handling for EBGP enabled
	UpdateErrorHandlingExtendedEbgp bool `protobuf:"varint,52,opt,name=update_error_handling_extended_ebgp,json=updateErrorHandlingExtendedEbgp" json:"update_error_handling_extended_ebgp,omitempty"`
	// Is extended error-handling for IBGP enabled
	UpdateErrorHandlingExtendedIbgp bool `protobuf:"varint,53,opt,name=update_error_handling_extended_ibgp,json=updateErrorHandlingExtendedIbgp" json:"update_error_handling_extended_ibgp,omitempty"`
	// Malformed messages count
	UpdateMalformedMessageCount uint32 `protobuf:"varint,54,opt,name=update_malformed_message_count,json=updateMalformedMessageCount" json:"update_malformed_message_count,omitempty"`
	// Count of neighbors that received malformed messages
	UpdateMalformedNeighborCount uint32 `protobuf:"varint,55,opt,name=update_malformed_neighbor_count,json=updateMalformedNeighborCount" json:"update_malformed_neighbor_count,omitempty"`
	// Last malformed messages received time: time elapsed since 00:00:00 UTC, January 1, 1970
	LastUpdateMalformedTimestamp *BgpTimespec `protobuf:"bytes,56,opt,name=last_update_malformed_timestamp,json=lastUpdateMalformedTimestamp" json:"last_update_malformed_timestamp,omitempty"`
	// Time since last malformed messages received event (in seconds)
	LastUpdateMalformedAge uint32 `protobuf:"varint,57,opt,name=last_update_malformed_age,json=lastUpdateMalformedAge" json:"last_update_malformed_age,omitempty"`
}

func (m *BgpUpderrProcBag) Reset()                    { *m = BgpUpderrProcBag{} }
func (m *BgpUpderrProcBag) String() string            { return proto.CompactTextString(m) }
func (*BgpUpderrProcBag) ProtoMessage()               {}
func (*BgpUpderrProcBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BgpUpderrProcBag) GetUpdateErrorHandlingBasicEbgp() bool {
	if m != nil {
		return m.UpdateErrorHandlingBasicEbgp
	}
	return false
}

func (m *BgpUpderrProcBag) GetUpdateErrorHandlingBasicIbgp() bool {
	if m != nil {
		return m.UpdateErrorHandlingBasicIbgp
	}
	return false
}

func (m *BgpUpderrProcBag) GetUpdateErrorHandlingExtendedEbgp() bool {
	if m != nil {
		return m.UpdateErrorHandlingExtendedEbgp
	}
	return false
}

func (m *BgpUpderrProcBag) GetUpdateErrorHandlingExtendedIbgp() bool {
	if m != nil {
		return m.UpdateErrorHandlingExtendedIbgp
	}
	return false
}

func (m *BgpUpderrProcBag) GetUpdateMalformedMessageCount() uint32 {
	if m != nil {
		return m.UpdateMalformedMessageCount
	}
	return 0
}

func (m *BgpUpderrProcBag) GetUpdateMalformedNeighborCount() uint32 {
	if m != nil {
		return m.UpdateMalformedNeighborCount
	}
	return 0
}

func (m *BgpUpderrProcBag) GetLastUpdateMalformedTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateMalformedTimestamp
	}
	return nil
}

func (m *BgpUpderrProcBag) GetLastUpdateMalformedAge() uint32 {
	if m != nil {
		return m.LastUpdateMalformedAge
	}
	return 0
}

type BgpTimespec struct {
	// Seconds part of time value
	Seconds uint32 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Nanoseconds part of time value
	Nanoseconds uint32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *BgpTimespec) Reset()                    { *m = BgpTimespec{} }
func (m *BgpTimespec) String() string            { return proto.CompactTextString(m) }
func (*BgpTimespec) ProtoMessage()               {}
func (*BgpTimespec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BgpTimespec) GetSeconds() uint32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *BgpTimespec) GetNanoseconds() uint32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

func init() {
	proto.RegisterType((*BgpUpderrProcBag_KEYS)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.update_inbound_error_process.bgp_upderr_proc_bag_KEYS")
	proto.RegisterType((*BgpUpderrProcBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.update_inbound_error_process.bgp_upderr_proc_bag")
	proto.RegisterType((*BgpTimespec)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.update_inbound_error_process.bgp_timespec")
}

func init() { proto.RegisterFile("bgp_upderr_proc_bag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcb, 0x6e, 0xd4, 0x30,
	0x14, 0x86, 0x15, 0x24, 0x6e, 0x6e, 0x67, 0x13, 0x24, 0x94, 0x8a, 0x11, 0x13, 0x4d, 0x37, 0xb3,
	0xca, 0xa2, 0x2d, 0x97, 0xae, 0x10, 0x54, 0x41, 0xdc, 0xda, 0x45, 0x80, 0x05, 0x1b, 0x8e, 0x7c,
	0x39, 0xb8, 0x96, 0x26, 0xb6, 0x65, 0x7b, 0xaa, 0xbe, 0x17, 0x7b, 0x9e, 0x0d, 0xd9, 0x4e, 0x46,
	0x85, 0x46, 0x94, 0x4d, 0x77, 0x8e, 0xcf, 0xa7, 0xef, 0xff, 0x23, 0x1d, 0x93, 0x3d, 0x26, 0x2d,
	0x6c, 0xac, 0x40, 0xe7, 0xc0, 0x3a, 0xc3, 0x81, 0x51, 0xd9, 0x58, 0x67, 0x82, 0x29, 0xbf, 0x73,
	0xe5, 0xb9, 0x01, 0x65, 0x3c, 0x5c, 0x3a, 0x50, 0xf6, 0xe2, 0x08, 0x22, 0x6c, 0x2c, 0xba, 0x86,
	0x49, 0xdb, 0x28, 0xed, 0x03, 0xd5, 0x1c, 0xfd, 0xf6, 0xb4, 0x3d, 0x00, 0xe5, 0x41, 0x5d, 0x60,
	0xb3, 0xb1, 0x82, 0x06, 0x04, 0xa5, 0x99, 0xd9, 0x68, 0x01, 0xe8, 0x9c, 0xc9, 0x31, 0xe8, 0xfd,
	0xf2, 0x15, 0xa9, 0x26, 0xc2, 0xe1, 0x63, 0xfb, 0xed, 0x73, 0xb9, 0x4f, 0x66, 0x5b, 0x97, 0xa6,
	0x3d, 0x56, 0x45, 0x5d, 0xac, 0x1e, 0x76, 0xbb, 0xe3, 0xe5, 0x19, 0xed, 0x71, 0xf9, 0xeb, 0x2e,
	0x79, 0x34, 0x61, 0x28, 0xdf, 0x92, 0x7a, 0x08, 0xce, 0x81, 0xe7, 0x54, 0x8b, 0xb5, 0xd2, 0x12,
	0x18, 0xf5, 0x8a, 0x03, 0x32, 0x69, 0xab, 0x83, 0xba, 0x58, 0x3d, 0xe8, 0xe6, 0x99, 0x6b, 0x23,
	0xf6, 0x6e, 0xa0, 0xde, 0x44, 0xa8, 0x65, 0xd2, 0xde, 0xe4, 0x51, 0xd1, 0x73, 0xf8, 0x6f, 0xcf,
	0xfb, 0xe8, 0xf9, 0x44, 0xf6, 0xa7, 0x3d, 0x78, 0x19, 0x50, 0x0b, 0x14, 0xb9, 0xd2, 0x51, 0x52,
	0x2d, 0x26, 0x54, 0xed, 0xc0, 0xb5, 0xff, 0x67, 0x4b, 0xc5, 0x9e, 0xdd, 0x68, 0x4b, 0xdd, 0x4e,
	0xc8, 0xd3, 0xc1, 0xd6, 0xd3, 0xf5, 0x0f, 0xe3, 0x7a, 0x14, 0xd0, 0xa3, 0xf7, 0x54, 0x22, 0x70,
	0xb3, 0xd1, 0xa1, 0x7a, 0x5e, 0x17, 0xab, 0x59, 0xf7, 0x24, 0x53, 0xa7, 0x23, 0x74, 0x9a, 0x99,
	0x93, 0x88, 0x94, 0x2d, 0x59, 0x5c, 0x93, 0x68, 0x54, 0xf2, 0x9c, 0x19, 0x37, 0x58, 0x5e, 0x24,
	0xcb, 0xfc, 0x2f, 0xcb, 0xd9, 0x00, 0x65, 0xcd, 0xcf, 0x82, 0x2c, 0xd6, 0xd4, 0x07, 0xb8, 0x26,
	0x0b, 0xaa, 0x47, 0x1f, 0x68, 0x6f, 0xab, 0x97, 0x75, 0xb1, 0xda, 0x39, 0x58, 0x37, 0xb7, 0xbb,
	0x9b, 0xd1, 0x91, 0x43, 0x2d, 0xf2, 0x6e, 0x1e, 0x4b, 0x7d, 0xfd, 0xb3, 0xf9, 0x97, 0xb1, 0x51,
	0x79, 0x4c, 0xf6, 0xa6, 0x4b, 0x53, 0x89, 0xd5, 0x71, 0xfa, 0xed, 0xc7, 0x13, 0x82, 0xd7, 0x12,
	0x97, 0x1f, 0xc8, 0xee, 0xd5, 0xa0, 0xb2, 0x22, 0xf7, 0x3d, 0x72, 0xa3, 0x85, 0x4f, 0xfb, 0x3e,
	0xeb, 0xc6, 0xcf, 0xb2, 0x26, 0x3b, 0x9a, 0x6a, 0x33, 0x4e, 0xef, 0xa4, 0xe9, 0xd5, 0x2b, 0x76,
	0x2f, 0x3d, 0xda, 0xc3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x29, 0x39, 0xd1, 0xd1, 0x03,
	0x00, 0x00,
}
