// Code generated by protoc-gen-go.
// source: bgp_msglog_nbr_bag.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_standby_vrfs_vrf_message_logs_message_log is a generated protocol buffer package.

It is generated from these files:
	bgp_msglog_nbr_bag.proto

It has these top-level messages:
	BgpMsglogNbrBag_KEYS
	BgpMsglogNbrBag
	BgpTimespec
	BgpNbrMsg_
*/
package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_standby_vrfs_vrf_message_logs_message_log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BGP Message logging Neighbor information
type BgpMsglogNbrBag_KEYS struct {
	InstanceName    string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
	VrfName         string `protobuf:"bytes,2,opt,name=vrf_name,json=vrfName" json:"vrf_name,omitempty"`
	NeighborAddress string `protobuf:"bytes,3,opt,name=neighbor_address,json=neighborAddress" json:"neighbor_address,omitempty"`
	Direction       uint32 `protobuf:"varint,4,opt,name=direction" json:"direction,omitempty"`
}

func (m *BgpMsglogNbrBag_KEYS) Reset()                    { *m = BgpMsglogNbrBag_KEYS{} }
func (m *BgpMsglogNbrBag_KEYS) String() string            { return proto.CompactTextString(m) }
func (*BgpMsglogNbrBag_KEYS) ProtoMessage()               {}
func (*BgpMsglogNbrBag_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BgpMsglogNbrBag_KEYS) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *BgpMsglogNbrBag_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *BgpMsglogNbrBag_KEYS) GetNeighborAddress() string {
	if m != nil {
		return m.NeighborAddress
	}
	return ""
}

func (m *BgpMsglogNbrBag_KEYS) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type BgpMsglogNbrBag struct {
	// Array of Neighbor Messages in one direction
	NeighborMessages []*BgpNbrMsg_ `protobuf:"bytes,50,rep,name=neighbor_messages,json=neighborMessages" json:"neighbor_messages,omitempty"`
}

func (m *BgpMsglogNbrBag) Reset()                    { *m = BgpMsglogNbrBag{} }
func (m *BgpMsglogNbrBag) String() string            { return proto.CompactTextString(m) }
func (*BgpMsglogNbrBag) ProtoMessage()               {}
func (*BgpMsglogNbrBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BgpMsglogNbrBag) GetNeighborMessages() []*BgpNbrMsg_ {
	if m != nil {
		return m.NeighborMessages
	}
	return nil
}

type BgpTimespec struct {
	// Seconds part of time value
	Seconds uint32 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Nanoseconds part of time value
	Nanoseconds uint32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *BgpTimespec) Reset()                    { *m = BgpTimespec{} }
func (m *BgpTimespec) String() string            { return proto.CompactTextString(m) }
func (*BgpTimespec) ProtoMessage()               {}
func (*BgpTimespec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BgpTimespec) GetSeconds() uint32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *BgpTimespec) GetNanoseconds() uint32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

type BgpNbrMsg_ struct {
	// Type of messages Received
	MessageTypeReceived uint32 `protobuf:"varint,1,opt,name=message_type_received,json=messageTypeReceived" json:"message_type_received,omitempty"`
	// Total logged messages count
	TotalLoggedMessageCount uint32 `protobuf:"varint,2,opt,name=total_logged_message_count,json=totalLoggedMessageCount" json:"total_logged_message_count,omitempty"`
	// message received time: time elapsed since 00:00:00 UTC, January 1, 1970
	MessageTimestamp *BgpTimespec `protobuf:"bytes,3,opt,name=message_timestamp,json=messageTimestamp" json:"message_timestamp,omitempty"`
	// Message data length
	MessageDataLength uint32 `protobuf:"varint,4,opt,name=message_data_length,json=messageDataLength" json:"message_data_length,omitempty"`
	// Raw Message data in binary format
	LoggedMessageData []uint32 `protobuf:"varint,5,rep,packed,name=logged_message_data,json=loggedMessageData" json:"logged_message_data,omitempty"`
}

func (m *BgpNbrMsg_) Reset()                    { *m = BgpNbrMsg_{} }
func (m *BgpNbrMsg_) String() string            { return proto.CompactTextString(m) }
func (*BgpNbrMsg_) ProtoMessage()               {}
func (*BgpNbrMsg_) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BgpNbrMsg_) GetMessageTypeReceived() uint32 {
	if m != nil {
		return m.MessageTypeReceived
	}
	return 0
}

func (m *BgpNbrMsg_) GetTotalLoggedMessageCount() uint32 {
	if m != nil {
		return m.TotalLoggedMessageCount
	}
	return 0
}

func (m *BgpNbrMsg_) GetMessageTimestamp() *BgpTimespec {
	if m != nil {
		return m.MessageTimestamp
	}
	return nil
}

func (m *BgpNbrMsg_) GetMessageDataLength() uint32 {
	if m != nil {
		return m.MessageDataLength
	}
	return 0
}

func (m *BgpNbrMsg_) GetLoggedMessageData() []uint32 {
	if m != nil {
		return m.LoggedMessageData
	}
	return nil
}

func init() {
	proto.RegisterType((*BgpMsglogNbrBag_KEYS)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.message_logs.message_log.bgp_msglog_nbr_bag_KEYS")
	proto.RegisterType((*BgpMsglogNbrBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.message_logs.message_log.bgp_msglog_nbr_bag")
	proto.RegisterType((*BgpTimespec)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.message_logs.message_log.bgp_timespec")
	proto.RegisterType((*BgpNbrMsg_)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.message_logs.message_log.bgp_nbr_msg_")
}

func init() { proto.RegisterFile("bgp_msglog_nbr_bag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xb1, 0x8e, 0xd4, 0x30,
	0x10, 0x55, 0x6e, 0x81, 0xe3, 0x7c, 0xb7, 0xe2, 0x30, 0x42, 0x17, 0x10, 0x45, 0xb4, 0x34, 0x4b,
	0x93, 0x62, 0xa1, 0xa3, 0x42, 0x40, 0x03, 0x07, 0x45, 0xa0, 0xa1, 0x1a, 0x39, 0xf1, 0xac, 0xcf,
	0x52, 0x62, 0x5b, 0x1e, 0x13, 0xb1, 0x25, 0x5f, 0x82, 0xc4, 0x47, 0xf0, 0x7d, 0xc8, 0xde, 0x38,
	0xac, 0xb8, 0x7e, 0x9b, 0xc4, 0x9e, 0xf7, 0x3c, 0xf3, 0xde, 0x4b, 0xcc, 0xca, 0x56, 0x39, 0x18,
	0x48, 0xf5, 0x56, 0x81, 0x69, 0x3d, 0xb4, 0x42, 0xd5, 0xce, 0xdb, 0x60, 0xb9, 0xec, 0x34, 0x75,
	0x16, 0xb4, 0x25, 0xf8, 0xe1, 0x41, 0xbb, 0xf1, 0x15, 0x44, 0xae, 0x75, 0xe8, 0xeb, 0x56, 0xb9,
	0x5a, 0x1b, 0x0a, 0xc2, 0x74, 0x48, 0xf3, 0x6a, 0x5e, 0x40, 0x7c, 0xc9, 0x76, 0x57, 0x8f, 0x7e,
	0x4b, 0xf1, 0x51, 0x0f, 0x48, 0x24, 0x14, 0x42, 0x6f, 0x15, 0x1d, 0x6e, 0x56, 0xbf, 0x0b, 0x76,
	0x75, 0x5b, 0x02, 0x7c, 0x7c, 0xff, 0xed, 0x0b, 0x7f, 0xce, 0x96, 0x73, 0x47, 0x23, 0x06, 0x2c,
	0x8b, 0xaa, 0x58, 0x9f, 0x35, 0x17, 0xb9, 0xf8, 0x59, 0x0c, 0xc8, 0x9f, 0xb0, 0xfb, 0xa3, 0xdf,
	0xee, 0xf1, 0x93, 0x84, 0x9f, 0x8e, 0x7e, 0x9b, 0xa0, 0x17, 0xec, 0xd2, 0xa0, 0x56, 0x37, 0xad,
	0xf5, 0x20, 0xa4, 0xf4, 0x48, 0x54, 0x2e, 0x12, 0xe5, 0x41, 0xae, 0xbf, 0xd9, 0x97, 0xf9, 0x33,
	0x76, 0x26, 0xb5, 0xc7, 0x2e, 0x68, 0x6b, 0xca, 0x3b, 0x55, 0xb1, 0x5e, 0x36, 0xff, 0x0a, 0xab,
	0x3f, 0x05, 0xe3, 0xb7, 0x45, 0xf2, 0x5f, 0x05, 0x7b, 0x38, 0x0f, 0x98, 0x4c, 0x51, 0xb9, 0xa9,
	0x16, 0xeb, 0xf3, 0x8d, 0xaf, 0x8f, 0x11, 0x5f, 0xec, 0x94, 0xe4, 0x0c, 0xa4, 0xa0, 0x99, 0xdd,
	0x7e, 0x9a, 0xb4, 0xac, 0x3e, 0xb0, 0x8b, 0xc8, 0x08, 0x7a, 0x40, 0x72, 0xd8, 0xf1, 0x92, 0x9d,
	0x12, 0x76, 0xd6, 0x48, 0x4a, 0x59, 0x2e, 0x9b, 0xbc, 0xe5, 0x15, 0x3b, 0x37, 0xc2, 0xd8, 0x8c,
	0x9e, 0x24, 0xf4, 0xb0, 0xb4, 0xfa, 0xb9, 0xd8, 0x37, 0xcb, 0xe3, 0xf8, 0x86, 0x3d, 0xce, 0x52,
	0xc2, 0xce, 0x21, 0x78, 0xec, 0x50, 0x8f, 0x28, 0xa7, 0xd6, 0x8f, 0x26, 0xf0, 0xeb, 0xce, 0x61,
	0x33, 0x41, 0xfc, 0x35, 0x7b, 0x1a, 0x6c, 0x10, 0x7d, 0x14, 0xaf, 0x50, 0xe6, 0xd4, 0xa0, 0xb3,
	0xdf, 0x4d, 0x98, 0xa6, 0x5e, 0x25, 0xc6, 0x75, 0x22, 0x4c, 0x4e, 0xde, 0x46, 0x38, 0xe5, 0x3d,
	0x4f, 0x8c, 0x96, 0x82, 0x18, 0x5c, 0xfa, 0xa2, 0x47, 0xcd, 0x3b, 0xa7, 0xd9, 0x5c, 0x66, 0x87,
	0x59, 0x0b, 0xaf, 0x59, 0x76, 0x0d, 0x52, 0x04, 0x01, 0x3d, 0x1a, 0x15, 0x6e, 0xa6, 0x1f, 0x2a,
	0x6b, 0x7f, 0x27, 0x82, 0xb8, 0x4e, 0x40, 0xe4, 0xff, 0x17, 0x44, 0x3c, 0x56, 0xde, 0xad, 0x16,
	0x91, 0xdf, 0x1f, 0x46, 0x10, 0x4f, 0xb5, 0xf7, 0xd2, 0xd5, 0x7c, 0xf9, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x73, 0x1f, 0x65, 0x0c, 0xb6, 0x03, 0x00, 0x00,
}
