// Code generated by protoc-gen-go.
// source: bgp_upderr_vrf_bag.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_default_vrf_update_inbound_error_vrf is a generated protocol buffer package.

It is generated from these files:
	bgp_upderr_vrf_bag.proto

It has these top-level messages:
	BgpUpderrVrfBag_KEYS
	BgpUpderrVrfBag
	BgpTimespec
*/
package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_default_vrf_update_inbound_error_vrf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BGP Update error-handling VRF information
type BgpUpderrVrfBag_KEYS struct {
	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
}

func (m *BgpUpderrVrfBag_KEYS) Reset()                    { *m = BgpUpderrVrfBag_KEYS{} }
func (m *BgpUpderrVrfBag_KEYS) String() string            { return proto.CompactTextString(m) }
func (*BgpUpderrVrfBag_KEYS) ProtoMessage()               {}
func (*BgpUpderrVrfBag_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BgpUpderrVrfBag_KEYS) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

type BgpUpderrVrfBag struct {
	// VRF Name
	UpdateVrfName string `protobuf:"bytes,50,opt,name=update_vrf_name,json=updateVrfName" json:"update_vrf_name,omitempty"`
	// Malformed messages count
	UpdateMalformedMessageCount uint32 `protobuf:"varint,51,opt,name=update_malformed_message_count,json=updateMalformedMessageCount" json:"update_malformed_message_count,omitempty"`
	// Count of neighbors that received malformed messages
	UpdateMalformedNeighborCount uint32 `protobuf:"varint,52,opt,name=update_malformed_neighbor_count,json=updateMalformedNeighborCount" json:"update_malformed_neighbor_count,omitempty"`
	// Last malformed messages received time: time elapsed since 00:00:00 UTC, January 1, 1970
	LastUpdateMalformedTimestamp *BgpTimespec `protobuf:"bytes,53,opt,name=last_update_malformed_timestamp,json=lastUpdateMalformedTimestamp" json:"last_update_malformed_timestamp,omitempty"`
	// Time since last malformed messages received event (in seconds)
	LastUpdateMalformedAge uint32 `protobuf:"varint,54,opt,name=last_update_malformed_age,json=lastUpdateMalformedAge" json:"last_update_malformed_age,omitempty"`
}

func (m *BgpUpderrVrfBag) Reset()                    { *m = BgpUpderrVrfBag{} }
func (m *BgpUpderrVrfBag) String() string            { return proto.CompactTextString(m) }
func (*BgpUpderrVrfBag) ProtoMessage()               {}
func (*BgpUpderrVrfBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BgpUpderrVrfBag) GetUpdateVrfName() string {
	if m != nil {
		return m.UpdateVrfName
	}
	return ""
}

func (m *BgpUpderrVrfBag) GetUpdateMalformedMessageCount() uint32 {
	if m != nil {
		return m.UpdateMalformedMessageCount
	}
	return 0
}

func (m *BgpUpderrVrfBag) GetUpdateMalformedNeighborCount() uint32 {
	if m != nil {
		return m.UpdateMalformedNeighborCount
	}
	return 0
}

func (m *BgpUpderrVrfBag) GetLastUpdateMalformedTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateMalformedTimestamp
	}
	return nil
}

func (m *BgpUpderrVrfBag) GetLastUpdateMalformedAge() uint32 {
	if m != nil {
		return m.LastUpdateMalformedAge
	}
	return 0
}

type BgpTimespec struct {
	// Seconds part of time value
	Seconds uint32 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Nanoseconds part of time value
	Nanoseconds uint32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *BgpTimespec) Reset()                    { *m = BgpTimespec{} }
func (m *BgpTimespec) String() string            { return proto.CompactTextString(m) }
func (*BgpTimespec) ProtoMessage()               {}
func (*BgpTimespec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BgpTimespec) GetSeconds() uint32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *BgpTimespec) GetNanoseconds() uint32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

func init() {
	proto.RegisterType((*BgpUpderrVrfBag_KEYS)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.default_vrf.update_inbound_error_vrf.bgp_upderr_vrf_bag_KEYS")
	proto.RegisterType((*BgpUpderrVrfBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.default_vrf.update_inbound_error_vrf.bgp_upderr_vrf_bag")
	proto.RegisterType((*BgpTimespec)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.default_vrf.update_inbound_error_vrf.bgp_timespec")
}

func init() { proto.RegisterFile("bgp_upderr_vrf_bag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xe9, 0xf7, 0x0b, 0x8a, 0xd9, 0x8a, 0x90, 0x83, 0x56, 0x1c, 0xae, 0x4c, 0x90, 0x9d,
	0x7a, 0xd8, 0xa6, 0xe0, 0x45, 0x90, 0xb1, 0x8b, 0xb2, 0x1d, 0xea, 0x0f, 0xf0, 0x14, 0xd2, 0xf6,
	0x6d, 0x0d, 0xac, 0x49, 0x48, 0xd2, 0xe1, 0xff, 0xe6, 0xc9, 0xff, 0x4c, 0x92, 0xb6, 0x63, 0xda,
	0x9d, 0xbd, 0xa5, 0x4f, 0x9e, 0xf7, 0xf3, 0x3c, 0xe1, 0x2d, 0x0a, 0x92, 0x42, 0x92, 0x4a, 0x66,
	0xa0, 0x14, 0xd9, 0xa8, 0x9c, 0x24, 0xb4, 0x88, 0xa4, 0x12, 0x46, 0xe0, 0x3c, 0x65, 0x3a, 0x15,
	0x84, 0x09, 0x4d, 0x3e, 0x14, 0x61, 0x72, 0x33, 0x23, 0xd6, 0x2b, 0x24, 0xa8, 0x28, 0x29, 0x64,
	0xc4, 0xb8, 0x36, 0x94, 0xa7, 0xa0, 0xb7, 0xa7, 0xed, 0x81, 0xd0, 0xd4, 0xb0, 0x0d, 0x44, 0x19,
	0xe4, 0xb4, 0x5a, 0x1b, 0x0b, 0x8e, 0x2a, 0x99, 0x51, 0x03, 0x84, 0xf1, 0x44, 0x54, 0x3c, 0x23,
	0xa0, 0x94, 0x70, 0x89, 0xa3, 0x3b, 0x74, 0xda, 0xed, 0x40, 0x1e, 0x17, 0x6f, 0x4f, 0xf8, 0x12,
	0xf9, 0x5b, 0x24, 0xa7, 0x25, 0x04, 0x5e, 0xe8, 0x8d, 0x8f, 0xe2, 0x7e, 0x2b, 0xae, 0x68, 0x09,
	0xa3, 0xaf, 0xff, 0x08, 0x77, 0x01, 0xf8, 0x0a, 0x1d, 0x37, 0x91, 0x56, 0x71, 0xd3, 0x13, 0x37,
	0xed, 0xd7, 0xf2, 0xab, 0xca, 0xed, 0x38, 0x9e, 0xa3, 0x8b, 0xc6, 0x57, 0xd2, 0x75, 0x2e, 0x54,
	0x09, 0x19, 0x29, 0x41, 0x6b, 0x5a, 0x00, 0x49, 0x45, 0xc5, 0x4d, 0x30, 0x0d, 0xbd, 0xb1, 0x1f,
	0x9f, 0xd7, 0xae, 0x65, 0x6b, 0x5a, 0xd6, 0x9e, 0xb9, 0xb5, 0xe0, 0x05, 0x1a, 0x76, 0x20, 0x1c,
	0x58, 0xf1, 0x9e, 0x08, 0xd5, 0x50, 0x66, 0x8e, 0x32, 0xf8, 0x45, 0x59, 0x35, 0xa6, 0x1a, 0xf3,
	0xe9, 0xa1, 0xe1, 0x9a, 0x6a, 0x43, 0x3a, 0x30, 0xc3, 0x4a, 0xd0, 0x86, 0x96, 0x32, 0xb8, 0x0e,
	0xbd, 0x71, 0x6f, 0x62, 0xa2, 0xbf, 0xd9, 0x8e, 0x65, 0xd5, 0xe1, 0x12, 0xd2, 0x78, 0x60, 0xcb,
	0xbd, 0xfc, 0x7c, 0xc1, 0x73, 0xdb, 0x0c, 0xdf, 0xa2, 0xb3, 0xfd, 0xe5, 0x69, 0x01, 0xc1, 0x8d,
	0x7b, 0xfe, 0xc9, 0x1e, 0xc0, 0x7d, 0x01, 0xa3, 0x07, 0xd4, 0xdf, 0x0d, 0xc2, 0x01, 0x3a, 0xd4,
	0x90, 0x0a, 0x9e, 0x69, 0xb7, 0x72, 0x3f, 0x6e, 0x3f, 0x71, 0x88, 0x7a, 0x9c, 0x72, 0xd1, 0xde,
	0xfe, 0x73, 0xb7, 0xbb, 0x52, 0x72, 0xe0, 0x7e, 0xdf, 0xe9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x7d, 0x2f, 0xb1, 0xf8, 0xda, 0x02, 0x00, 0x00,
}
