// Code generated by protoc-gen-go.
// source: bgp_updgen_nbr_bag.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_vrfs_vrf_afs_af_update_generation_neighbors_update_generation_neighbor is a generated protocol buffer package.

It is generated from these files:
	bgp_updgen_nbr_bag.proto

It has these top-level messages:
	BgpUpdgenNbrBag_KEYS
	BgpUpdgenNbrBag
	BgpTimespec
	IPV4TunnelAddressType
	IPV4MDTAddressType
	RTConstraintAddressType
	IPV6AddressType
	BgpIpv4SrpolicyAddrT
	BgpIpv6SrpolicyAddrT
	BgpL2VpnAddrT
	L2VPNEVPNAddressType
	BgpL2VpnMspwAddrT
	IPV6MVPNAddressType
	IPV4MVPNAddressType
	LS_LSAddressType
	IPv4FlowspecAddressType
	IPv6FlowspecAddressType
	BgpAddrtype
	BgpUpdgenStatsBag
*/
package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_vrfs_vrf_afs_af_update_generation_neighbors_update_generation_neighbor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BGP Update generation Neighbor information
type BgpUpdgenNbrBag_KEYS struct {
	InstanceName     string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
	VrfName          string `protobuf:"bytes,2,opt,name=vrf_name,json=vrfName" json:"vrf_name,omitempty"`
	AfName           string `protobuf:"bytes,3,opt,name=af_name,json=afName" json:"af_name,omitempty"`
	UpdateGroupIndex uint32 `protobuf:"varint,4,opt,name=update_group_index,json=updateGroupIndex" json:"update_group_index,omitempty"`
	SubGroupIndex    uint32 `protobuf:"varint,5,opt,name=sub_group_index,json=subGroupIndex" json:"sub_group_index,omitempty"`
	SubGroupId       uint32 `protobuf:"varint,6,opt,name=sub_group_id,json=subGroupId" json:"sub_group_id,omitempty"`
	FilterGroupIndex uint32 `protobuf:"varint,7,opt,name=filter_group_index,json=filterGroupIndex" json:"filter_group_index,omitempty"`
	NeighborAddress  string `protobuf:"bytes,8,opt,name=neighbor_address,json=neighborAddress" json:"neighbor_address,omitempty"`
}

func (m *BgpUpdgenNbrBag_KEYS) Reset()                    { *m = BgpUpdgenNbrBag_KEYS{} }
func (m *BgpUpdgenNbrBag_KEYS) String() string            { return proto.CompactTextString(m) }
func (*BgpUpdgenNbrBag_KEYS) ProtoMessage()               {}
func (*BgpUpdgenNbrBag_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BgpUpdgenNbrBag_KEYS) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *BgpUpdgenNbrBag_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *BgpUpdgenNbrBag_KEYS) GetAfName() string {
	if m != nil {
		return m.AfName
	}
	return ""
}

func (m *BgpUpdgenNbrBag_KEYS) GetUpdateGroupIndex() uint32 {
	if m != nil {
		return m.UpdateGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag_KEYS) GetSubGroupIndex() uint32 {
	if m != nil {
		return m.SubGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag_KEYS) GetSubGroupId() uint32 {
	if m != nil {
		return m.SubGroupId
	}
	return 0
}

func (m *BgpUpdgenNbrBag_KEYS) GetFilterGroupIndex() uint32 {
	if m != nil {
		return m.FilterGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag_KEYS) GetNeighborAddress() string {
	if m != nil {
		return m.NeighborAddress
	}
	return ""
}

type BgpUpdgenNbrBag struct {
	// ProcessID
	ProcessId uint32 `protobuf:"varint,50,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	// VRF Name
	UpdateVrfName string `protobuf:"bytes,51,opt,name=update_vrf_name,json=updateVrfName" json:"update_vrf_name,omitempty"`
	// Address family identifier
	UpdateGroupAfName string `protobuf:"bytes,52,opt,name=update_group_af_name,json=updateGroupAfName" json:"update_group_af_name,omitempty"`
	// Neighbor address
	UpdateNeighborAddress *BgpAddrtype `protobuf:"bytes,53,opt,name=update_neighbor_address,json=updateNeighborAddress" json:"update_neighbor_address,omitempty"`
	// Filter-group index
	UpdateFilterGroupIndex uint32 `protobuf:"varint,54,opt,name=update_filter_group_index,json=updateFilterGroupIndex" json:"update_filter_group_index,omitempty"`
	// Refresh Filter-group index
	RefreshFilterGroupIndex uint32 `protobuf:"varint,55,opt,name=refresh_filter_group_index,json=refreshFilterGroupIndex" json:"refresh_filter_group_index,omitempty"`
	// Sub-group index
	SubGroupIndex uint32 `protobuf:"varint,56,opt,name=sub_group_index,json=subGroupIndex" json:"sub_group_index,omitempty"`
	// Refresh Sub-group index
	RefreshSubGroupIndex uint32 `protobuf:"varint,57,opt,name=refresh_sub_group_index,json=refreshSubGroupIndex" json:"refresh_sub_group_index,omitempty"`
	// Refresh sub-group ID
	RefreshSubGroupId uint32 `protobuf:"varint,58,opt,name=refresh_sub_group_id,json=refreshSubGroupId" json:"refresh_sub_group_id,omitempty"`
	// Update-group index
	UpdateGroupIndex uint32 `protobuf:"varint,59,opt,name=update_group_index,json=updateGroupIndex" json:"update_group_index,omitempty"`
	// Main table version
	UpdateMainTableVersion uint32 `protobuf:"varint,60,opt,name=update_main_table_version,json=updateMainTableVersion" json:"update_main_table_version,omitempty"`
	// VRF Table RIB version
	UpdateVrfTableRibVersion uint32 `protobuf:"varint,61,opt,name=update_vrf_table_rib_version,json=updateVrfTableRibVersion" json:"update_vrf_table_rib_version,omitempty"`
	// OutQueue messages
	UpdateOutQueueMessages uint32 `protobuf:"varint,62,opt,name=update_out_queue_messages,json=updateOutQueueMessages" json:"update_out_queue_messages,omitempty"`
	// OutQueue size
	UpdateOutQueueSize uint32 `protobuf:"varint,63,opt,name=update_out_queue_size,json=updateOutQueueSize" json:"update_out_queue_size,omitempty"`
	// Refresh OutQueue messages
	RefreshUpdateOutQueueMessages uint32 `protobuf:"varint,64,opt,name=refresh_update_out_queue_messages,json=refreshUpdateOutQueueMessages" json:"refresh_update_out_queue_messages,omitempty"`
	// Refresh OutQueue size
	RefreshUpdateOutQueueSize uint32 `protobuf:"varint,65,opt,name=refresh_update_out_queue_size,json=refreshUpdateOutQueueSize" json:"refresh_update_out_queue_size,omitempty"`
	// Filter-group messages
	UpdateFilterGroupMessages uint32 `protobuf:"varint,66,opt,name=update_filter_group_messages,json=updateFilterGroupMessages" json:"update_filter_group_messages,omitempty"`
	// Last added time
	LastSubGroupAddTimestamp *BgpTimespec `protobuf:"bytes,67,opt,name=last_sub_group_add_timestamp,json=lastSubGroupAddTimestamp" json:"last_sub_group_add_timestamp,omitempty"`
	// Last removed time
	LastSubGroupRemoveTimestamp *BgpTimespec `protobuf:"bytes,68,opt,name=last_sub_group_remove_timestamp,json=lastSubGroupRemoveTimestamp" json:"last_sub_group_remove_timestamp,omitempty"`
	// Last added time
	LastFilterGroupAddTimestamp *BgpTimespec `protobuf:"bytes,69,opt,name=last_filter_group_add_timestamp,json=lastFilterGroupAddTimestamp" json:"last_filter_group_add_timestamp,omitempty"`
	// Last removed time
	LastFilterGroupRemoveTimestamp *BgpTimespec `protobuf:"bytes,70,opt,name=last_filter_group_remove_timestamp,json=lastFilterGroupRemoveTimestamp" json:"last_filter_group_remove_timestamp,omitempty"`
	// Version
	Version uint32 `protobuf:"varint,71,opt,name=version" json:"version,omitempty"`
	// Pending target version
	PendingTargetVersion uint32 `protobuf:"varint,72,opt,name=pending_target_version,json=pendingTargetVersion" json:"pending_target_version,omitempty"`
	// Resume version
	NextResumeVersion uint32 `protobuf:"varint,73,opt,name=next_resume_version,json=nextResumeVersion" json:"next_resume_version,omitempty"`
	// Ack version
	AckVersion uint32 `protobuf:"varint,74,opt,name=ack_version,json=ackVersion" json:"ack_version,omitempty"`
	// Synced ack version
	SyncedAckVersion uint32 `protobuf:"varint,75,opt,name=synced_ack_version,json=syncedAckVersion" json:"synced_ack_version,omitempty"`
	// Outstanding version count
	OutstandingVersionCount uint32 `protobuf:"varint,76,opt,name=outstanding_version_count,json=outstandingVersionCount" json:"outstanding_version_count,omitempty"`
	// Refresh version
	UpdateRefreshVersion uint32 `protobuf:"varint,77,opt,name=update_refresh_version,json=updateRefreshVersion" json:"update_refresh_version,omitempty"`
	// Requested refresh target version
	RefreshRequestedTargetVersion uint32 `protobuf:"varint,78,opt,name=refresh_requested_target_version,json=refreshRequestedTargetVersion" json:"refresh_requested_target_version,omitempty"`
	// Refresh target version
	UpdateRefreshTargetVersion uint32 `protobuf:"varint,79,opt,name=update_refresh_target_version,json=updateRefreshTargetVersion" json:"update_refresh_target_version,omitempty"`
	// Pending refresh target version
	RefreshPendingTargetVersion uint32 `protobuf:"varint,80,opt,name=refresh_pending_target_version,json=refreshPendingTargetVersion" json:"refresh_pending_target_version,omitempty"`
	// Refresh resume version
	RefreshNextResumeVersion uint32 `protobuf:"varint,81,opt,name=refresh_next_resume_version,json=refreshNextResumeVersion" json:"refresh_next_resume_version,omitempty"`
	// Refresh Ack version
	RefreshAckVersion uint32 `protobuf:"varint,82,opt,name=refresh_ack_version,json=refreshAckVersion" json:"refresh_ack_version,omitempty"`
	// First default-origination time
	FirstDefaultOriginateTimestamp *BgpTimespec `protobuf:"bytes,83,opt,name=first_default_originate_timestamp,json=firstDefaultOriginateTimestamp" json:"first_default_originate_timestamp,omitempty"`
	// Last default-origination time
	LastDefaultOriginateTimestamp *BgpTimespec `protobuf:"bytes,84,opt,name=last_default_originate_timestamp,json=lastDefaultOriginateTimestamp" json:"last_default_originate_timestamp,omitempty"`
	// Time since last default-origination event (in seconds)
	LastDefaultOriginateAge uint32 `protobuf:"varint,85,opt,name=last_default_originate_age,json=lastDefaultOriginateAge" json:"last_default_originate_age,omitempty"`
	// Default-origination state
	DefaultOriginateState int32 `protobuf:"zigzag32,86,opt,name=default_originate_state,json=defaultOriginateState" json:"default_originate_state,omitempty"`
	// Default-origination context
	DefaultOriginateInternalContext int32 `protobuf:"zigzag32,87,opt,name=default_originate_internal_context,json=defaultOriginateInternalContext" json:"default_originate_internal_context,omitempty"`
	// Number of EORs outstanding
	IsEorOutstanding bool `protobuf:"varint,88,opt,name=is_eor_outstanding,json=isEorOutstanding" json:"is_eor_outstanding,omitempty"`
	// Refresh Outbound count
	OutboundRefreshCount uint32 `protobuf:"varint,89,opt,name=outbound_refresh_count,json=outboundRefreshCount" json:"outbound_refresh_count,omitempty"`
	// Refresh Inbound count
	InboundRefreshCount uint32 `protobuf:"varint,90,opt,name=inbound_refresh_count,json=inboundRefreshCount" json:"inbound_refresh_count,omitempty"`
	// Last update-group timer start
	LastUpdateGroupStartTimestamp *BgpTimespec `protobuf:"bytes,91,opt,name=last_update_group_start_timestamp,json=lastUpdateGroupStartTimestamp" json:"last_update_group_start_timestamp,omitempty"`
	// Last update-group timer expiry
	LastUpdateGroupExpiryTimestamp *BgpTimespec `protobuf:"bytes,92,opt,name=last_update_group_expiry_timestamp,json=lastUpdateGroupExpiryTimestamp" json:"last_update_group_expiry_timestamp,omitempty"`
	// Is update-group timer running
	IsUpdateGroupTimerRunning bool `protobuf:"varint,93,opt,name=is_update_group_timer_running,json=isUpdateGroupTimerRunning" json:"is_update_group_timer_running,omitempty"`
	// Current Update-group address-family identifier
	CurrentUpdateGroupAfName string `protobuf:"bytes,94,opt,name=current_update_group_af_name,json=currentUpdateGroupAfName" json:"current_update_group_af_name,omitempty"`
	// Last Update-group address-family identifier
	LastUpdateGroupAfName string `protobuf:"bytes,95,opt,name=last_update_group_af_name,json=lastUpdateGroupAfName" json:"last_update_group_af_name,omitempty"`
	// First update queued time
	FirstUpdateQueuedTimestamp *BgpTimespec `protobuf:"bytes,96,opt,name=first_update_queued_timestamp,json=firstUpdateQueuedTimestamp" json:"first_update_queued_timestamp,omitempty"`
	// Last update queued time
	LastUpdateQueuedTimestamp *BgpTimespec `protobuf:"bytes,97,opt,name=last_update_queued_timestamp,json=lastUpdateQueuedTimestamp" json:"last_update_queued_timestamp,omitempty"`
	// Time since last update queued event (in seconds)
	LastUpdateQueuedAge uint32 `protobuf:"varint,98,opt,name=last_update_queued_age,json=lastUpdateQueuedAge" json:"last_update_queued_age,omitempty"`
	// Last refresh update queued time
	LastRefreshUpdateQueuedTimestamp *BgpTimespec `protobuf:"bytes,99,opt,name=last_refresh_update_queued_timestamp,json=lastRefreshUpdateQueuedTimestamp" json:"last_refresh_update_queued_timestamp,omitempty"`
	// Time since last refresh update queued event (in seconds)
	LastRefreshUpdateQueuedAge uint32 `protobuf:"varint,100,opt,name=last_refresh_update_queued_age,json=lastRefreshUpdateQueuedAge" json:"last_refresh_update_queued_age,omitempty"`
	// First update write time
	FirstUpdateWriteTimestamp *BgpTimespec `protobuf:"bytes,101,opt,name=first_update_write_timestamp,json=firstUpdateWriteTimestamp" json:"first_update_write_timestamp,omitempty"`
	// Last update write time
	LastUpdateWriteTimestamp *BgpTimespec `protobuf:"bytes,102,opt,name=last_update_write_timestamp,json=lastUpdateWriteTimestamp" json:"last_update_write_timestamp,omitempty"`
	// Time since last update write event (in seconds)
	LastUpdateWriteAge uint32 `protobuf:"varint,103,opt,name=last_update_write_age,json=lastUpdateWriteAge" json:"last_update_write_age,omitempty"`
	// Last refresh update write time
	LastRefreshUpdateWriteTimestamp *BgpTimespec `protobuf:"bytes,104,opt,name=last_refresh_update_write_timestamp,json=lastRefreshUpdateWriteTimestamp" json:"last_refresh_update_write_timestamp,omitempty"`
	// Time since last refresh update write event (in seconds)
	LastRefreshUpdateWriteAge uint32 `protobuf:"varint,105,opt,name=last_refresh_update_write_age,json=lastRefreshUpdateWriteAge" json:"last_refresh_update_write_age,omitempty"`
	// Update statistics
	UpdateStatistics *BgpUpdgenStatsBag `protobuf:"bytes,106,opt,name=update_statistics,json=updateStatistics" json:"update_statistics,omitempty"`
}

func (m *BgpUpdgenNbrBag) Reset()                    { *m = BgpUpdgenNbrBag{} }
func (m *BgpUpdgenNbrBag) String() string            { return proto.CompactTextString(m) }
func (*BgpUpdgenNbrBag) ProtoMessage()               {}
func (*BgpUpdgenNbrBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BgpUpdgenNbrBag) GetProcessId() uint32 {
	if m != nil {
		return m.ProcessId
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateVrfName() string {
	if m != nil {
		return m.UpdateVrfName
	}
	return ""
}

func (m *BgpUpdgenNbrBag) GetUpdateGroupAfName() string {
	if m != nil {
		return m.UpdateGroupAfName
	}
	return ""
}

func (m *BgpUpdgenNbrBag) GetUpdateNeighborAddress() *BgpAddrtype {
	if m != nil {
		return m.UpdateNeighborAddress
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetUpdateFilterGroupIndex() uint32 {
	if m != nil {
		return m.UpdateFilterGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshFilterGroupIndex() uint32 {
	if m != nil {
		return m.RefreshFilterGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetSubGroupIndex() uint32 {
	if m != nil {
		return m.SubGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshSubGroupIndex() uint32 {
	if m != nil {
		return m.RefreshSubGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshSubGroupId() uint32 {
	if m != nil {
		return m.RefreshSubGroupId
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateGroupIndex() uint32 {
	if m != nil {
		return m.UpdateGroupIndex
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateMainTableVersion() uint32 {
	if m != nil {
		return m.UpdateMainTableVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateVrfTableRibVersion() uint32 {
	if m != nil {
		return m.UpdateVrfTableRibVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateOutQueueMessages() uint32 {
	if m != nil {
		return m.UpdateOutQueueMessages
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateOutQueueSize() uint32 {
	if m != nil {
		return m.UpdateOutQueueSize
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshUpdateOutQueueMessages() uint32 {
	if m != nil {
		return m.RefreshUpdateOutQueueMessages
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshUpdateOutQueueSize() uint32 {
	if m != nil {
		return m.RefreshUpdateOutQueueSize
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateFilterGroupMessages() uint32 {
	if m != nil {
		return m.UpdateFilterGroupMessages
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetLastSubGroupAddTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastSubGroupAddTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastSubGroupRemoveTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastSubGroupRemoveTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastFilterGroupAddTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastFilterGroupAddTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastFilterGroupRemoveTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastFilterGroupRemoveTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetPendingTargetVersion() uint32 {
	if m != nil {
		return m.PendingTargetVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetNextResumeVersion() uint32 {
	if m != nil {
		return m.NextResumeVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetAckVersion() uint32 {
	if m != nil {
		return m.AckVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetSyncedAckVersion() uint32 {
	if m != nil {
		return m.SyncedAckVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetOutstandingVersionCount() uint32 {
	if m != nil {
		return m.OutstandingVersionCount
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateRefreshVersion() uint32 {
	if m != nil {
		return m.UpdateRefreshVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshRequestedTargetVersion() uint32 {
	if m != nil {
		return m.RefreshRequestedTargetVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateRefreshTargetVersion() uint32 {
	if m != nil {
		return m.UpdateRefreshTargetVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshPendingTargetVersion() uint32 {
	if m != nil {
		return m.RefreshPendingTargetVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshNextResumeVersion() uint32 {
	if m != nil {
		return m.RefreshNextResumeVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetRefreshAckVersion() uint32 {
	if m != nil {
		return m.RefreshAckVersion
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetFirstDefaultOriginateTimestamp() *BgpTimespec {
	if m != nil {
		return m.FirstDefaultOriginateTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastDefaultOriginateTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastDefaultOriginateTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastDefaultOriginateAge() uint32 {
	if m != nil {
		return m.LastDefaultOriginateAge
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetDefaultOriginateState() int32 {
	if m != nil {
		return m.DefaultOriginateState
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetDefaultOriginateInternalContext() int32 {
	if m != nil {
		return m.DefaultOriginateInternalContext
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetIsEorOutstanding() bool {
	if m != nil {
		return m.IsEorOutstanding
	}
	return false
}

func (m *BgpUpdgenNbrBag) GetOutboundRefreshCount() uint32 {
	if m != nil {
		return m.OutboundRefreshCount
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetInboundRefreshCount() uint32 {
	if m != nil {
		return m.InboundRefreshCount
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetLastUpdateGroupStartTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateGroupStartTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastUpdateGroupExpiryTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateGroupExpiryTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetIsUpdateGroupTimerRunning() bool {
	if m != nil {
		return m.IsUpdateGroupTimerRunning
	}
	return false
}

func (m *BgpUpdgenNbrBag) GetCurrentUpdateGroupAfName() string {
	if m != nil {
		return m.CurrentUpdateGroupAfName
	}
	return ""
}

func (m *BgpUpdgenNbrBag) GetLastUpdateGroupAfName() string {
	if m != nil {
		return m.LastUpdateGroupAfName
	}
	return ""
}

func (m *BgpUpdgenNbrBag) GetFirstUpdateQueuedTimestamp() *BgpTimespec {
	if m != nil {
		return m.FirstUpdateQueuedTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastUpdateQueuedTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateQueuedTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastUpdateQueuedAge() uint32 {
	if m != nil {
		return m.LastUpdateQueuedAge
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetLastRefreshUpdateQueuedTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastRefreshUpdateQueuedTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastRefreshUpdateQueuedAge() uint32 {
	if m != nil {
		return m.LastRefreshUpdateQueuedAge
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetFirstUpdateWriteTimestamp() *BgpTimespec {
	if m != nil {
		return m.FirstUpdateWriteTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastUpdateWriteTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateWriteTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastUpdateWriteAge() uint32 {
	if m != nil {
		return m.LastUpdateWriteAge
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetLastRefreshUpdateWriteTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastRefreshUpdateWriteTimestamp
	}
	return nil
}

func (m *BgpUpdgenNbrBag) GetLastRefreshUpdateWriteAge() uint32 {
	if m != nil {
		return m.LastRefreshUpdateWriteAge
	}
	return 0
}

func (m *BgpUpdgenNbrBag) GetUpdateStatistics() *BgpUpdgenStatsBag {
	if m != nil {
		return m.UpdateStatistics
	}
	return nil
}

type BgpTimespec struct {
	// Seconds part of time value
	Seconds uint32 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	// Nanoseconds part of time value
	Nanoseconds uint32 `protobuf:"varint,2,opt,name=nanoseconds" json:"nanoseconds,omitempty"`
}

func (m *BgpTimespec) Reset()                    { *m = BgpTimespec{} }
func (m *BgpTimespec) String() string            { return proto.CompactTextString(m) }
func (*BgpTimespec) ProtoMessage()               {}
func (*BgpTimespec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BgpTimespec) GetSeconds() uint32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *BgpTimespec) GetNanoseconds() uint32 {
	if m != nil {
		return m.Nanoseconds
	}
	return 0
}

// IPV4Tunnel Address type
type IPV4TunnelAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4TunnelAddressType) Reset()                    { *m = IPV4TunnelAddressType{} }
func (m *IPV4TunnelAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4TunnelAddressType) ProtoMessage()               {}
func (*IPV4TunnelAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IPV4TunnelAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4MDT Address type
type IPV4MDTAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4MDTAddressType) Reset()                    { *m = IPV4MDTAddressType{} }
func (m *IPV4MDTAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4MDTAddressType) ProtoMessage()               {}
func (*IPV4MDTAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IPV4MDTAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4 RTConstraint Address type
type RTConstraintAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *RTConstraintAddressType) Reset()                    { *m = RTConstraintAddressType{} }
func (m *RTConstraintAddressType) String() string            { return proto.CompactTextString(m) }
func (*RTConstraintAddressType) ProtoMessage()               {}
func (*RTConstraintAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RTConstraintAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV6 Address type
type IPV6AddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV6AddressType) Reset()                    { *m = IPV6AddressType{} }
func (m *IPV6AddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV6AddressType) ProtoMessage()               {}
func (*IPV6AddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IPV6AddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpIpv4SrpolicyAddrT struct {
	Ipv4SrpolicyAddress []byte `protobuf:"bytes,1,opt,name=ipv4_srpolicy_address,json=ipv4SrpolicyAddress,proto3" json:"ipv4_srpolicy_address,omitempty"`
}

func (m *BgpIpv4SrpolicyAddrT) Reset()                    { *m = BgpIpv4SrpolicyAddrT{} }
func (m *BgpIpv4SrpolicyAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpIpv4SrpolicyAddrT) ProtoMessage()               {}
func (*BgpIpv4SrpolicyAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BgpIpv4SrpolicyAddrT) GetIpv4SrpolicyAddress() []byte {
	if m != nil {
		return m.Ipv4SrpolicyAddress
	}
	return nil
}

type BgpIpv6SrpolicyAddrT struct {
	Ipv6SrpolicyAddress []byte `protobuf:"bytes,1,opt,name=ipv6_srpolicy_address,json=ipv6SrpolicyAddress,proto3" json:"ipv6_srpolicy_address,omitempty"`
}

func (m *BgpIpv6SrpolicyAddrT) Reset()                    { *m = BgpIpv6SrpolicyAddrT{} }
func (m *BgpIpv6SrpolicyAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpIpv6SrpolicyAddrT) ProtoMessage()               {}
func (*BgpIpv6SrpolicyAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BgpIpv6SrpolicyAddrT) GetIpv6SrpolicyAddress() []byte {
	if m != nil {
		return m.Ipv6SrpolicyAddress
	}
	return nil
}

type BgpL2VpnAddrT struct {
	L2VpnAddress []byte `protobuf:"bytes,1,opt,name=l2vpn_address,json=l2vpnAddress,proto3" json:"l2vpn_address,omitempty"`
}

func (m *BgpL2VpnAddrT) Reset()                    { *m = BgpL2VpnAddrT{} }
func (m *BgpL2VpnAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpL2VpnAddrT) ProtoMessage()               {}
func (*BgpL2VpnAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BgpL2VpnAddrT) GetL2VpnAddress() []byte {
	if m != nil {
		return m.L2VpnAddress
	}
	return nil
}

// L2VPN EVPN Address type
type L2VPNEVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *L2VPNEVPNAddressType) Reset()                    { *m = L2VPNEVPNAddressType{} }
func (m *L2VPNEVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*L2VPNEVPNAddressType) ProtoMessage()               {}
func (*L2VPNEVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *L2VPNEVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpL2VpnMspwAddrT struct {
	L2VpnAddress []byte `protobuf:"bytes,1,opt,name=l2vpn_address,json=l2vpnAddress,proto3" json:"l2vpn_address,omitempty"`
}

func (m *BgpL2VpnMspwAddrT) Reset()                    { *m = BgpL2VpnMspwAddrT{} }
func (m *BgpL2VpnMspwAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpL2VpnMspwAddrT) ProtoMessage()               {}
func (*BgpL2VpnMspwAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BgpL2VpnMspwAddrT) GetL2VpnAddress() []byte {
	if m != nil {
		return m.L2VpnAddress
	}
	return nil
}

// IPV6 MVPN Address type
type IPV6MVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV6MVPNAddressType) Reset()                    { *m = IPV6MVPNAddressType{} }
func (m *IPV6MVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV6MVPNAddressType) ProtoMessage()               {}
func (*IPV6MVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IPV6MVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4 MVPN Address type
type IPV4MVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4MVPNAddressType) Reset()                    { *m = IPV4MVPNAddressType{} }
func (m *IPV4MVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4MVPNAddressType) ProtoMessage()               {}
func (*IPV4MVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IPV4MVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// LINKSTATE LINKSTATE Address type
type LS_LSAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *LS_LSAddressType) Reset()                    { *m = LS_LSAddressType{} }
func (m *LS_LSAddressType) String() string            { return proto.CompactTextString(m) }
func (*LS_LSAddressType) ProtoMessage()               {}
func (*LS_LSAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *LS_LSAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPv4 Flowspec Address type
type IPv4FlowspecAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPv4FlowspecAddressType) Reset()                    { *m = IPv4FlowspecAddressType{} }
func (m *IPv4FlowspecAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPv4FlowspecAddressType) ProtoMessage()               {}
func (*IPv4FlowspecAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IPv4FlowspecAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPv6 Flowspec Address type
type IPv6FlowspecAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPv6FlowspecAddressType) Reset()                    { *m = IPv6FlowspecAddressType{} }
func (m *IPv6FlowspecAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPv6FlowspecAddressType) ProtoMessage()               {}
func (*IPv6FlowspecAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *IPv6FlowspecAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpAddrtype struct {
	Afi string `protobuf:"bytes,1,opt,name=afi" json:"afi,omitempty"`
	// IPv4 Addr
	Ipv4Address string `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address" json:"ipv4_address,omitempty"`
	// IPv4 Mcast Addr
	Ipv4McastAddress string `protobuf:"bytes,3,opt,name=ipv4_mcast_address,json=ipv4McastAddress" json:"ipv4_mcast_address,omitempty"`
	// IPv4 Label Addr
	Ipv4LabelAddress string `protobuf:"bytes,4,opt,name=ipv4_label_address,json=ipv4LabelAddress" json:"ipv4_label_address,omitempty"`
	// IPv4 Tunnel
	Ipv4TunnelAddress *IPV4TunnelAddressType `protobuf:"bytes,5,opt,name=ipv4_tunnel_address,json=ipv4TunnelAddress" json:"ipv4_tunnel_address,omitempty"`
	// IPv4 MDT Addr
	Ipv4MdtAddress *IPV4MDTAddressType `protobuf:"bytes,6,opt,name=ipv4_mdt_address,json=ipv4MdtAddress" json:"ipv4_mdt_address,omitempty"`
	// IPv4 VPN Addr
	Ipv4VpnAddress string `protobuf:"bytes,7,opt,name=ipv4_vpn_address,json=ipv4VpnAddress" json:"ipv4_vpn_address,omitempty"`
	// IPv4 VPN Mcast Addr
	Ipv4VpnaMcastddress string `protobuf:"bytes,8,opt,name=ipv4_vpna_mcastddress,json=ipv4VpnaMcastddress" json:"ipv4_vpna_mcastddress,omitempty"`
	// IPV6 Addr
	Ipv6Address *IPV6AddressType `protobuf:"bytes,9,opt,name=ipv6_address,json=ipv6Address" json:"ipv6_address,omitempty"`
	// IPV6 Mcast Addr
	Ipv6McastAddress *IPV6AddressType `protobuf:"bytes,10,opt,name=ipv6_mcast_address,json=ipv6McastAddress" json:"ipv6_mcast_address,omitempty"`
	// IPv6 Label Addr
	Ipv6LabelAddress *IPV6AddressType `protobuf:"bytes,11,opt,name=ipv6_label_address,json=ipv6LabelAddress" json:"ipv6_label_address,omitempty"`
	// IPv6 VPN Addr
	Ipv6VpnAddress *IPV6AddressType `protobuf:"bytes,12,opt,name=ipv6_vpn_address,json=ipv6VpnAddress" json:"ipv6_vpn_address,omitempty"`
	// IPv6 VPN Mcast Addr
	Ipv6VpnMcastAddress *IPV6AddressType `protobuf:"bytes,13,opt,name=ipv6_vpn_mcast_address,json=ipv6VpnMcastAddress" json:"ipv6_vpn_mcast_address,omitempty"`
	// L2VPN VPLS Addr
	L2VpnvplsAddress *BgpL2VpnAddrT `protobuf:"bytes,14,opt,name=l2_vpnvpls_address,json=l2VpnvplsAddress" json:"l2_vpnvpls_address,omitempty"`
	// RT Constrt Addr
	RtConstraintAddress *RTConstraintAddressType `protobuf:"bytes,15,opt,name=rt_constraint_address,json=rtConstraintAddress" json:"rt_constraint_address,omitempty"`
	// MVPN addr
	Ipv6MvpnAddress *IPV6MVPNAddressType `protobuf:"bytes,16,opt,name=ipv6_mvpn_address,json=ipv6MvpnAddress" json:"ipv6_mvpn_address,omitempty"`
	// MVPN4 addr
	Ipv4MvpnAddress *IPV4MVPNAddressType `protobuf:"bytes,17,opt,name=ipv4_mvpn_address,json=ipv4MvpnAddress" json:"ipv4_mvpn_address,omitempty"`
	// L2VPN EVPN Addr
	L2VpnEvpnAddress *L2VPNEVPNAddressType `protobuf:"bytes,18,opt,name=l2_vpn_evpn_address,json=l2VpnEvpnAddress" json:"l2_vpn_evpn_address,omitempty"`
	// LINKSTATE LINKSTATE Addr
	LsLsAddress *LS_LSAddressType `protobuf:"bytes,19,opt,name=ls_ls_address,json=lsLsAddress" json:"ls_ls_address,omitempty"`
	// L2VPN MSPW Addr
	L2VpnMspwAddress *BgpL2VpnMspwAddrT `protobuf:"bytes,20,opt,name=l2_vpn_mspw_address,json=l2VpnMspwAddress" json:"l2_vpn_mspw_address,omitempty"`
	// IPV4 Flowspec Addr
	Ipv4FlowspecAddress *IPv4FlowspecAddressType `protobuf:"bytes,21,opt,name=ipv4_flowspec_address,json=ipv4FlowspecAddress" json:"ipv4_flowspec_address,omitempty"`
	// IPV6 Flowspec Addr
	Ipv6FlowspecAddress *IPv6FlowspecAddressType `protobuf:"bytes,22,opt,name=ipv6_flowspec_address,json=ipv6FlowspecAddress" json:"ipv6_flowspec_address,omitempty"`
	// IPV4 VPN Flowspec Addr
	Ipv4VpnFlowspecAddress *IPv4FlowspecAddressType `protobuf:"bytes,23,opt,name=ipv4_vpn_flowspec_address,json=ipv4VpnFlowspecAddress" json:"ipv4_vpn_flowspec_address,omitempty"`
	// IPV6 VPN Flowspec Addr
	Ipv6VpnFlowspecAddress *IPv6FlowspecAddressType `protobuf:"bytes,24,opt,name=ipv6_vpn_flowspec_address,json=ipv6VpnFlowspecAddress" json:"ipv6_vpn_flowspec_address,omitempty"`
	// IPV4 Policy Addr
	Ipv4SrPolicyAddress *BgpIpv4SrpolicyAddrT `protobuf:"bytes,25,opt,name=ipv4_sr_policy_address,json=ipv4SrPolicyAddress" json:"ipv4_sr_policy_address,omitempty"`
	// IPV6 Policy Addr
	Ipv6SrPolicyAddress *BgpIpv6SrpolicyAddrT `protobuf:"bytes,26,opt,name=ipv6_sr_policy_address,json=ipv6SrPolicyAddress" json:"ipv6_sr_policy_address,omitempty"`
}

func (m *BgpAddrtype) Reset()                    { *m = BgpAddrtype{} }
func (m *BgpAddrtype) String() string            { return proto.CompactTextString(m) }
func (*BgpAddrtype) ProtoMessage()               {}
func (*BgpAddrtype) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *BgpAddrtype) GetAfi() string {
	if m != nil {
		return m.Afi
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4McastAddress() string {
	if m != nil {
		return m.Ipv4McastAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4LabelAddress() string {
	if m != nil {
		return m.Ipv4LabelAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4TunnelAddress() *IPV4TunnelAddressType {
	if m != nil {
		return m.Ipv4TunnelAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4MdtAddress() *IPV4MDTAddressType {
	if m != nil {
		return m.Ipv4MdtAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4VpnAddress() string {
	if m != nil {
		return m.Ipv4VpnAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4VpnaMcastddress() string {
	if m != nil {
		return m.Ipv4VpnaMcastddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv6Address() *IPV6AddressType {
	if m != nil {
		return m.Ipv6Address
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6McastAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6McastAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6LabelAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6LabelAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6VpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnMcastAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6VpnMcastAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnvplsAddress() *BgpL2VpnAddrT {
	if m != nil {
		return m.L2VpnvplsAddress
	}
	return nil
}

func (m *BgpAddrtype) GetRtConstraintAddress() *RTConstraintAddressType {
	if m != nil {
		return m.RtConstraintAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6MvpnAddress() *IPV6MVPNAddressType {
	if m != nil {
		return m.Ipv6MvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4MvpnAddress() *IPV4MVPNAddressType {
	if m != nil {
		return m.Ipv4MvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnEvpnAddress() *L2VPNEVPNAddressType {
	if m != nil {
		return m.L2VpnEvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetLsLsAddress() *LS_LSAddressType {
	if m != nil {
		return m.LsLsAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnMspwAddress() *BgpL2VpnMspwAddrT {
	if m != nil {
		return m.L2VpnMspwAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4FlowspecAddress() *IPv4FlowspecAddressType {
	if m != nil {
		return m.Ipv4FlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6FlowspecAddress() *IPv6FlowspecAddressType {
	if m != nil {
		return m.Ipv6FlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4VpnFlowspecAddress() *IPv4FlowspecAddressType {
	if m != nil {
		return m.Ipv4VpnFlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnFlowspecAddress() *IPv6FlowspecAddressType {
	if m != nil {
		return m.Ipv6VpnFlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4SrPolicyAddress() *BgpIpv4SrpolicyAddrT {
	if m != nil {
		return m.Ipv4SrPolicyAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6SrPolicyAddress() *BgpIpv6SrpolicyAddrT {
	if m != nil {
		return m.Ipv6SrPolicyAddress
	}
	return nil
}

// BGP Update generation common statistics information
type BgpUpdgenStatsBag struct {
	// OutQueue High Messages
	UpdateOutQueueMessagesHigh uint32 `protobuf:"varint,1,opt,name=update_out_queue_messages_high,json=updateOutQueueMessagesHigh" json:"update_out_queue_messages_high,omitempty"`
	// OutQueue Cumulative Messages
	UpdateOutQueueMessagesCumulative uint32 `protobuf:"varint,2,opt,name=update_out_queue_messages_cumulative,json=updateOutQueueMessagesCumulative" json:"update_out_queue_messages_cumulative,omitempty"`
	// OutQueue Discarded Messages
	UpdateOutQueueMessagesDiscarded uint32 `protobuf:"varint,3,opt,name=update_out_queue_messages_discarded,json=updateOutQueueMessagesDiscarded" json:"update_out_queue_messages_discarded,omitempty"`
	// OutQueue Cleared Messages
	UpdateOutQueueMessagesCleared uint32 `protobuf:"varint,4,opt,name=update_out_queue_messages_cleared,json=updateOutQueueMessagesCleared" json:"update_out_queue_messages_cleared,omitempty"`
	// OutQueue Hi Size
	UpdateOutQueueSizeHigh uint32 `protobuf:"varint,5,opt,name=update_out_queue_size_high,json=updateOutQueueSizeHigh" json:"update_out_queue_size_high,omitempty"`
	// OutQueue Cumulative Size
	UpdateOutQueueSizeCumulative uint64 `protobuf:"varint,6,opt,name=update_out_queue_size_cumulative,json=updateOutQueueSizeCumulative" json:"update_out_queue_size_cumulative,omitempty"`
	// OutQueue Discarded Size
	UpdateOutQueueSizeDiscarded uint64 `protobuf:"varint,7,opt,name=update_out_queue_size_discarded,json=updateOutQueueSizeDiscarded" json:"update_out_queue_size_discarded,omitempty"`
	// OutQueue Cleared Size
	UpdateOutQueueSizeCleared uint64 `protobuf:"varint,8,opt,name=update_out_queue_size_cleared,json=updateOutQueueSizeCleared" json:"update_out_queue_size_cleared,omitempty"`
	// Last Discarded time
	LastUpdateDiscardTimestamp *BgpTimespec `protobuf:"bytes,9,opt,name=last_update_discard_timestamp,json=lastUpdateDiscardTimestamp" json:"last_update_discard_timestamp,omitempty"`
	// Time since last Discard event (in seconds)
	LastUpdateDiscardAge uint32 `protobuf:"varint,10,opt,name=last_update_discard_age,json=lastUpdateDiscardAge" json:"last_update_discard_age,omitempty"`
	// Last Cleared time
	LastUpdateClearedTimestamp *BgpTimespec `protobuf:"bytes,11,opt,name=last_update_cleared_timestamp,json=lastUpdateClearedTimestamp" json:"last_update_cleared_timestamp,omitempty"`
	// Time since last Clear event (in seconds)
	LastUpdateCleardAge uint32 `protobuf:"varint,12,opt,name=last_update_cleard_age,json=lastUpdateCleardAge" json:"last_update_cleard_age,omitempty"`
	// Throttle Count
	UpdateThrottleCount uint32 `protobuf:"varint,13,opt,name=update_throttle_count,json=updateThrottleCount" json:"update_throttle_count,omitempty"`
	// Last Throttled time
	LastUpdateThrottleTimestamp *BgpTimespec `protobuf:"bytes,14,opt,name=last_update_throttle_timestamp,json=lastUpdateThrottleTimestamp" json:"last_update_throttle_timestamp,omitempty"`
	// Time since last Throttle event (in seconds)
	LastUpdateThrottleAge uint32 `protobuf:"varint,15,opt,name=last_update_throttle_age,json=lastUpdateThrottleAge" json:"last_update_throttle_age,omitempty"`
	// Recovery Count
	UpdateRecoveryCount uint32 `protobuf:"varint,16,opt,name=update_recovery_count,json=updateRecoveryCount" json:"update_recovery_count,omitempty"`
	// Last Recovery time
	LastUpdateRecoveryTimestamp *BgpTimespec `protobuf:"bytes,17,opt,name=last_update_recovery_timestamp,json=lastUpdateRecoveryTimestamp" json:"last_update_recovery_timestamp,omitempty"`
	// Time since last Recovery event (in seconds)
	LastUpdateRecoveryAge uint32 `protobuf:"varint,18,opt,name=last_update_recovery_age,json=lastUpdateRecoveryAge" json:"last_update_recovery_age,omitempty"`
	// Memory allocation failure count
	UpdateMemoryAllocationFailCount uint32 `protobuf:"varint,19,opt,name=update_memory_allocation_fail_count,json=updateMemoryAllocationFailCount" json:"update_memory_allocation_fail_count,omitempty"`
	// Memory allocation failure time
	LastUpdateMemoryAllocationFailTimestamp *BgpTimespec `protobuf:"bytes,20,opt,name=last_update_memory_allocation_fail_timestamp,json=lastUpdateMemoryAllocationFailTimestamp" json:"last_update_memory_allocation_fail_timestamp,omitempty"`
	// Time since last memory allocation failure event (in seconds)
	LastUpdateMemoryAllocationFailAge uint32 `protobuf:"varint,21,opt,name=last_update_memory_allocation_fail_age,json=lastUpdateMemoryAllocationFailAge" json:"last_update_memory_allocation_fail_age,omitempty"`
}

func (m *BgpUpdgenStatsBag) Reset()                    { *m = BgpUpdgenStatsBag{} }
func (m *BgpUpdgenStatsBag) String() string            { return proto.CompactTextString(m) }
func (*BgpUpdgenStatsBag) ProtoMessage()               {}
func (*BgpUpdgenStatsBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueMessagesHigh() uint32 {
	if m != nil {
		return m.UpdateOutQueueMessagesHigh
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueMessagesCumulative() uint32 {
	if m != nil {
		return m.UpdateOutQueueMessagesCumulative
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueMessagesDiscarded() uint32 {
	if m != nil {
		return m.UpdateOutQueueMessagesDiscarded
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueMessagesCleared() uint32 {
	if m != nil {
		return m.UpdateOutQueueMessagesCleared
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueSizeHigh() uint32 {
	if m != nil {
		return m.UpdateOutQueueSizeHigh
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueSizeCumulative() uint64 {
	if m != nil {
		return m.UpdateOutQueueSizeCumulative
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueSizeDiscarded() uint64 {
	if m != nil {
		return m.UpdateOutQueueSizeDiscarded
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateOutQueueSizeCleared() uint64 {
	if m != nil {
		return m.UpdateOutQueueSizeCleared
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetLastUpdateDiscardTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateDiscardTimestamp
	}
	return nil
}

func (m *BgpUpdgenStatsBag) GetLastUpdateDiscardAge() uint32 {
	if m != nil {
		return m.LastUpdateDiscardAge
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetLastUpdateClearedTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateClearedTimestamp
	}
	return nil
}

func (m *BgpUpdgenStatsBag) GetLastUpdateCleardAge() uint32 {
	if m != nil {
		return m.LastUpdateCleardAge
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateThrottleCount() uint32 {
	if m != nil {
		return m.UpdateThrottleCount
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetLastUpdateThrottleTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateThrottleTimestamp
	}
	return nil
}

func (m *BgpUpdgenStatsBag) GetLastUpdateThrottleAge() uint32 {
	if m != nil {
		return m.LastUpdateThrottleAge
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateRecoveryCount() uint32 {
	if m != nil {
		return m.UpdateRecoveryCount
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetLastUpdateRecoveryTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateRecoveryTimestamp
	}
	return nil
}

func (m *BgpUpdgenStatsBag) GetLastUpdateRecoveryAge() uint32 {
	if m != nil {
		return m.LastUpdateRecoveryAge
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetUpdateMemoryAllocationFailCount() uint32 {
	if m != nil {
		return m.UpdateMemoryAllocationFailCount
	}
	return 0
}

func (m *BgpUpdgenStatsBag) GetLastUpdateMemoryAllocationFailTimestamp() *BgpTimespec {
	if m != nil {
		return m.LastUpdateMemoryAllocationFailTimestamp
	}
	return nil
}

func (m *BgpUpdgenStatsBag) GetLastUpdateMemoryAllocationFailAge() uint32 {
	if m != nil {
		return m.LastUpdateMemoryAllocationFailAge
	}
	return 0
}

func init() {
	proto.RegisterType((*BgpUpdgenNbrBag_KEYS)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_updgen_nbr_bag_KEYS")
	proto.RegisterType((*BgpUpdgenNbrBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_updgen_nbr_bag")
	proto.RegisterType((*BgpTimespec)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_timespec")
	proto.RegisterType((*IPV4TunnelAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.IPV4TunnelAddressType")
	proto.RegisterType((*IPV4MDTAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.IPV4MDTAddressType")
	proto.RegisterType((*RTConstraintAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.RTConstraintAddressType")
	proto.RegisterType((*IPV6AddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.IPV6AddressType")
	proto.RegisterType((*BgpIpv4SrpolicyAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_ipv4_srpolicy_addr_t")
	proto.RegisterType((*BgpIpv6SrpolicyAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_ipv6_srpolicy_addr_t")
	proto.RegisterType((*BgpL2VpnAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_l2vpn_addr_t")
	proto.RegisterType((*L2VPNEVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.L2VPNEVPNAddressType")
	proto.RegisterType((*BgpL2VpnMspwAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_l2vpn_mspw_addr_t")
	proto.RegisterType((*IPV6MVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.IPV6MVPNAddressType")
	proto.RegisterType((*IPV4MVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.IPV4MVPNAddressType")
	proto.RegisterType((*LS_LSAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.LS_LSAddressType")
	proto.RegisterType((*IPv4FlowspecAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.IPv4FlowspecAddressType")
	proto.RegisterType((*IPv6FlowspecAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.IPv6FlowspecAddressType")
	proto.RegisterType((*BgpAddrtype)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_addrtype")
	proto.RegisterType((*BgpUpdgenStatsBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.update_generation_neighbors.update_generation_neighbor.bgp_updgen_stats_bag")
}

func init() { proto.RegisterFile("bgp_updgen_nbr_bag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x5b, 0x59, 0x6f, 0xdc, 0xd6,
	0x15, 0x06, 0x13, 0xdb, 0xb2, 0x8f, 0x24, 0x4b, 0xa2, 0x34, 0xd2, 0x48, 0xb6, 0xac, 0x91, 0x1c,
	0x24, 0x6a, 0xeb, 0xc8, 0x88, 0x2c, 0x8f, 0x13, 0x3b, 0x8b, 0x65, 0x59, 0xb6, 0x15, 0x4b, 0xb2,
	0x4c, 0xc9, 0x4a, 0xd3, 0x8d, 0xe5, 0x90, 0x77, 0x46, 0x6c, 0x38, 0xe4, 0xe4, 0x5e, 0x72, 0x6c,
	0xf9, 0x17, 0xf4, 0x17, 0x14, 0x68, 0xd1, 0x05, 0xed, 0x43, 0xff, 0x45, 0xd1, 0x87, 0x16, 0xe8,
	0x82, 0xa2, 0xe9, 0x4b, 0xd3, 0x20, 0x68, 0x80, 0x2e, 0x28, 0xfa, 0xd6, 0xc7, 0x3e, 0x17, 0x77,
	0x23, 0x2f, 0x37, 0x59, 0x7d, 0xa3, 0x5e, 0x0c, 0x0d, 0xcf, 0x72, 0xcf, 0xf7, 0x9d, 0x73, 0x0f,
	0xef, 0x42, 0x43, 0xbd, 0xd5, 0xe9, 0x99, 0x51, 0xcf, 0xe9, 0x20, 0xdf, 0xf4, 0x5b, 0xd8, 0x6c,
	0x59, 0x9d, 0xa5, 0x1e, 0x0e, 0xc2, 0x40, 0xff, 0xae, 0x66, 0xbb, 0xc4, 0x0e, 0x4c, 0x37, 0x20,
	0xe6, 0x33, 0x6c, 0xba, 0xbd, 0xfe, 0x8a, 0x49, 0x95, 0x83, 0x1e, 0xc2, 0x4b, 0xad, 0x4e, 0x6f,
	0xc9, 0xf5, 0x49, 0x68, 0xf9, 0x36, 0x22, 0xf1, 0x5f, 0xf1, 0x1f, 0xa6, 0x65, 0x87, 0x6e, 0x1f,
	0x2d, 0xf5, 0x71, 0x9b, 0xd0, 0x7f, 0x96, 0xac, 0x36, 0x59, 0xb2, 0xda, 0x4b, 0x51, 0xcf, 0xb1,
	0x42, 0x64, 0x76, 0x90, 0x8f, 0xb0, 0x15, 0xba, 0x81, 0x6f, 0xfa, 0xc8, 0xed, 0x1c, 0xb4, 0x02,
	0x4c, 0x8e, 0x90, 0x2d, 0xfc, 0xea, 0x25, 0x98, 0xca, 0xc7, 0x69, 0x3e, 0x5c, 0xff, 0x70, 0x57,
	0xbf, 0x0c, 0xc3, 0xf1, 0xa8, 0xbe, 0xd5, 0x45, 0x75, 0xad, 0xa1, 0x2d, 0x9e, 0x33, 0x86, 0xe4,
	0xc3, 0x6d, 0xab, 0x8b, 0xf4, 0x69, 0x38, 0xdb, 0xc7, 0x6d, 0x2e, 0x7f, 0x89, 0xc9, 0x07, 0xfa,
	0xb8, 0xcd, 0x44, 0x53, 0x30, 0x60, 0x09, 0xc9, 0xcb, 0x4c, 0x72, 0xc6, 0xe2, 0x82, 0x2b, 0xa0,
	0xcb, 0x90, 0x70, 0x10, 0xf5, 0x4c, 0xd7, 0x77, 0xd0, 0xb3, 0xfa, 0xa9, 0x86, 0xb6, 0x38, 0x6c,
	0x8c, 0x72, 0xc9, 0x7d, 0x2a, 0xd8, 0xa0, 0xcf, 0xf5, 0x57, 0x61, 0x84, 0x44, 0xad, 0x94, 0xea,
	0x69, 0xa6, 0x3a, 0x4c, 0xa2, 0x96, 0xa2, 0xd7, 0x80, 0x21, 0x45, 0xcf, 0xa9, 0x9f, 0x61, 0x4a,
	0x10, 0x2b, 0x39, 0x74, 0xdc, 0xb6, 0xeb, 0x85, 0x08, 0xa7, 0x9c, 0x0d, 0xf0, 0x71, 0xb9, 0x44,
	0xf1, 0xf7, 0x25, 0x18, 0x95, 0x34, 0x99, 0x96, 0xe3, 0x60, 0x44, 0x48, 0xfd, 0x2c, 0xc3, 0x31,
	0x22, 0x9f, 0xaf, 0xf2, 0xc7, 0x0b, 0xff, 0x79, 0x1d, 0xf4, 0x3c, 0x8b, 0xfa, 0x2c, 0x40, 0x0f,
	0x07, 0x36, 0x22, 0x84, 0xc6, 0xb3, 0xcc, 0xc6, 0x39, 0x27, 0x9e, 0x6c, 0x38, 0x14, 0x98, 0xa0,
	0x21, 0x66, 0xf0, 0x1a, 0xf3, 0x3f, 0xcc, 0x1f, 0xef, 0x0b, 0x1e, 0xaf, 0xc2, 0x44, 0x8a, 0x2e,
	0x49, 0xea, 0x0a, 0x53, 0x1e, 0x53, 0x08, 0x5b, 0xe5, 0x06, 0x9f, 0x68, 0x30, 0x25, 0x2c, 0x72,
	0x08, 0xae, 0x37, 0xb4, 0xc5, 0xc1, 0xe5, 0xef, 0x69, 0x4b, 0x55, 0x29, 0x41, 0x3a, 0x1a, 0x8b,
	0x2e, 0x3c, 0xec, 0x21, 0xa3, 0xc6, 0x15, 0xb7, 0xd3, 0x04, 0xeb, 0x6f, 0xc1, 0xb4, 0xf0, 0x50,
	0x90, 0xc0, 0x26, 0x23, 0x76, 0x92, 0x2b, 0xdc, 0xcb, 0xa6, 0xf1, 0x16, 0xcc, 0x60, 0xd4, 0xc6,
	0x88, 0x1c, 0x14, 0xd9, 0xde, 0x60, 0xb6, 0x53, 0x42, 0x23, 0x67, 0x5c, 0x50, 0x7b, 0x6f, 0x16,
	0xd5, 0xde, 0x75, 0x90, 0x2e, 0xcc, 0xac, 0xfe, 0x5b, 0x4c, 0x7f, 0x42, 0x88, 0x77, 0x53, 0x66,
	0x57, 0x61, 0xa2, 0xc0, 0xcc, 0xa9, 0xdf, 0x64, 0x36, 0x63, 0x59, 0x1b, 0xa7, 0x64, 0xe6, 0xdc,
	0x2a, 0x99, 0x39, 0x09, 0x6b, 0x5d, 0xcb, 0xf5, 0xcd, 0xd0, 0x6a, 0x79, 0xc8, 0xec, 0x23, 0x4c,
	0xdc, 0xc0, 0xaf, 0xbf, 0xad, 0xb2, 0xb6, 0x65, 0xb9, 0xfe, 0x1e, 0x15, 0xef, 0x73, 0xa9, 0xfe,
	0x2e, 0x5c, 0x54, 0x6a, 0x93, 0x5b, 0x62, 0xb7, 0x15, 0x5b, 0xbf, 0xc3, 0xac, 0xeb, 0x71, 0xa1,
	0x32, 0x63, 0xc3, 0x6d, 0x49, 0xfb, 0x64, 0xe8, 0x20, 0x0a, 0xcd, 0x8f, 0x23, 0x14, 0x21, 0xb3,
	0x8b, 0x08, 0xb1, 0x3a, 0x88, 0xd4, 0xdf, 0x55, 0x87, 0x7e, 0x14, 0x85, 0x8f, 0xa9, 0x78, 0x4b,
	0x48, 0xf5, 0x37, 0xa0, 0x96, 0x33, 0x25, 0xee, 0x73, 0x54, 0x7f, 0x8f, 0x99, 0xe9, 0x69, 0xb3,
	0x5d, 0xf7, 0x39, 0xd2, 0x1f, 0xc0, 0xbc, 0xe4, 0xb1, 0x7c, 0xd4, 0xdb, 0xcc, 0x7c, 0x56, 0x28,
	0x3e, 0x29, 0x1e, 0xfc, 0x36, 0xcc, 0x96, 0x7a, 0x62, 0x41, 0xac, 0x32, 0x2f, 0xd3, 0x85, 0x5e,
	0x58, 0x2c, 0xef, 0xc5, 0xcc, 0xa5, 0xca, 0x2d, 0x0e, 0xe3, 0x0e, 0x77, 0x90, 0xab, 0xd6, 0x38,
	0x84, 0xbf, 0x68, 0x70, 0xd1, 0xb3, 0x48, 0xa8, 0x94, 0x84, 0xe5, 0x38, 0x66, 0xe8, 0x76, 0x11,
	0x09, 0xad, 0x6e, 0xaf, 0xbe, 0x56, 0xc9, 0x29, 0xcc, 0xe2, 0xeb, 0x21, 0xdb, 0xa8, 0xd3, 0xe0,
	0x65, 0xcd, 0xae, 0x3a, 0xce, 0x9e, 0x0c, 0x5c, 0xff, 0x42, 0x83, 0xb9, 0x0c, 0x32, 0x8c, 0xba,
	0x41, 0x1f, 0x29, 0xe0, 0xee, 0x56, 0x1b, 0xdc, 0x05, 0x15, 0x9c, 0xc1, 0x82, 0x2f, 0xc0, 0x97,
	0xca, 0x7c, 0x3a, 0x79, 0xeb, 0x27, 0x00, 0x9f, 0x52, 0x95, 0xa9, 0xfc, 0xfd, 0x53, 0x83, 0x85,
	0x3c, 0xbe, 0x5c, 0x0a, 0xef, 0x55, 0x1b, 0xe2, 0xa5, 0x0c, 0xc4, 0x6c, 0x16, 0xeb, 0x30, 0x20,
	0xbb, 0xdc, 0x7d, 0x36, 0x57, 0xe5, 0x4f, 0x7d, 0x05, 0x26, 0x7b, 0xc8, 0x77, 0x5c, 0xbf, 0x63,
	0x86, 0x16, 0xee, 0xa0, 0x30, 0x6e, 0x87, 0x0f, 0x78, 0x93, 0x17, 0xd2, 0x3d, 0x26, 0x94, 0xad,
	0x70, 0x09, 0xc6, 0x7d, 0xf4, 0x2c, 0x34, 0x31, 0x22, 0x51, 0x37, 0xe9, 0xbf, 0x1b, 0xbc, 0xc7,
	0x53, 0x91, 0xc1, 0x24, 0x52, 0x7f, 0x0e, 0x06, 0x2d, 0xfb, 0xa3, 0x58, 0xef, 0x7d, 0xbe, 0x8c,
	0xb1, 0xec, 0x8f, 0xa4, 0xc2, 0x15, 0xd0, 0xc9, 0xa1, 0x6f, 0x23, 0xc7, 0x54, 0xf5, 0x1e, 0xf2,
	0x97, 0x00, 0x97, 0xac, 0x26, 0xda, 0x37, 0x61, 0x3a, 0x88, 0x42, 0x4a, 0x2b, 0x0b, 0x5c, 0xa8,
	0x9b, 0x76, 0x10, 0xf9, 0x61, 0x7d, 0x93, 0xbf, 0xfe, 0x14, 0x05, 0x61, 0xb6, 0x46, 0xc5, 0x14,
	0xb0, 0x60, 0x55, 0x36, 0x45, 0x39, 0xda, 0x16, 0x07, 0xcc, 0xa5, 0x06, 0x17, 0xca, 0x11, 0xef,
	0x43, 0x43, 0xaa, 0x63, 0xf4, 0x71, 0x84, 0x48, 0x88, 0x9c, 0x2c, 0x61, 0xdb, 0xa9, 0x66, 0x6c,
	0x48, 0xb5, 0x34, 0x73, 0xab, 0x30, 0x9b, 0x19, 0x3e, 0xe3, 0xe5, 0x11, 0xf3, 0x32, 0x93, 0x8a,
	0x22, 0xed, 0x62, 0x0d, 0x2e, 0x49, 0xdb, 0x92, 0xd4, 0xed, 0x30, 0x1f, 0x17, 0x84, 0xd6, 0x4e,
	0x51, 0x06, 0xdf, 0x01, 0x29, 0x36, 0x8b, 0x32, 0xf9, 0x98, 0xbf, 0x0b, 0x85, 0xca, 0x76, 0x2e,
	0xa1, 0x4b, 0x30, 0x2e, 0xcd, 0xd5, 0x84, 0x19, 0xa9, 0x97, 0xbc, 0x92, 0xb1, 0x7f, 0x68, 0x30,
	0xdf, 0x76, 0x31, 0x09, 0x4d, 0x07, 0xb5, 0xad, 0xc8, 0x0b, 0xcd, 0x00, 0xbb, 0x1d, 0xd7, 0xa7,
	0x44, 0x24, 0xb3, 0x6c, 0xb7, 0xe2, 0xb3, 0x8c, 0x21, 0xb8, 0xcb, 0x01, 0x3c, 0x92, 0xf1, 0x27,
	0xb3, 0xec, 0x6f, 0x1a, 0x34, 0x58, 0x2f, 0x39, 0x0a, 0xe3, 0x5e, 0xb5, 0x31, 0xce, 0x52, 0x00,
	0xe5, 0x10, 0x6f, 0xc1, 0x4c, 0x09, 0x42, 0xab, 0x83, 0xea, 0x4f, 0xf8, 0xd4, 0x2b, 0x72, 0xb1,
	0xda, 0x41, 0x7a, 0x13, 0xa6, 0xf2, 0x76, 0x24, 0xb4, 0x42, 0x54, 0xdf, 0x6f, 0x68, 0x8b, 0x63,
	0x46, 0xcd, 0xc9, 0x58, 0xed, 0x52, 0xa1, 0xfe, 0x10, 0x16, 0xf2, 0x76, 0xae, 0x1f, 0x22, 0xec,
	0x5b, 0x9e, 0x69, 0x07, 0x7e, 0x88, 0x9e, 0x85, 0xf5, 0x0f, 0x98, 0x8b, 0xb9, 0xac, 0x8b, 0x0d,
	0xa1, 0xb7, 0xc6, 0xd5, 0x68, 0xa7, 0x71, 0x89, 0x89, 0x02, 0x6c, 0x2a, 0x1d, 0xa2, 0xfe, 0xd5,
	0x86, 0xb6, 0x78, 0xd6, 0x18, 0x75, 0xc9, 0x7a, 0x80, 0x1f, 0x25, 0xcf, 0x69, 0xb7, 0x08, 0xa2,
	0xb0, 0x15, 0x44, 0xbe, 0x13, 0x4f, 0x58, 0xde, 0x66, 0x3e, 0xe4, 0xdd, 0x42, 0x4a, 0xc5, 0x4c,
	0xe5, 0x3d, 0x66, 0x19, 0x6a, 0xae, 0x5f, 0x64, 0xf4, 0x35, 0x66, 0x34, 0x2e, 0x84, 0x29, 0x9b,
	0xbf, 0x6b, 0x30, 0xcf, 0xa8, 0x4d, 0x2d, 0x86, 0x49, 0x68, 0xe1, 0x50, 0xa9, 0x9e, 0xaf, 0x9f,
	0x80, 0xea, 0x79, 0x92, 0xac, 0xd9, 0x77, 0x69, 0xf8, 0x05, 0x2f, 0xdb, 0x14, 0x46, 0xf4, 0xac,
	0xe7, 0xe2, 0x43, 0x05, 0xe4, 0x37, 0x4e, 0xc0, 0xcb, 0x56, 0x01, 0xb9, 0xce, 0xe2, 0x4f, 0x50,
	0xde, 0x86, 0x59, 0x97, 0xa4, 0x21, 0x52, 0x5b, 0x6c, 0xe2, 0xc8, 0xf7, 0x69, 0xb1, 0x7d, 0x93,
	0x15, 0xdb, 0xb4, 0x4b, 0x14, 0x27, 0xd4, 0x1c, 0x1b, 0x5c, 0x81, 0xee, 0x54, 0xec, 0x08, 0x63,
	0xe4, 0x67, 0x98, 0x92, 0xbb, 0xe4, 0x6f, 0xb1, 0x5d, 0x72, 0x5d, 0xe8, 0x3c, 0xc9, 0x6d, 0x96,
	0xdf, 0x84, 0xe9, 0x3c, 0xcd, 0xd2, 0xd8, 0x64, 0xc6, 0xb5, 0x0c, 0x08, 0x61, 0xf9, 0xb9, 0x06,
	0xb3, 0xbc, 0x4f, 0x0b, 0x5b, 0xb6, 0x4d, 0x50, 0x17, 0x7b, 0xdf, 0xae, 0x76, 0x72, 0x66, 0x58,
	0xf4, 0x1c, 0x18, 0xdb, 0xc0, 0x28, 0x6b, 0xbd, 0xcf, 0xe4, 0x2e, 0xa4, 0x0c, 0x9b, 0x55, 0x6d,
	0x6c, 0xd3, 0x49, 0xce, 0xb2, 0xd0, 0xae, 0xc1, 0x64, 0x01, 0x32, 0xda, 0x93, 0x5b, 0xbc, 0xe5,
	0x64, 0x4d, 0x69, 0x3f, 0xfe, 0xb7, 0x06, 0xaf, 0x30, 0xab, 0xcc, 0xf6, 0x30, 0xc7, 0x8b, 0x5d,
	0x6d, 0x5e, 0xd8, 0x4b, 0xd7, 0x50, 0x77, 0xaf, 0x59, 0x7a, 0xee, 0xc0, 0xa5, 0x23, 0x80, 0x52,
	0x9a, 0x1c, 0xbe, 0xec, 0x2a, 0xf1, 0x44, 0xd9, 0xa2, 0xd5, 0x93, 0x9a, 0x1a, 0x4f, 0xb1, 0x9b,
	0x7a, 0xb3, 0xa3, 0x8a, 0x57, 0x8f, 0x32, 0x33, 0x3e, 0xa0, 0xa1, 0x27, 0xf4, 0x7c, 0xaa, 0xc1,
	0x05, 0xb5, 0x7c, 0xb2, 0xc8, 0xda, 0x27, 0x60, 0x77, 0x5e, 0x08, 0xec, 0x0d, 0xa8, 0xe5, 0x71,
	0xd1, 0x74, 0x77, 0xf8, 0xb9, 0x4b, 0xc6, 0x90, 0xa6, 0xf9, 0x5f, 0x1a, 0x5c, 0x2e, 0xaa, 0x95,
	0x2c, 0x27, 0x07, 0xd5, 0xe6, 0x64, 0x2e, 0x57, 0xc9, 0x19, 0x6a, 0x6e, 0xc3, 0x6c, 0x39, 0x4c,
	0x4a, 0x91, 0xcb, 0x0f, 0x75, 0x8a, 0xfd, 0x50, 0xa6, 0xfe, 0xa0, 0x81, 0x38, 0xa8, 0x65, 0x8b,
	0x38, 0x97, 0x84, 0xae, 0x4d, 0xea, 0xdf, 0x61, 0xbc, 0xfc, 0xb8, 0x62, 0xbc, 0x88, 0x53, 0x6c,
	0x1a, 0x27, 0x31, 0x5b, 0x56, 0x47, 0x9e, 0x2c, 0xee, 0xc6, 0x81, 0x2f, 0xbc, 0x0f, 0x43, 0x2a,
	0x83, 0x74, 0xcf, 0x4c, 0x90, 0x1d, 0xf8, 0x0e, 0x61, 0x97, 0x04, 0xc3, 0x86, 0xfc, 0xa9, 0x37,
	0x60, 0xd0, 0xb7, 0xfc, 0x40, 0x4a, 0x5f, 0x62, 0x52, 0xf5, 0xd1, 0xc2, 0xeb, 0x50, 0xdb, 0xd8,
	0xd9, 0x5f, 0xd9, 0x8b, 0x7c, 0x1f, 0x79, 0xe2, 0xc0, 0x77, 0xef, 0xb0, 0x87, 0xf4, 0x09, 0x38,
	0xdd, 0xb7, 0xbc, 0x48, 0xde, 0x3b, 0xf0, 0x1f, 0x0b, 0x5f, 0x06, 0x9d, 0xaa, 0x6f, 0xdd, 0xdd,
	0x7b, 0xb1, 0xee, 0x55, 0x98, 0x32, 0xf6, 0xd6, 0x02, 0x9f, 0x84, 0xd8, 0x72, 0xfd, 0xf0, 0xc5,
	0x06, 0xaf, 0xc1, 0xc8, 0xc6, 0xce, 0x7e, 0xf3, 0xc5, 0x8a, 0xdb, 0xfc, 0x7a, 0x87, 0xa5, 0x8a,
	0xe0, 0x5e, 0xe0, 0xb9, 0xf6, 0x21, 0x3b, 0xc5, 0x36, 0xf9, 0x8a, 0x36, 0xf7, 0x1c, 0x11, 0x4e,
	0xcd, 0x90, 0x31, 0x4e, 0x85, 0xbb, 0x42, 0x26, 0x6f, 0x10, 0x12, 0x7f, 0xcd, 0x12, 0x7f, 0xcd,
	0xa3, 0xfc, 0x35, 0xb3, 0xfe, 0x6e, 0xc0, 0x28, 0xf5, 0xe7, 0x2d, 0xf7, 0x7b, 0xbe, 0xf4, 0x73,
	0x19, 0x86, 0x93, 0xdf, 0x89, 0xfd, 0x10, 0x7b, 0x28, 0x0d, 0xaf, 0xc0, 0xc4, 0xe6, 0xf2, 0xfe,
	0xce, 0xf6, 0xfa, 0xfe, 0xce, 0xf6, 0x8b, 0x69, 0x78, 0x1b, 0x6a, 0xc9, 0x30, 0x5d, 0xd2, 0x7b,
	0xfa, 0x7f, 0x8d, 0xf5, 0x15, 0x18, 0xa7, 0x6c, 0x6f, 0x1d, 0x6b, 0x28, 0xae, 0xbc, 0x72, 0x3c,
	0xe5, 0x45, 0x18, 0xdd, 0xdc, 0x35, 0x37, 0x77, 0x8f, 0x55, 0x22, 0x1b, 0x3b, 0xfd, 0x95, 0x7b,
	0x5e, 0xf0, 0x94, 0x56, 0xf2, 0x71, 0x0d, 0x9a, 0xc7, 0x37, 0xf8, 0xf3, 0x02, 0x9f, 0x2c, 0xf2,
	0x8e, 0x43, 0x1f, 0x85, 0x97, 0xad, 0xb6, 0x2b, 0x94, 0xe8, 0x9f, 0xfa, 0x3c, 0x0c, 0xb1, 0x8a,
	0x91, 0x64, 0xf1, 0x8b, 0xb4, 0x41, 0xfa, 0x4c, 0xde, 0x80, 0xd0, 0xad, 0x18, 0x55, 0xe9, 0xda,
	0xb4, 0x11, 0x49, 0x45, 0x7e, 0xaf, 0x36, 0x4a, 0x25, 0x5b, 0x54, 0x90, 0xd5, 0xf6, 0xac, 0x16,
	0xf2, 0x62, 0xed, 0x53, 0x89, 0xf6, 0x26, 0x15, 0x48, 0xed, 0x3f, 0x69, 0xc0, 0x8a, 0xd2, 0x0c,
	0xd9, 0x1c, 0x8c, 0xf5, 0x4f, 0xb3, 0xf6, 0xf4, 0x93, 0x0a, 0xb5, 0xa7, 0xc2, 0x46, 0x61, 0x8c,
	0xd1, 0x90, 0x52, 0x8f, 0xf5, 0xdf, 0x68, 0x30, 0xca, 0xf9, 0x72, 0x12, 0xb6, 0xce, 0x30, 0x3c,
	0x3f, 0xac, 0x18, 0x9e, 0x74, 0x27, 0x33, 0xce, 0xb3, 0x64, 0x3a, 0x71, 0x2a, 0x17, 0x05, 0x10,
	0x75, 0x32, 0x0d, 0xb0, 0x44, 0x32, 0xcd, 0xfd, 0x78, 0x3a, 0xc5, 0x7d, 0xa7, 0xdf, 0xf3, 0x2d,
	0x5e, 0x27, 0xa9, 0x5b, 0xcb, 0x71, 0xa1, 0x6e, 0x6d, 0x25, 0x22, 0xfd, 0x17, 0x1a, 0x2b, 0xbd,
	0x66, 0xec, 0xfa, 0x1c, 0xe3, 0xe8, 0xfb, 0xd5, 0xe2, 0x48, 0x6d, 0xc8, 0x6c, 0x5a, 0xc8, 0x07,
	0xfa, 0x6f, 0x35, 0x56, 0xe9, 0xcd, 0xcc, 0xbc, 0x80, 0xca, 0xa3, 0xa0, 0x49, 0x6d, 0xa6, 0xe6,
	0x6c, 0x0c, 0x25, 0x3d, 0x69, 0x07, 0x4f, 0x06, 0x94, 0x54, 0x43, 0xf9, 0x35, 0x9f, 0x7d, 0xcd,
	0x54, 0xd1, 0x0e, 0x55, 0x1e, 0x08, 0x9d, 0x50, 0x4d, 0x65, 0x42, 0x7d, 0xa2, 0xc1, 0x64, 0x0c,
	0x23, 0x5d, 0x60, 0xc3, 0x95, 0x07, 0x33, 0x2e, 0xc0, 0xa4, 0x6a, 0xec, 0x77, 0x1a, 0xe8, 0xde,
	0x32, 0xc5, 0xd3, 0xef, 0x79, 0x24, 0x46, 0x73, 0x9e, 0xa1, 0xf9, 0x41, 0xc5, 0xd6, 0xa1, 0xea,
	0xe2, 0xc5, 0x18, 0xf5, 0x96, 0xf7, 0x79, 0xd4, 0x12, 0xcb, 0xa7, 0x1a, 0xd4, 0x70, 0x68, 0xda,
	0xf1, 0xf2, 0x2e, 0x86, 0x33, 0xc2, 0xe0, 0xfc, 0xb4, 0x42, 0x70, 0x4a, 0x56, 0xa1, 0xc6, 0x38,
	0x0e, 0x73, 0x02, 0xfd, 0xf7, 0x1a, 0x8c, 0xf1, 0x9e, 0xa6, 0x4e, 0x9f, 0x51, 0x06, 0xea, 0x47,
	0x15, 0xab, 0xb8, 0xcc, 0x72, 0xcc, 0x18, 0x61, 0x6d, 0x2d, 0x59, 0xe3, 0x49, 0x30, 0x2b, 0x69,
	0x30, 0x63, 0x55, 0x04, 0xb3, 0x52, 0x04, 0x66, 0x45, 0x05, 0xf3, 0x47, 0x0d, 0xc6, 0xf9, 0xf4,
	0x31, 0x91, 0x0a, 0x47, 0xaf, 0xdc, 0x3e, 0xae, 0x68, 0x0d, 0x2f, 0xe6, 0xd0, 0xba, 0x02, 0xe8,
	0x97, 0x1a, 0x0c, 0x7b, 0xc4, 0x54, 0x5a, 0xc1, 0x78, 0xe5, 0x5a, 0x41, 0x76, 0x21, 0x6f, 0x0c,
	0x7a, 0x64, 0x93, 0x28, 0x3d, 0x5a, 0xa6, 0x24, 0xde, 0x7f, 0x50, 0x1c, 0x13, 0x95, 0x5b, 0xbb,
	0x16, 0x6e, 0x94, 0x44, 0x4e, 0xb6, 0x48, 0xef, 0xa9, 0xda, 0xd7, 0x58, 0x9c, 0x6d, 0xb1, 0xc5,
	0x88, 0x31, 0xd5, 0x2a, 0xd7, 0xd7, 0x4a, 0xb6, 0x4e, 0x7c, 0xad, 0x99, 0x11, 0x48, 0x60, 0xcd,
	0x3c, 0xb0, 0xc9, 0x2a, 0x02, 0x6b, 0x96, 0x01, 0xcb, 0x0a, 0xf4, 0x2f, 0x34, 0x98, 0x8e, 0xd7,
	0xe8, 0x39, 0x70, 0x53, 0x27, 0x26, 0x6b, 0x93, 0x62, 0x87, 0x50, 0x82, 0xaf, 0x59, 0x8c, 0xaf,
	0x7e, 0x62, 0x92, 0x37, 0x29, 0x96, 0x44, 0x59, 0x7c, 0x9f, 0xf1, 0x75, 0xde, 0x8a, 0x49, 0xb0,
	0x99, 0x39, 0x62, 0x99, 0x66, 0xe0, 0x7e, 0x56, 0xb1, 0x36, 0x52, 0x74, 0xec, 0x24, 0xcf, 0x95,
	0x76, 0xd4, 0x73, 0x20, 0x09, 0xad, 0x59, 0x00, 0x6d, 0xa6, 0xaa, 0xd0, 0x9a, 0x85, 0xd0, 0x9a,
	0x19, 0x68, 0x0b, 0x3f, 0x1f, 0x83, 0x89, 0xa2, 0xe3, 0x4a, 0xfd, 0x0e, 0x5c, 0x2a, 0xfd, 0x0a,
	0xd0, 0x3c, 0x70, 0x3b, 0x07, 0xe2, 0x8c, 0x72, 0xa6, 0xf8, 0x03, 0xc4, 0x07, 0x6e, 0xe7, 0x40,
	0xdf, 0x86, 0x57, 0xca, 0x7d, 0xd8, 0x51, 0x37, 0xf2, 0x2c, 0x8a, 0x5c, 0x9c, 0x67, 0x36, 0x8a,
	0x3d, 0xad, 0xc5, 0x7a, 0xfa, 0x26, 0x5c, 0x2e, 0xf7, 0xe7, 0xb8, 0xc4, 0xb6, 0xb0, 0x83, 0x1c,
	0x76, 0x9e, 0x33, 0x6c, 0xcc, 0x15, 0xbb, 0xbb, 0x2b, 0xd5, 0xf4, 0x07, 0x30, 0x7f, 0x44, 0x74,
	0x1e, 0xb2, 0x30, 0x72, 0xc4, 0xf7, 0xd4, 0xb3, 0x25, 0xa1, 0x71, 0x25, 0xfd, 0x26, 0xcc, 0x14,
	0x7e, 0xe7, 0xc8, 0x79, 0x3a, 0x5d, 0xf4, 0xa1, 0xe6, 0xae, 0xfb, 0x1c, 0x31, 0x8e, 0xee, 0x41,
	0xa3, 0xd8, 0x56, 0xe1, 0xe7, 0x4c, 0x43, 0x5b, 0x3c, 0x65, 0x5c, 0xcc, 0x7b, 0x50, 0xb8, 0xb9,
	0x0b, 0x73, 0xc5, 0x7e, 0x12, 0x5e, 0x06, 0x98, 0x9b, 0x0b, 0x79, 0x37, 0x09, 0x27, 0xb7, 0xe3,
	0x8f, 0x85, 0xb2, 0xd1, 0x08, 0x3e, 0xce, 0x32, 0x1f, 0xd3, 0x05, 0xa1, 0x08, 0x2e, 0x3e, 0xd7,
	0xc4, 0x31, 0xbf, 0xf0, 0x23, 0x86, 0x57, 0xee, 0x31, 0xce, 0x55, 0xfc, 0x3e, 0x37, 0xb9, 0xa2,
	0x11, 0xbc, 0x24, 0x57, 0x18, 0xd7, 0x61, 0xaa, 0x08, 0x9b, 0xd5, 0x41, 0xec, 0xb0, 0x64, 0xd8,
	0x98, 0xc8, 0x19, 0xaf, 0x76, 0x50, 0x8e, 0x13, 0x41, 0xa6, 0xc2, 0xc9, 0xe0, 0x89, 0xe1, 0x44,
	0xe4, 0xb9, 0xf4, 0x22, 0x98, 0x61, 0xe3, 0x94, 0x0c, 0x65, 0x2f, 0x82, 0x99, 0x2d, 0x63, 0x64,
	0x39, 0xfe, 0x3c, 0x39, 0x3c, 0xc0, 0x41, 0x18, 0x7a, 0x48, 0x7c, 0xaf, 0x32, 0xcc, 0x6d, 0xb8,
	0x70, 0x4f, 0xc8, 0xf8, 0xf7, 0x2a, 0x7f, 0xd5, 0xc4, 0x9d, 0x6a, 0xd6, 0x32, 0xa1, 0xf1, 0xfc,
	0x09, 0xf8, 0x2e, 0xf4, 0x49, 0x0a, 0x5a, 0xc2, 0xe3, 0x0d, 0xa8, 0x17, 0xa2, 0xa3, 0x4c, 0x8e,
	0x30, 0x56, 0x6a, 0x79, 0xf3, 0x34, 0x97, 0x18, 0xd9, 0x41, 0x1f, 0xe1, 0x43, 0xc1, 0xe5, 0xa8,
	0xca, 0xa5, 0x21, 0x64, 0xc5, 0x5c, 0xc6, 0x96, 0x09, 0x97, 0x63, 0x27, 0x86, 0x4b, 0x09, 0xad,
	0x94, 0xcb, 0x18, 0x1d, 0xe5, 0x52, 0xcf, 0x72, 0x29, 0xcd, 0x29, 0x97, 0xc9, 0x1b, 0xa6, 0x8b,
	0xba, 0x01, 0xb5, 0xf0, 0xbc, 0xc0, 0xe6, 0x71, 0xb4, 0x2d, 0xd7, 0x13, 0xcc, 0x8e, 0xab, 0x6f,
	0x98, 0x2d, 0xa6, 0xb9, 0x1a, 0x2b, 0xde, 0xb3, 0x5c, 0x8f, 0xb3, 0xfc, 0x5f, 0x0d, 0xae, 0xa8,
	0x71, 0x94, 0xf8, 0x4c, 0x38, 0x9f, 0xa8, 0x36, 0xe7, 0xaf, 0x25, 0xa4, 0x15, 0x81, 0x4e, 0xf8,
	0x7f, 0x0c, 0xaf, 0x1e, 0x03, 0x37, 0xcd, 0x46, 0x8d, 0x31, 0x39, 0x7f, 0xb4, 0xe3, 0xd5, 0x0e,
	0x6a, 0x9d, 0x61, 0xff, 0xeb, 0xeb, 0xda, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xce, 0xa0, 0x53,
	0x3d, 0x11, 0x36, 0x00, 0x00,
}
