// Code generated by protoc-gen-go.
// source: ospf_sh_topology_backup.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_ospf_oper_ospf_processes_process_default_vrf_route_information_multicast_intact_backup_routes_multicast_intact_backup_route is a generated protocol buffer package.

It is generated from these files:
	ospf_sh_topology_backup.proto

It has these top-level messages:
	OspfShTopologyBackup_KEYS
	OspfShTopologyBackup
	OspfShTime
	OspfShRepEl
	OspfShBackupPath
	OspfShSrUloopPath
	OspfShTopPathBackup
	OspfShTopCommon
*/
package cisco_ios_xr_ipv4_ospf_oper_ospf_processes_process_default_vrf_route_information_multicast_intact_backup_routes_multicast_intact_backup_route

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OSPF Route Information With Backup Path
type OspfShTopologyBackup_KEYS struct {
	ProcessName  string `protobuf:"bytes,1,opt,name=process_name,json=processName" json:"process_name,omitempty"`
	Prefix       string `protobuf:"bytes,2,opt,name=prefix" json:"prefix,omitempty"`
	PrefixLength uint32 `protobuf:"varint,3,opt,name=prefix_length,json=prefixLength" json:"prefix_length,omitempty"`
}

func (m *OspfShTopologyBackup_KEYS) Reset()                    { *m = OspfShTopologyBackup_KEYS{} }
func (m *OspfShTopologyBackup_KEYS) String() string            { return proto.CompactTextString(m) }
func (*OspfShTopologyBackup_KEYS) ProtoMessage()               {}
func (*OspfShTopologyBackup_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OspfShTopologyBackup_KEYS) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *OspfShTopologyBackup_KEYS) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *OspfShTopologyBackup_KEYS) GetPrefixLength() uint32 {
	if m != nil {
		return m.PrefixLength
	}
	return 0
}

type OspfShTopologyBackup struct {
	// Prefix
	RoutePrefix string `protobuf:"bytes,50,opt,name=route_prefix,json=routePrefix" json:"route_prefix,omitempty"`
	// Prefix length
	RoutePrefixLength uint32 `protobuf:"varint,51,opt,name=route_prefix_length,json=routePrefixLength" json:"route_prefix_length,omitempty"`
	// Metric
	RouteMetric uint32 `protobuf:"varint,52,opt,name=route_metric,json=routeMetric" json:"route_metric,omitempty"`
	// Route type
	RouteType string `protobuf:"bytes,53,opt,name=route_type,json=routeType" json:"route_type,omitempty"`
	// If true, connected route
	RouteConnected bool `protobuf:"varint,54,opt,name=route_connected,json=routeConnected" json:"route_connected,omitempty"`
	// Route information
	RouteInfo *OspfShTopCommon `protobuf:"bytes,55,opt,name=route_info,json=routeInfo" json:"route_info,omitempty"`
	// List of paths to this route
	RoutePathList []*OspfShTopPathBackup `protobuf:"bytes,56,rep,name=route_path_list,json=routePathList" json:"route_path_list,omitempty"`
}

func (m *OspfShTopologyBackup) Reset()                    { *m = OspfShTopologyBackup{} }
func (m *OspfShTopologyBackup) String() string            { return proto.CompactTextString(m) }
func (*OspfShTopologyBackup) ProtoMessage()               {}
func (*OspfShTopologyBackup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OspfShTopologyBackup) GetRoutePrefix() string {
	if m != nil {
		return m.RoutePrefix
	}
	return ""
}

func (m *OspfShTopologyBackup) GetRoutePrefixLength() uint32 {
	if m != nil {
		return m.RoutePrefixLength
	}
	return 0
}

func (m *OspfShTopologyBackup) GetRouteMetric() uint32 {
	if m != nil {
		return m.RouteMetric
	}
	return 0
}

func (m *OspfShTopologyBackup) GetRouteType() string {
	if m != nil {
		return m.RouteType
	}
	return ""
}

func (m *OspfShTopologyBackup) GetRouteConnected() bool {
	if m != nil {
		return m.RouteConnected
	}
	return false
}

func (m *OspfShTopologyBackup) GetRouteInfo() *OspfShTopCommon {
	if m != nil {
		return m.RouteInfo
	}
	return nil
}

func (m *OspfShTopologyBackup) GetRoutePathList() []*OspfShTopPathBackup {
	if m != nil {
		return m.RoutePathList
	}
	return nil
}

type OspfShTime struct {
	Second     uint32 `protobuf:"varint,1,opt,name=second" json:"second,omitempty"`
	Nanosecond uint32 `protobuf:"varint,2,opt,name=nanosecond" json:"nanosecond,omitempty"`
}

func (m *OspfShTime) Reset()                    { *m = OspfShTime{} }
func (m *OspfShTime) String() string            { return proto.CompactTextString(m) }
func (*OspfShTime) ProtoMessage()               {}
func (*OspfShTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OspfShTime) GetSecond() uint32 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *OspfShTime) GetNanosecond() uint32 {
	if m != nil {
		return m.Nanosecond
	}
	return 0
}

// OSPF Repair Element
type OspfShRepEl struct {
	// Repair Element ID
	RepairElementId string `protobuf:"bytes,1,opt,name=repair_element_id,json=repairElementId" json:"repair_element_id,omitempty"`
	// Repair Label
	RepairLabel uint32 `protobuf:"varint,2,opt,name=repair_label,json=repairLabel" json:"repair_label,omitempty"`
	// Repair Element Type
	RepairElementType uint32 `protobuf:"varint,3,opt,name=repair_element_type,json=repairElementType" json:"repair_element_type,omitempty"`
}

func (m *OspfShRepEl) Reset()                    { *m = OspfShRepEl{} }
func (m *OspfShRepEl) String() string            { return proto.CompactTextString(m) }
func (*OspfShRepEl) ProtoMessage()               {}
func (*OspfShRepEl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OspfShRepEl) GetRepairElementId() string {
	if m != nil {
		return m.RepairElementId
	}
	return ""
}

func (m *OspfShRepEl) GetRepairLabel() uint32 {
	if m != nil {
		return m.RepairLabel
	}
	return 0
}

func (m *OspfShRepEl) GetRepairElementType() uint32 {
	if m != nil {
		return m.RepairElementType
	}
	return 0
}

// OSPF Route Backup Path Information
type OspfShBackupPath struct {
	// Next hop Interface
	BackupRouteInterfaceName string `protobuf:"bytes,1,opt,name=backup_route_interface_name,json=backupRouteInterfaceName" json:"backup_route_interface_name,omitempty"`
	// Nexthop IP address
	BackupRouteNextHopAddress string `protobuf:"bytes,2,opt,name=backup_route_next_hop_address,json=backupRouteNextHopAddress" json:"backup_route_next_hop_address,omitempty"`
	// IP address of source of route
	BackupRouteSource string `protobuf:"bytes,3,opt,name=backup_route_source,json=backupRouteSource" json:"backup_route_source,omitempty"`
	// Metric
	BackupMetric uint32 `protobuf:"varint,4,opt,name=backup_metric,json=backupMetric" json:"backup_metric,omitempty"`
	// Primary Path
	PrimaryPath bool `protobuf:"varint,5,opt,name=primary_path,json=primaryPath" json:"primary_path,omitempty"`
	// Line Card Disjoint
	LineCardDisjoint bool `protobuf:"varint,6,opt,name=line_card_disjoint,json=lineCardDisjoint" json:"line_card_disjoint,omitempty"`
	// Downstream
	Downstream bool `protobuf:"varint,7,opt,name=downstream" json:"downstream,omitempty"`
	// Node Protect
	NodeProtect bool `protobuf:"varint,8,opt,name=node_protect,json=nodeProtect" json:"node_protect,omitempty"`
	// SRLG Disjoint
	SrlgDisjoint bool `protobuf:"varint,9,opt,name=srlg_disjoint,json=srlgDisjoint" json:"srlg_disjoint,omitempty"`
	// IP address of remote LFA
	BackupRemoteLfa string `protobuf:"bytes,10,opt,name=backup_remote_lfa,json=backupRemoteLfa" json:"backup_remote_lfa,omitempty"`
	// Backup Repair List
	BackupRepairList []*OspfShRepEl `protobuf:"bytes,11,rep,name=backup_repair_list,json=backupRepairList" json:"backup_repair_list,omitempty"`
	// Repair List Size
	BackupRepairListSize uint32 `protobuf:"varint,12,opt,name=backup_repair_list_size,json=backupRepairListSize" json:"backup_repair_list_size,omitempty"`
	// Backup Tunnel Interface
	BackupTunnelInterfaceName string `protobuf:"bytes,13,opt,name=backup_tunnel_interface_name,json=backupTunnelInterfaceName" json:"backup_tunnel_interface_name,omitempty"`
}

func (m *OspfShBackupPath) Reset()                    { *m = OspfShBackupPath{} }
func (m *OspfShBackupPath) String() string            { return proto.CompactTextString(m) }
func (*OspfShBackupPath) ProtoMessage()               {}
func (*OspfShBackupPath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OspfShBackupPath) GetBackupRouteInterfaceName() string {
	if m != nil {
		return m.BackupRouteInterfaceName
	}
	return ""
}

func (m *OspfShBackupPath) GetBackupRouteNextHopAddress() string {
	if m != nil {
		return m.BackupRouteNextHopAddress
	}
	return ""
}

func (m *OspfShBackupPath) GetBackupRouteSource() string {
	if m != nil {
		return m.BackupRouteSource
	}
	return ""
}

func (m *OspfShBackupPath) GetBackupMetric() uint32 {
	if m != nil {
		return m.BackupMetric
	}
	return 0
}

func (m *OspfShBackupPath) GetPrimaryPath() bool {
	if m != nil {
		return m.PrimaryPath
	}
	return false
}

func (m *OspfShBackupPath) GetLineCardDisjoint() bool {
	if m != nil {
		return m.LineCardDisjoint
	}
	return false
}

func (m *OspfShBackupPath) GetDownstream() bool {
	if m != nil {
		return m.Downstream
	}
	return false
}

func (m *OspfShBackupPath) GetNodeProtect() bool {
	if m != nil {
		return m.NodeProtect
	}
	return false
}

func (m *OspfShBackupPath) GetSrlgDisjoint() bool {
	if m != nil {
		return m.SrlgDisjoint
	}
	return false
}

func (m *OspfShBackupPath) GetBackupRemoteLfa() string {
	if m != nil {
		return m.BackupRemoteLfa
	}
	return ""
}

func (m *OspfShBackupPath) GetBackupRepairList() []*OspfShRepEl {
	if m != nil {
		return m.BackupRepairList
	}
	return nil
}

func (m *OspfShBackupPath) GetBackupRepairListSize() uint32 {
	if m != nil {
		return m.BackupRepairListSize
	}
	return 0
}

func (m *OspfShBackupPath) GetBackupTunnelInterfaceName() string {
	if m != nil {
		return m.BackupTunnelInterfaceName
	}
	return ""
}

// OSPF Route SR Uloop Path Information
type OspfShSrUloopPath struct {
	// Microloop Repair List
	MicroloopRepairList []*OspfShRepEl `protobuf:"bytes,1,rep,name=microloop_repair_list,json=microloopRepairList" json:"microloop_repair_list,omitempty"`
	// Microloop Repair List Size
	MicroloopRepairListSize uint32 `protobuf:"varint,2,opt,name=microloop_repair_list_size,json=microloopRepairListSize" json:"microloop_repair_list_size,omitempty"`
	// Microloop Tunnel Interface name
	MicroloopTunnelInterfaceName string `protobuf:"bytes,3,opt,name=microloop_tunnel_interface_name,json=microloopTunnelInterfaceName" json:"microloop_tunnel_interface_name,omitempty"`
	// Strict SPF SID
	MicroloopStrictSpf bool `protobuf:"varint,4,opt,name=microloop_strict_spf,json=microloopStrictSpf" json:"microloop_strict_spf,omitempty"`
}

func (m *OspfShSrUloopPath) Reset()                    { *m = OspfShSrUloopPath{} }
func (m *OspfShSrUloopPath) String() string            { return proto.CompactTextString(m) }
func (*OspfShSrUloopPath) ProtoMessage()               {}
func (*OspfShSrUloopPath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OspfShSrUloopPath) GetMicroloopRepairList() []*OspfShRepEl {
	if m != nil {
		return m.MicroloopRepairList
	}
	return nil
}

func (m *OspfShSrUloopPath) GetMicroloopRepairListSize() uint32 {
	if m != nil {
		return m.MicroloopRepairListSize
	}
	return 0
}

func (m *OspfShSrUloopPath) GetMicroloopTunnelInterfaceName() string {
	if m != nil {
		return m.MicroloopTunnelInterfaceName
	}
	return ""
}

func (m *OspfShSrUloopPath) GetMicroloopStrictSpf() bool {
	if m != nil {
		return m.MicroloopStrictSpf
	}
	return false
}

// OSPF Route Path Wit Backup Path Information
type OspfShTopPathBackup struct {
	// Next hop Interface
	RouteInterfaceName string `protobuf:"bytes,1,opt,name=route_interface_name,json=routeInterfaceName" json:"route_interface_name,omitempty"`
	// Nexthop IP address
	RouteNextHopAddress string `protobuf:"bytes,2,opt,name=route_next_hop_address,json=routeNextHopAddress" json:"route_next_hop_address,omitempty"`
	// IP address of source of route
	RouteSource string `protobuf:"bytes,3,opt,name=route_source,json=routeSource" json:"route_source,omitempty"`
	// LSA ID, see RFC2328
	RouteLsaid string `protobuf:"bytes,4,opt,name=route_lsaid,json=routeLsaid" json:"route_lsaid,omitempty"`
	// Multicast-intact path
	RoutePathIsMcastIntact bool `protobuf:"varint,5,opt,name=route_path_is_mcast_intact,json=routePathIsMcastIntact" json:"route_path_is_mcast_intact,omitempty"`
	// UCMP path
	RoutePathIsUcmpPath bool `protobuf:"varint,6,opt,name=route_path_is_ucmp_path,json=routePathIsUcmpPath" json:"route_path_is_ucmp_path,omitempty"`
	// Metric
	RouteMetric uint32 `protobuf:"varint,7,opt,name=route_metric,json=routeMetric" json:"route_metric,omitempty"`
	// Path ID of path
	RoutePathId uint32 `protobuf:"varint,8,opt,name=route_path_id,json=routePathId" json:"route_path_id,omitempty"`
	// LSA type, see RFC2328 etc.
	LsaType uint32 `protobuf:"varint,9,opt,name=lsa_type,json=lsaType" json:"lsa_type,omitempty"`
	// Backup Path Info
	RouteBackupPath *OspfShBackupPath `protobuf:"bytes,10,opt,name=route_backup_path,json=routeBackupPath" json:"route_backup_path,omitempty"`
	// SR Microloop avoidance Path Info
	SrMicroloopAvoidancePath *OspfShSrUloopPath `protobuf:"bytes,11,opt,name=sr_microloop_avoidance_path,json=srMicroloopAvoidancePath" json:"sr_microloop_avoidance_path,omitempty"`
}

func (m *OspfShTopPathBackup) Reset()                    { *m = OspfShTopPathBackup{} }
func (m *OspfShTopPathBackup) String() string            { return proto.CompactTextString(m) }
func (*OspfShTopPathBackup) ProtoMessage()               {}
func (*OspfShTopPathBackup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OspfShTopPathBackup) GetRouteInterfaceName() string {
	if m != nil {
		return m.RouteInterfaceName
	}
	return ""
}

func (m *OspfShTopPathBackup) GetRouteNextHopAddress() string {
	if m != nil {
		return m.RouteNextHopAddress
	}
	return ""
}

func (m *OspfShTopPathBackup) GetRouteSource() string {
	if m != nil {
		return m.RouteSource
	}
	return ""
}

func (m *OspfShTopPathBackup) GetRouteLsaid() string {
	if m != nil {
		return m.RouteLsaid
	}
	return ""
}

func (m *OspfShTopPathBackup) GetRoutePathIsMcastIntact() bool {
	if m != nil {
		return m.RoutePathIsMcastIntact
	}
	return false
}

func (m *OspfShTopPathBackup) GetRoutePathIsUcmpPath() bool {
	if m != nil {
		return m.RoutePathIsUcmpPath
	}
	return false
}

func (m *OspfShTopPathBackup) GetRouteMetric() uint32 {
	if m != nil {
		return m.RouteMetric
	}
	return 0
}

func (m *OspfShTopPathBackup) GetRoutePathId() uint32 {
	if m != nil {
		return m.RoutePathId
	}
	return 0
}

func (m *OspfShTopPathBackup) GetLsaType() uint32 {
	if m != nil {
		return m.LsaType
	}
	return 0
}

func (m *OspfShTopPathBackup) GetRouteBackupPath() *OspfShBackupPath {
	if m != nil {
		return m.RouteBackupPath
	}
	return nil
}

func (m *OspfShTopPathBackup) GetSrMicroloopAvoidancePath() *OspfShSrUloopPath {
	if m != nil {
		return m.SrMicroloopAvoidancePath
	}
	return nil
}

// OSPF Common Route Information
type OspfShTopCommon struct {
	// Area ID
	RouteAreaId uint32 `protobuf:"varint,1,opt,name=route_area_id,json=routeAreaId" json:"route_area_id,omitempty"`
	// TE metric
	RouteTeMetric uint32 `protobuf:"varint,2,opt,name=route_te_metric,json=routeTeMetric" json:"route_te_metric,omitempty"`
	// RIB version
	RouteRibVersion uint32 `protobuf:"varint,3,opt,name=route_rib_version,json=routeRibVersion" json:"route_rib_version,omitempty"`
	// SPF version
	RouteSpfVersion uint64 `protobuf:"varint,4,opt,name=route_spf_version,json=routeSpfVersion" json:"route_spf_version,omitempty"`
	// Forward distance
	RouteForwardDistance uint32 `protobuf:"varint,5,opt,name=route_forward_distance,json=routeForwardDistance" json:"route_forward_distance,omitempty"`
	// Protocol source
	RouteSource uint32 `protobuf:"varint,6,opt,name=route_source,json=routeSource" json:"route_source,omitempty"`
	// Last time updated
	RouteUpdateTime *OspfShTime `protobuf:"bytes,7,opt,name=route_update_time,json=routeUpdateTime" json:"route_update_time,omitempty"`
	// Last time update failed
	RouteFailTime *OspfShTime `protobuf:"bytes,8,opt,name=route_fail_time,json=routeFailTime" json:"route_fail_time,omitempty"`
	// SPF priority
	RouteSpfPriority uint32 `protobuf:"varint,9,opt,name=route_spf_priority,json=routeSpfPriority" json:"route_spf_priority,omitempty"`
	// If true, exclude from TE paths
	RouteAutoExcluded bool `protobuf:"varint,10,opt,name=route_auto_excluded,json=routeAutoExcluded" json:"route_auto_excluded,omitempty"`
	// If true, SRTE registered prefix route
	RouteSrtePrefixRegistered bool `protobuf:"varint,11,opt,name=route_srte_prefix_registered,json=routeSrtePrefixRegistered" json:"route_srte_prefix_registered,omitempty"`
	// SRTE registered neigbhor count on route
	RouteSrteNbrRegistered uint32 `protobuf:"varint,12,opt,name=route_srte_nbr_registered,json=routeSrteNbrRegistered" json:"route_srte_nbr_registered,omitempty"`
}

func (m *OspfShTopCommon) Reset()                    { *m = OspfShTopCommon{} }
func (m *OspfShTopCommon) String() string            { return proto.CompactTextString(m) }
func (*OspfShTopCommon) ProtoMessage()               {}
func (*OspfShTopCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OspfShTopCommon) GetRouteAreaId() uint32 {
	if m != nil {
		return m.RouteAreaId
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteTeMetric() uint32 {
	if m != nil {
		return m.RouteTeMetric
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteRibVersion() uint32 {
	if m != nil {
		return m.RouteRibVersion
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteSpfVersion() uint64 {
	if m != nil {
		return m.RouteSpfVersion
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteForwardDistance() uint32 {
	if m != nil {
		return m.RouteForwardDistance
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteSource() uint32 {
	if m != nil {
		return m.RouteSource
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteUpdateTime() *OspfShTime {
	if m != nil {
		return m.RouteUpdateTime
	}
	return nil
}

func (m *OspfShTopCommon) GetRouteFailTime() *OspfShTime {
	if m != nil {
		return m.RouteFailTime
	}
	return nil
}

func (m *OspfShTopCommon) GetRouteSpfPriority() uint32 {
	if m != nil {
		return m.RouteSpfPriority
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteAutoExcluded() bool {
	if m != nil {
		return m.RouteAutoExcluded
	}
	return false
}

func (m *OspfShTopCommon) GetRouteSrtePrefixRegistered() bool {
	if m != nil {
		return m.RouteSrtePrefixRegistered
	}
	return false
}

func (m *OspfShTopCommon) GetRouteSrteNbrRegistered() uint32 {
	if m != nil {
		return m.RouteSrteNbrRegistered
	}
	return 0
}

func init() {
	proto.RegisterType((*OspfShTopologyBackup_KEYS)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_topology_backup_KEYS")
	proto.RegisterType((*OspfShTopologyBackup)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_topology_backup")
	proto.RegisterType((*OspfShTime)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_time")
	proto.RegisterType((*OspfShRepEl)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_rep_el")
	proto.RegisterType((*OspfShBackupPath)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_backup_path")
	proto.RegisterType((*OspfShSrUloopPath)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_sr_uloop_path")
	proto.RegisterType((*OspfShTopPathBackup)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_top_path_backup")
	proto.RegisterType((*OspfShTopCommon)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.multicast_intact_backup_routes.multicast_intact_backup_route.ospf_sh_top_common")
}

func init() { proto.RegisterFile("ospf_sh_topology_backup.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0xd6, 0xc4, 0x61, 0xb3, 0xee, 0xf5, 0x26, 0x71, 0x3b, 0xb1, 0xc7, 0xf9, 0x21, 0x66, 0x91,
	0xc0, 0x8a, 0xa2, 0x15, 0x72, 0x1c, 0x7e, 0x85, 0xc0, 0x24, 0x8e, 0xb0, 0x70, 0xa2, 0x68, 0xec,
	0x20, 0x71, 0x6a, 0xf5, 0xce, 0xf4, 0xd8, 0x0d, 0x33, 0xd3, 0xa3, 0xee, 0x5e, 0xc7, 0xce, 0x81,
	0x37, 0x40, 0x1c, 0x39, 0x20, 0x0e, 0x44, 0x88, 0xf7, 0x40, 0xe2, 0xc0, 0x01, 0x29, 0x82, 0x67,
	0xe0, 0xca, 0x23, 0x20, 0xa1, 0xae, 0xea, 0xf9, 0x59, 0xdb, 0xc9, 0x79, 0x73, 0xdb, 0xfd, 0xea,
	0xaf, 0xab, 0xfa, 0xab, 0xea, 0x1a, 0x72, 0x5d, 0x99, 0x32, 0x65, 0x66, 0x9f, 0x59, 0x55, 0xaa,
	0x4c, 0xed, 0x1d, 0xb1, 0x11, 0x8f, 0xbf, 0x19, 0x97, 0xc3, 0x52, 0x2b, 0xab, 0xe8, 0x77, 0x41,
	0x2c, 0x4d, 0xac, 0x98, 0x54, 0x86, 0x1d, 0x6a, 0x26, 0xcb, 0x83, 0x75, 0x06, 0x16, 0xaa, 0x14,
	0x7a, 0xe8, 0x7e, 0x39, 0xc5, 0x58, 0x18, 0x23, 0x4c, 0xf5, 0x6b, 0x98, 0x88, 0x94, 0x8f, 0x33,
	0xcb, 0x0e, 0x74, 0x3a, 0xd4, 0x6a, 0x6c, 0x05, 0x93, 0x45, 0xaa, 0x74, 0xce, 0xad, 0x54, 0xc5,
	0x30, 0x1f, 0x67, 0x56, 0xc6, 0xdc, 0x58, 0x26, 0x0b, 0xcb, 0x63, 0xeb, 0x03, 0x32, 0xd0, 0x34,
	0x2f, 0x17, 0x0f, 0xbe, 0x25, 0xd7, 0x5e, 0x70, 0x60, 0xf6, 0xc5, 0xe6, 0x57, 0x3b, 0xf4, 0x0d,
	0x32, 0xe7, 0x4f, 0xc1, 0x0a, 0x9e, 0x8b, 0x30, 0x58, 0x09, 0x56, 0x67, 0xa3, 0x9e, 0xc7, 0x1e,
	0xf2, 0x5c, 0xd0, 0x45, 0xd2, 0x29, 0xb5, 0x48, 0xe5, 0x61, 0x78, 0x06, 0x84, 0xfe, 0x1f, 0x7d,
	0x93, 0xf4, 0xf1, 0x17, 0xcb, 0x44, 0xb1, 0x67, 0xf7, 0xc3, 0x99, 0x95, 0x60, 0xb5, 0x1f, 0xcd,
	0x21, 0xb8, 0x0d, 0xd8, 0xe0, 0xdf, 0xb3, 0x64, 0xe9, 0x05, 0x07, 0x70, 0xb1, 0x31, 0x5b, 0xef,
	0x7e, 0x0d, 0x63, 0x03, 0xf6, 0x08, 0x63, 0x0c, 0xc9, 0x42, 0x5b, 0xa5, 0x8a, 0x74, 0x1b, 0x22,
	0xcd, 0xb7, 0x34, 0x31, 0x5c, 0xe3, 0x32, 0x17, 0x56, 0xcb, 0x38, 0x5c, 0x07, 0x45, 0x74, 0xf9,
	0x00, 0x20, 0x7a, 0x9d, 0x10, 0x54, 0xb1, 0x47, 0xa5, 0x08, 0xef, 0x40, 0xcc, 0x59, 0x40, 0x76,
	0x8f, 0x4a, 0x41, 0xdf, 0x26, 0x17, 0x50, 0x1c, 0xab, 0xa2, 0x10, 0xb1, 0x15, 0x49, 0xf8, 0xee,
	0x4a, 0xb0, 0xda, 0x8d, 0xce, 0x03, 0x7c, 0xb7, 0x42, 0xe9, 0x6f, 0x41, 0xe5, 0xc8, 0x5d, 0x56,
	0xf8, 0xde, 0x4a, 0xb0, 0xda, 0x5b, 0xfb, 0x39, 0x18, 0x4e, 0xd5, 0xfd, 0x0f, 0x5b, 0xb5, 0x67,
	0xb1, 0xca, 0x73, 0x55, 0xf8, 0x64, 0xb7, 0x8a, 0x54, 0xd1, 0xe7, 0x41, 0x95, 0x6d, 0xc9, 0xed,
	0x3e, 0xcb, 0xa4, 0xb1, 0xe1, 0xfb, 0x2b, 0x33, 0xab, 0xbd, 0xb5, 0x5f, 0xa7, 0x39, 0x11, 0x38,
	0x2c, 0x4a, 0xa3, 0x3e, 0x92, 0x80, 0xdb, 0xfd, 0x6d, 0x69, 0xec, 0xe0, 0x3e, 0x99, 0xab, 0x35,
	0x25, 0x92, 0xd7, 0x88, 0x58, 0x15, 0x09, 0x30, 0xbb, 0x1f, 0xf9, 0x7f, 0xf4, 0x75, 0x42, 0x0a,
	0x5e, 0x28, 0x2f, 0x3b, 0x03, 0xb2, 0x16, 0x32, 0xf8, 0x3e, 0x20, 0xe7, 0x2b, 0x47, 0x5a, 0x94,
	0x4c, 0x64, 0xf4, 0x26, 0x99, 0xd7, 0xa2, 0xe4, 0x52, 0x33, 0x91, 0x89, 0x5c, 0x14, 0x96, 0xc9,
	0xc4, 0xf7, 0xcb, 0x05, 0x14, 0x6c, 0x22, 0xbe, 0x95, 0x00, 0x0f, 0x51, 0x37, 0xe3, 0x23, 0x91,
	0xf9, 0x00, 0x3d, 0xc4, 0xb6, 0x1d, 0x04, 0xd4, 0x9e, 0x74, 0x07, 0x84, 0x9c, 0xf1, 0xd4, 0x6e,
	0x3b, 0x74, 0xc4, 0x1c, 0xfc, 0xd0, 0x21, 0x0b, 0xd5, 0x89, 0x7c, 0x65, 0x5c, 0x1d, 0xe8, 0xc7,
	0xe4, 0x6a, 0xbb, 0x50, 0xae, 0x78, 0x42, 0xa7, 0x3c, 0x16, 0xed, 0x86, 0x0e, 0x7d, 0xb5, 0xf0,
	0xe6, 0xbd, 0x02, 0x74, 0xf7, 0xa7, 0xe4, 0xfa, 0x84, 0x79, 0x21, 0x0e, 0x2d, 0xdb, 0x57, 0x25,
	0xe3, 0x49, 0xa2, 0x85, 0x31, 0xbe, 0xe9, 0x97, 0x5b, 0x0e, 0x1e, 0x8a, 0x43, 0xfb, 0xb9, 0x2a,
	0x37, 0x50, 0xc1, 0x25, 0x32, 0xe1, 0xc1, 0xa8, 0xb1, 0x8e, 0x31, 0x91, 0xd9, 0x68, 0xbe, 0x65,
	0xb7, 0x03, 0x02, 0x37, 0x37, 0xbc, 0xbe, 0x6f, 0xd2, 0xb3, 0x38, 0x37, 0x10, 0xf4, 0x5d, 0x0a,
	0x73, 0x49, 0xe6, 0x5c, 0x1f, 0x41, 0x96, 0xe1, 0x6b, 0xd0, 0x83, 0x3d, 0x8f, 0xb9, 0xeb, 0xa6,
	0xb7, 0x08, 0xcd, 0x64, 0x21, 0x58, 0xcc, 0x75, 0xc2, 0x12, 0x69, 0xbe, 0x56, 0xb2, 0xb0, 0x61,
	0x07, 0x14, 0x2f, 0x3a, 0xc9, 0x5d, 0xae, 0x93, 0x7b, 0x1e, 0x77, 0x17, 0x9e, 0xa8, 0x27, 0x85,
	0xb1, 0x5a, 0xf0, 0x3c, 0x3c, 0x07, 0x5a, 0x2d, 0xc4, 0x05, 0x2c, 0x54, 0xe2, 0x06, 0x8d, 0xb2,
	0x22, 0xb6, 0x61, 0x17, 0x03, 0x3a, 0xec, 0x11, 0x42, 0xee, 0xe0, 0x46, 0x67, 0x7b, 0x4d, 0xac,
	0x59, 0xd0, 0x99, 0x73, 0x60, 0x1d, 0xe7, 0x26, 0x99, 0xaf, 0xaa, 0x21, 0x72, 0x65, 0x05, 0xcb,
	0x52, 0x1e, 0x12, 0x64, 0x89, 0xaf, 0x05, 0xe0, 0xdb, 0x29, 0xa7, 0x7f, 0x06, 0x84, 0xd6, 0xca,
	0xc8, 0x16, 0xd7, 0x81, 0x3d, 0xe8, 0xc0, 0x9f, 0xa6, 0xb5, 0x03, 0xb1, 0x1d, 0xa2, 0x8b, 0x55,
	0x36, 0x40, 0x69, 0x69, 0x2c, 0xbd, 0x43, 0x96, 0x4e, 0x66, 0xc3, 0x8c, 0x7c, 0x2a, 0xc2, 0x39,
	0xb8, 0xe2, 0x4b, 0xc7, 0x4d, 0x76, 0xe4, 0x53, 0x41, 0x3f, 0x21, 0xd7, 0xbc, 0x99, 0x1d, 0x17,
	0x85, 0xc8, 0x8e, 0x33, 0xb8, 0xdf, 0x26, 0xe0, 0x2e, 0xa8, 0x4c, 0x50, 0x78, 0xf0, 0x6c, 0x86,
	0x5c, 0xae, 0x0e, 0x67, 0x34, 0x1b, 0x67, 0xca, 0xcf, 0x08, 0xfa, 0x77, 0x40, 0x2e, 0xe7, 0x32,
	0xd6, 0x0a, 0xa0, 0x76, 0x8d, 0x83, 0x57, 0xa2, 0xc6, 0x0b, 0xf5, 0xe1, 0x5b, 0x65, 0xfe, 0x88,
	0x5c, 0x39, 0x35, 0x27, 0xac, 0x34, 0x4e, 0x9a, 0xa5, 0x53, 0x0c, 0xa1, 0xd8, 0x9b, 0xe4, 0x46,
	0x63, 0x7c, 0x7a, 0xbd, 0xb1, 0x71, 0xaf, 0xd5, 0x6a, 0xa7, 0x94, 0x9c, 0xbe, 0x43, 0x2e, 0x35,
	0x6e, 0x8c, 0xeb, 0x58, 0xcb, 0x4c, 0x99, 0x42, 0x2b, 0x77, 0x23, 0x5a, 0xcb, 0x76, 0x40, 0xb4,
	0x53, 0xa6, 0x83, 0xbf, 0x3a, 0x13, 0x8b, 0x40, 0x7b, 0x86, 0x3b, 0x6f, 0x2f, 0x99, 0x5d, 0x54,
	0x9f, 0x9c, 0x5a, 0xb7, 0xc9, 0xe2, 0x4b, 0xc7, 0x15, 0x6e, 0x0d, 0xc7, 0x06, 0x55, 0xbd, 0x1c,
	0x4c, 0x4c, 0x28, 0x5c, 0x0e, 0xfc, 0x6c, 0xba, 0x41, 0xf0, 0x2f, 0xcb, 0x0c, 0x97, 0x09, 0xa4,
	0x33, 0x1b, 0xe1, 0x33, 0xbf, 0xed, 0x10, 0xfa, 0x21, 0xb9, 0xd2, 0x7a, 0x30, 0xa5, 0x61, 0x79,
	0xeb, 0x2e, 0xfd, 0x94, 0x5a, 0xac, 0x9f, 0xa4, 0x2d, 0xf3, 0xc0, 0x89, 0xb7, 0x40, 0x4a, 0xd7,
	0xc9, 0xd2, 0xa4, 0xed, 0x38, 0xce, 0xb1, 0x10, 0x7e, 0x6a, 0x2d, 0xb4, 0x0c, 0x1f, 0xc7, 0x79,
	0x09, 0x63, 0xee, 0xf8, 0x4a, 0x73, 0xee, 0xe4, 0x4a, 0x33, 0x20, 0xfd, 0xb6, 0xe3, 0x04, 0x86,
	0x57, 0xa5, 0x03, 0xee, 0x12, 0xba, 0x4c, 0xba, 0x99, 0xe1, 0xf8, 0xc6, 0xcc, 0x82, 0xf8, 0x5c,
	0x66, 0x38, 0xac, 0x3c, 0xcf, 0x03, 0x82, 0xab, 0x54, 0xfb, 0x5d, 0x81, 0x99, 0xd5, 0x5b, 0x7b,
	0x36, 0xad, 0x1d, 0xd2, 0x3a, 0x6a, 0x84, 0x3b, 0xcc, 0x67, 0x80, 0x40, 0xcd, 0xfe, 0x09, 0xc8,
	0x55, 0xa3, 0x59, 0x43, 0x51, 0x7e, 0xa0, 0x64, 0xc2, 0x8b, 0x18, 0x4b, 0x14, 0xf6, 0x20, 0xb7,
	0x5f, 0xa6, 0x35, 0xb7, 0x89, 0x21, 0x16, 0x85, 0x46, 0x3f, 0xa8, 0x12, 0xd9, 0xa8, 0xf2, 0x70,
	0x69, 0x0e, 0xfe, 0xeb, 0x10, 0x7a, 0x72, 0xc1, 0x6b, 0xe8, 0xc0, 0xb5, 0xe0, 0xd5, 0x92, 0x52,
	0xd1, 0x61, 0x43, 0x0b, 0xbe, 0x95, 0xd0, 0xb7, 0xaa, 0xc5, 0xaf, 0x21, 0x16, 0x4e, 0x0e, 0x34,
	0xdd, 0xad, 0xa8, 0x75, 0xb3, 0xa2, 0x86, 0x96, 0x23, 0x76, 0x20, 0xb4, 0x91, 0xaa, 0xf0, 0x3b,
	0x0a, 0x3a, 0x88, 0xe4, 0xe8, 0x4b, 0x84, 0x1b, 0x5d, 0x77, 0xa4, 0x4a, 0xd7, 0xb5, 0xd0, 0x59,
	0xaf, 0xbb, 0x53, 0xa6, 0x95, 0xee, 0x7a, 0xd5, 0xc0, 0xa9, 0xd2, 0x4f, 0xfc, 0x03, 0x6e, 0x5d,
	0x62, 0xd0, 0x43, 0xfd, 0x08, 0x07, 0xc2, 0x7d, 0x14, 0xde, 0xf3, 0xb2, 0x13, 0x1d, 0xdc, 0x69,
	0x25, 0xe6, 0x3b, 0xf8, 0x8f, 0x9a, 0xcc, 0xe3, 0x32, 0xe1, 0x2e, 0x41, 0x99, 0x0b, 0x68, 0x9a,
	0xde, 0xda, 0x8f, 0x53, 0xbb, 0xd4, 0xca, 0x5c, 0xf8, 0x1a, 0x3d, 0x86, 0x53, 0xef, 0xba, 0xdd,
	0xf5, 0xf7, 0x7a, 0x3b, 0x4f, 0xb9, 0xcc, 0x30, 0x91, 0xee, 0x2b, 0x90, 0x08, 0x52, 0xe8, 0x3e,
	0x97, 0x19, 0xa4, 0x71, 0x8b, 0xd0, 0x86, 0x16, 0xa5, 0x96, 0x4a, 0x4b, 0x7b, 0xe4, 0x67, 0xd0,
	0xc5, 0x8a, 0x17, 0x8f, 0x3c, 0xde, 0x7c, 0xf1, 0xf1, 0xb1, 0x55, 0x4c, 0x1c, 0xc6, 0xd9, 0x38,
	0x11, 0x09, 0x4c, 0xa3, 0xae, 0xff, 0xe2, 0xdb, 0x18, 0x5b, 0xb5, 0xe9, 0x05, 0x6e, 0x7b, 0xf0,
	0xde, 0x75, 0xf3, 0x99, 0xa8, 0xc5, 0x9e, 0x34, 0x56, 0x68, 0x91, 0x40, 0xab, 0x77, 0xa3, 0x65,
	0x8c, 0xa3, 0xab, 0xcf, 0xc5, 0xa8, 0x56, 0xa0, 0x1f, 0x90, 0xe5, 0x96, 0x83, 0x62, 0xa4, 0xdb,
	0xd6, 0xb8, 0xb7, 0x2c, 0xd6, 0xd6, 0x0f, 0x47, 0xba, 0x31, 0x1d, 0x75, 0xe0, 0x9b, 0xff, 0xf6,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x1f, 0xfd, 0xb9, 0x14, 0x10, 0x00, 0x00,
}
