// Code generated by protoc-gen-go.
// source: bgp_rcv_pfxlst_bag.proto
// DO NOT EDIT!

/*
Package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_vrfs_vrf_afs_af_prefix_filters_prefix_filter is a generated protocol buffer package.

It is generated from these files:
	bgp_rcv_pfxlst_bag.proto

It has these top-level messages:
	BgpRcvPfxlstBag_KEYS
	BgpRcvPfxlstBag
	IPV4TunnelAddressType
	IPV4MDTAddressType
	RTConstraintAddressType
	IPV6AddressType
	BgpIpv4SrpolicyAddrT
	BgpIpv6SrpolicyAddrT
	BgpL2VpnAddrT
	L2VPNEVPNAddressType
	BgpL2VpnMspwAddrT
	IPV6MVPNAddressType
	IPV4MVPNAddressType
	LS_LSAddressType
	IPv4FlowspecAddressType
	IPv6FlowspecAddressType
	BgpAddrtype
	BgpPrefixtype
	BgpPfxlst_
	BgpPfxlst_Item
*/
package cisco_ios_xr_ipv4_bgp_oper_bgp_instances_instance_instance_active_vrfs_vrf_afs_af_prefix_filters_prefix_filter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Received prefix filter
type BgpRcvPfxlstBag_KEYS struct {
	InstanceName    string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName" json:"instance_name,omitempty"`
	VrfName         string `protobuf:"bytes,2,opt,name=vrf_name,json=vrfName" json:"vrf_name,omitempty"`
	AfName          string `protobuf:"bytes,3,opt,name=af_name,json=afName" json:"af_name,omitempty"`
	NeighborAddress string `protobuf:"bytes,4,opt,name=neighbor_address,json=neighborAddress" json:"neighbor_address,omitempty"`
}

func (m *BgpRcvPfxlstBag_KEYS) Reset()                    { *m = BgpRcvPfxlstBag_KEYS{} }
func (m *BgpRcvPfxlstBag_KEYS) String() string            { return proto.CompactTextString(m) }
func (*BgpRcvPfxlstBag_KEYS) ProtoMessage()               {}
func (*BgpRcvPfxlstBag_KEYS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BgpRcvPfxlstBag_KEYS) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *BgpRcvPfxlstBag_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *BgpRcvPfxlstBag_KEYS) GetAfName() string {
	if m != nil {
		return m.AfName
	}
	return ""
}

func (m *BgpRcvPfxlstBag_KEYS) GetNeighborAddress() string {
	if m != nil {
		return m.NeighborAddress
	}
	return ""
}

type BgpRcvPfxlstBag struct {
	// Address family identfier
	AfName string `protobuf:"bytes,50,opt,name=af_name,json=afName" json:"af_name,omitempty"`
	// Neighbor Address
	NeighborAddress *BgpAddrtype `protobuf:"bytes,51,opt,name=neighbor_address,json=neighborAddress" json:"neighbor_address,omitempty"`
	// Prefix list
	PrefixListInfo *BgpPfxlst_ `protobuf:"bytes,52,opt,name=prefix_list_info,json=prefixListInfo" json:"prefix_list_info,omitempty"`
}

func (m *BgpRcvPfxlstBag) Reset()                    { *m = BgpRcvPfxlstBag{} }
func (m *BgpRcvPfxlstBag) String() string            { return proto.CompactTextString(m) }
func (*BgpRcvPfxlstBag) ProtoMessage()               {}
func (*BgpRcvPfxlstBag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BgpRcvPfxlstBag) GetAfName() string {
	if m != nil {
		return m.AfName
	}
	return ""
}

func (m *BgpRcvPfxlstBag) GetNeighborAddress() *BgpAddrtype {
	if m != nil {
		return m.NeighborAddress
	}
	return nil
}

func (m *BgpRcvPfxlstBag) GetPrefixListInfo() *BgpPfxlst_ {
	if m != nil {
		return m.PrefixListInfo
	}
	return nil
}

// IPV4Tunnel Address type
type IPV4TunnelAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4TunnelAddressType) Reset()                    { *m = IPV4TunnelAddressType{} }
func (m *IPV4TunnelAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4TunnelAddressType) ProtoMessage()               {}
func (*IPV4TunnelAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IPV4TunnelAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4MDT Address type
type IPV4MDTAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4MDTAddressType) Reset()                    { *m = IPV4MDTAddressType{} }
func (m *IPV4MDTAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4MDTAddressType) ProtoMessage()               {}
func (*IPV4MDTAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IPV4MDTAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4 RTConstraint Address type
type RTConstraintAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *RTConstraintAddressType) Reset()                    { *m = RTConstraintAddressType{} }
func (m *RTConstraintAddressType) String() string            { return proto.CompactTextString(m) }
func (*RTConstraintAddressType) ProtoMessage()               {}
func (*RTConstraintAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RTConstraintAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV6 Address type
type IPV6AddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV6AddressType) Reset()                    { *m = IPV6AddressType{} }
func (m *IPV6AddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV6AddressType) ProtoMessage()               {}
func (*IPV6AddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IPV6AddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpIpv4SrpolicyAddrT struct {
	Ipv4SrpolicyAddress []byte `protobuf:"bytes,1,opt,name=ipv4_srpolicy_address,json=ipv4SrpolicyAddress,proto3" json:"ipv4_srpolicy_address,omitempty"`
}

func (m *BgpIpv4SrpolicyAddrT) Reset()                    { *m = BgpIpv4SrpolicyAddrT{} }
func (m *BgpIpv4SrpolicyAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpIpv4SrpolicyAddrT) ProtoMessage()               {}
func (*BgpIpv4SrpolicyAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BgpIpv4SrpolicyAddrT) GetIpv4SrpolicyAddress() []byte {
	if m != nil {
		return m.Ipv4SrpolicyAddress
	}
	return nil
}

type BgpIpv6SrpolicyAddrT struct {
	Ipv6SrpolicyAddress []byte `protobuf:"bytes,1,opt,name=ipv6_srpolicy_address,json=ipv6SrpolicyAddress,proto3" json:"ipv6_srpolicy_address,omitempty"`
}

func (m *BgpIpv6SrpolicyAddrT) Reset()                    { *m = BgpIpv6SrpolicyAddrT{} }
func (m *BgpIpv6SrpolicyAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpIpv6SrpolicyAddrT) ProtoMessage()               {}
func (*BgpIpv6SrpolicyAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BgpIpv6SrpolicyAddrT) GetIpv6SrpolicyAddress() []byte {
	if m != nil {
		return m.Ipv6SrpolicyAddress
	}
	return nil
}

type BgpL2VpnAddrT struct {
	L2VpnAddress []byte `protobuf:"bytes,1,opt,name=l2vpn_address,json=l2vpnAddress,proto3" json:"l2vpn_address,omitempty"`
}

func (m *BgpL2VpnAddrT) Reset()                    { *m = BgpL2VpnAddrT{} }
func (m *BgpL2VpnAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpL2VpnAddrT) ProtoMessage()               {}
func (*BgpL2VpnAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BgpL2VpnAddrT) GetL2VpnAddress() []byte {
	if m != nil {
		return m.L2VpnAddress
	}
	return nil
}

// L2VPN EVPN Address type
type L2VPNEVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *L2VPNEVPNAddressType) Reset()                    { *m = L2VPNEVPNAddressType{} }
func (m *L2VPNEVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*L2VPNEVPNAddressType) ProtoMessage()               {}
func (*L2VPNEVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *L2VPNEVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpL2VpnMspwAddrT struct {
	L2VpnAddress []byte `protobuf:"bytes,1,opt,name=l2vpn_address,json=l2vpnAddress,proto3" json:"l2vpn_address,omitempty"`
}

func (m *BgpL2VpnMspwAddrT) Reset()                    { *m = BgpL2VpnMspwAddrT{} }
func (m *BgpL2VpnMspwAddrT) String() string            { return proto.CompactTextString(m) }
func (*BgpL2VpnMspwAddrT) ProtoMessage()               {}
func (*BgpL2VpnMspwAddrT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BgpL2VpnMspwAddrT) GetL2VpnAddress() []byte {
	if m != nil {
		return m.L2VpnAddress
	}
	return nil
}

// IPV6 MVPN Address type
type IPV6MVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV6MVPNAddressType) Reset()                    { *m = IPV6MVPNAddressType{} }
func (m *IPV6MVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV6MVPNAddressType) ProtoMessage()               {}
func (*IPV6MVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IPV6MVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPV4 MVPN Address type
type IPV4MVPNAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPV4MVPNAddressType) Reset()                    { *m = IPV4MVPNAddressType{} }
func (m *IPV4MVPNAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPV4MVPNAddressType) ProtoMessage()               {}
func (*IPV4MVPNAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IPV4MVPNAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// LINKSTATE LINKSTATE Address type
type LS_LSAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *LS_LSAddressType) Reset()                    { *m = LS_LSAddressType{} }
func (m *LS_LSAddressType) String() string            { return proto.CompactTextString(m) }
func (*LS_LSAddressType) ProtoMessage()               {}
func (*LS_LSAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LS_LSAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPv4 Flowspec Address type
type IPv4FlowspecAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPv4FlowspecAddressType) Reset()                    { *m = IPv4FlowspecAddressType{} }
func (m *IPv4FlowspecAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPv4FlowspecAddressType) ProtoMessage()               {}
func (*IPv4FlowspecAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IPv4FlowspecAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IPv6 Flowspec Address type
type IPv6FlowspecAddressType struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *IPv6FlowspecAddressType) Reset()                    { *m = IPv6FlowspecAddressType{} }
func (m *IPv6FlowspecAddressType) String() string            { return proto.CompactTextString(m) }
func (*IPv6FlowspecAddressType) ProtoMessage()               {}
func (*IPv6FlowspecAddressType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IPv6FlowspecAddressType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BgpAddrtype struct {
	Afi string `protobuf:"bytes,1,opt,name=afi" json:"afi,omitempty"`
	// IPv4 Addr
	Ipv4Address string `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address" json:"ipv4_address,omitempty"`
	// IPv4 Mcast Addr
	Ipv4McastAddress string `protobuf:"bytes,3,opt,name=ipv4_mcast_address,json=ipv4McastAddress" json:"ipv4_mcast_address,omitempty"`
	// IPv4 Label Addr
	Ipv4LabelAddress string `protobuf:"bytes,4,opt,name=ipv4_label_address,json=ipv4LabelAddress" json:"ipv4_label_address,omitempty"`
	// IPv4 Tunnel
	Ipv4TunnelAddress *IPV4TunnelAddressType `protobuf:"bytes,5,opt,name=ipv4_tunnel_address,json=ipv4TunnelAddress" json:"ipv4_tunnel_address,omitempty"`
	// IPv4 MDT Addr
	Ipv4MdtAddress *IPV4MDTAddressType `protobuf:"bytes,6,opt,name=ipv4_mdt_address,json=ipv4MdtAddress" json:"ipv4_mdt_address,omitempty"`
	// IPv4 VPN Addr
	Ipv4VpnAddress string `protobuf:"bytes,7,opt,name=ipv4_vpn_address,json=ipv4VpnAddress" json:"ipv4_vpn_address,omitempty"`
	// IPv4 VPN Mcast Addr
	Ipv4VpnaMcastddress string `protobuf:"bytes,8,opt,name=ipv4_vpna_mcastddress,json=ipv4VpnaMcastddress" json:"ipv4_vpna_mcastddress,omitempty"`
	// IPV6 Addr
	Ipv6Address *IPV6AddressType `protobuf:"bytes,9,opt,name=ipv6_address,json=ipv6Address" json:"ipv6_address,omitempty"`
	// IPV6 Mcast Addr
	Ipv6McastAddress *IPV6AddressType `protobuf:"bytes,10,opt,name=ipv6_mcast_address,json=ipv6McastAddress" json:"ipv6_mcast_address,omitempty"`
	// IPv6 Label Addr
	Ipv6LabelAddress *IPV6AddressType `protobuf:"bytes,11,opt,name=ipv6_label_address,json=ipv6LabelAddress" json:"ipv6_label_address,omitempty"`
	// IPv6 VPN Addr
	Ipv6VpnAddress *IPV6AddressType `protobuf:"bytes,12,opt,name=ipv6_vpn_address,json=ipv6VpnAddress" json:"ipv6_vpn_address,omitempty"`
	// IPv6 VPN Mcast Addr
	Ipv6VpnMcastAddress *IPV6AddressType `protobuf:"bytes,13,opt,name=ipv6_vpn_mcast_address,json=ipv6VpnMcastAddress" json:"ipv6_vpn_mcast_address,omitempty"`
	// L2VPN VPLS Addr
	L2VpnvplsAddress *BgpL2VpnAddrT `protobuf:"bytes,14,opt,name=l2_vpnvpls_address,json=l2VpnvplsAddress" json:"l2_vpnvpls_address,omitempty"`
	// RT Constrt Addr
	RtConstraintAddress *RTConstraintAddressType `protobuf:"bytes,15,opt,name=rt_constraint_address,json=rtConstraintAddress" json:"rt_constraint_address,omitempty"`
	// MVPN addr
	Ipv6MvpnAddress *IPV6MVPNAddressType `protobuf:"bytes,16,opt,name=ipv6_mvpn_address,json=ipv6MvpnAddress" json:"ipv6_mvpn_address,omitempty"`
	// MVPN4 addr
	Ipv4MvpnAddress *IPV4MVPNAddressType `protobuf:"bytes,17,opt,name=ipv4_mvpn_address,json=ipv4MvpnAddress" json:"ipv4_mvpn_address,omitempty"`
	// L2VPN EVPN Addr
	L2VpnEvpnAddress *L2VPNEVPNAddressType `protobuf:"bytes,18,opt,name=l2_vpn_evpn_address,json=l2VpnEvpnAddress" json:"l2_vpn_evpn_address,omitempty"`
	// LINKSTATE LINKSTATE Addr
	LsLsAddress *LS_LSAddressType `protobuf:"bytes,19,opt,name=ls_ls_address,json=lsLsAddress" json:"ls_ls_address,omitempty"`
	// L2VPN MSPW Addr
	L2VpnMspwAddress *BgpL2VpnMspwAddrT `protobuf:"bytes,20,opt,name=l2_vpn_mspw_address,json=l2VpnMspwAddress" json:"l2_vpn_mspw_address,omitempty"`
	// IPV4 Flowspec Addr
	Ipv4FlowspecAddress *IPv4FlowspecAddressType `protobuf:"bytes,21,opt,name=ipv4_flowspec_address,json=ipv4FlowspecAddress" json:"ipv4_flowspec_address,omitempty"`
	// IPV6 Flowspec Addr
	Ipv6FlowspecAddress *IPv6FlowspecAddressType `protobuf:"bytes,22,opt,name=ipv6_flowspec_address,json=ipv6FlowspecAddress" json:"ipv6_flowspec_address,omitempty"`
	// IPV4 VPN Flowspec Addr
	Ipv4VpnFlowspecAddress *IPv4FlowspecAddressType `protobuf:"bytes,23,opt,name=ipv4_vpn_flowspec_address,json=ipv4VpnFlowspecAddress" json:"ipv4_vpn_flowspec_address,omitempty"`
	// IPV6 VPN Flowspec Addr
	Ipv6VpnFlowspecAddress *IPv6FlowspecAddressType `protobuf:"bytes,24,opt,name=ipv6_vpn_flowspec_address,json=ipv6VpnFlowspecAddress" json:"ipv6_vpn_flowspec_address,omitempty"`
	// IPV4 Policy Addr
	Ipv4SrPolicyAddress *BgpIpv4SrpolicyAddrT `protobuf:"bytes,25,opt,name=ipv4_sr_policy_address,json=ipv4SrPolicyAddress" json:"ipv4_sr_policy_address,omitempty"`
	// IPV6 Policy Addr
	Ipv6SrPolicyAddress *BgpIpv6SrpolicyAddrT `protobuf:"bytes,26,opt,name=ipv6_sr_policy_address,json=ipv6SrPolicyAddress" json:"ipv6_sr_policy_address,omitempty"`
}

func (m *BgpAddrtype) Reset()                    { *m = BgpAddrtype{} }
func (m *BgpAddrtype) String() string            { return proto.CompactTextString(m) }
func (*BgpAddrtype) ProtoMessage()               {}
func (*BgpAddrtype) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *BgpAddrtype) GetAfi() string {
	if m != nil {
		return m.Afi
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4McastAddress() string {
	if m != nil {
		return m.Ipv4McastAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4LabelAddress() string {
	if m != nil {
		return m.Ipv4LabelAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4TunnelAddress() *IPV4TunnelAddressType {
	if m != nil {
		return m.Ipv4TunnelAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4MdtAddress() *IPV4MDTAddressType {
	if m != nil {
		return m.Ipv4MdtAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4VpnAddress() string {
	if m != nil {
		return m.Ipv4VpnAddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv4VpnaMcastddress() string {
	if m != nil {
		return m.Ipv4VpnaMcastddress
	}
	return ""
}

func (m *BgpAddrtype) GetIpv6Address() *IPV6AddressType {
	if m != nil {
		return m.Ipv6Address
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6McastAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6McastAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6LabelAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6LabelAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6VpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnMcastAddress() *IPV6AddressType {
	if m != nil {
		return m.Ipv6VpnMcastAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnvplsAddress() *BgpL2VpnAddrT {
	if m != nil {
		return m.L2VpnvplsAddress
	}
	return nil
}

func (m *BgpAddrtype) GetRtConstraintAddress() *RTConstraintAddressType {
	if m != nil {
		return m.RtConstraintAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6MvpnAddress() *IPV6MVPNAddressType {
	if m != nil {
		return m.Ipv6MvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4MvpnAddress() *IPV4MVPNAddressType {
	if m != nil {
		return m.Ipv4MvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnEvpnAddress() *L2VPNEVPNAddressType {
	if m != nil {
		return m.L2VpnEvpnAddress
	}
	return nil
}

func (m *BgpAddrtype) GetLsLsAddress() *LS_LSAddressType {
	if m != nil {
		return m.LsLsAddress
	}
	return nil
}

func (m *BgpAddrtype) GetL2VpnMspwAddress() *BgpL2VpnMspwAddrT {
	if m != nil {
		return m.L2VpnMspwAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4FlowspecAddress() *IPv4FlowspecAddressType {
	if m != nil {
		return m.Ipv4FlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6FlowspecAddress() *IPv6FlowspecAddressType {
	if m != nil {
		return m.Ipv6FlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4VpnFlowspecAddress() *IPv4FlowspecAddressType {
	if m != nil {
		return m.Ipv4VpnFlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6VpnFlowspecAddress() *IPv6FlowspecAddressType {
	if m != nil {
		return m.Ipv6VpnFlowspecAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv4SrPolicyAddress() *BgpIpv4SrpolicyAddrT {
	if m != nil {
		return m.Ipv4SrPolicyAddress
	}
	return nil
}

func (m *BgpAddrtype) GetIpv6SrPolicyAddress() *BgpIpv6SrpolicyAddrT {
	if m != nil {
		return m.Ipv6SrPolicyAddress
	}
	return nil
}

type BgpPrefixtype struct {
	// Prefix
	Prefix *BgpAddrtype `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	// Prefix length
	PrefixLength uint32 `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength" json:"prefix_length,omitempty"`
}

func (m *BgpPrefixtype) Reset()                    { *m = BgpPrefixtype{} }
func (m *BgpPrefixtype) String() string            { return proto.CompactTextString(m) }
func (*BgpPrefixtype) ProtoMessage()               {}
func (*BgpPrefixtype) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *BgpPrefixtype) GetPrefix() *BgpAddrtype {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *BgpPrefixtype) GetPrefixLength() uint32 {
	if m != nil {
		return m.PrefixLength
	}
	return 0
}

type BgpPfxlst_ struct {
	// Next entry in prefix list
	BgpPfxlst_ []*BgpPfxlst_Item `protobuf:"bytes,1,rep,name=bgp_pfxlst_,json=bgpPfxlst" json:"bgp_pfxlst_,omitempty"`
}

func (m *BgpPfxlst_) Reset()                    { *m = BgpPfxlst_{} }
func (m *BgpPfxlst_) String() string            { return proto.CompactTextString(m) }
func (*BgpPfxlst_) ProtoMessage()               {}
func (*BgpPfxlst_) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *BgpPfxlst_) GetBgpPfxlst_() []*BgpPfxlst_Item {
	if m != nil {
		return m.BgpPfxlst_
	}
	return nil
}

type BgpPfxlst_Item struct {
	// BGP prefix
	BgpPrefix *BgpPrefixtype `protobuf:"bytes,1,opt,name=bgp_prefix,json=bgpPrefix" json:"bgp_prefix,omitempty"`
	// Sequence number
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	// TRUE = permit, FALSE = deny
	IsPrefixGrant bool `protobuf:"varint,3,opt,name=is_prefix_grant,json=isPrefixGrant" json:"is_prefix_grant,omitempty"`
	// Minimum prefix length
	MinPrefixLength uint32 `protobuf:"varint,4,opt,name=min_prefix_length,json=minPrefixLength" json:"min_prefix_length,omitempty"`
	// Maximum prefix length
	MaxPrefixLength uint32 `protobuf:"varint,5,opt,name=max_prefix_length,json=maxPrefixLength" json:"max_prefix_length,omitempty"`
}

func (m *BgpPfxlst_Item) Reset()                    { *m = BgpPfxlst_Item{} }
func (m *BgpPfxlst_Item) String() string            { return proto.CompactTextString(m) }
func (*BgpPfxlst_Item) ProtoMessage()               {}
func (*BgpPfxlst_Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *BgpPfxlst_Item) GetBgpPrefix() *BgpPrefixtype {
	if m != nil {
		return m.BgpPrefix
	}
	return nil
}

func (m *BgpPfxlst_Item) GetSequenceNumber() uint32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *BgpPfxlst_Item) GetIsPrefixGrant() bool {
	if m != nil {
		return m.IsPrefixGrant
	}
	return false
}

func (m *BgpPfxlst_Item) GetMinPrefixLength() uint32 {
	if m != nil {
		return m.MinPrefixLength
	}
	return 0
}

func (m *BgpPfxlst_Item) GetMaxPrefixLength() uint32 {
	if m != nil {
		return m.MaxPrefixLength
	}
	return 0
}

func init() {
	proto.RegisterType((*BgpRcvPfxlstBag_KEYS)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_rcv_pfxlst_bag_KEYS")
	proto.RegisterType((*BgpRcvPfxlstBag)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_rcv_pfxlst_bag")
	proto.RegisterType((*IPV4TunnelAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.IPV4TunnelAddressType")
	proto.RegisterType((*IPV4MDTAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.IPV4MDTAddressType")
	proto.RegisterType((*RTConstraintAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.RTConstraintAddressType")
	proto.RegisterType((*IPV6AddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.IPV6AddressType")
	proto.RegisterType((*BgpIpv4SrpolicyAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_ipv4_srpolicy_addr_t")
	proto.RegisterType((*BgpIpv6SrpolicyAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_ipv6_srpolicy_addr_t")
	proto.RegisterType((*BgpL2VpnAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_l2vpn_addr_t")
	proto.RegisterType((*L2VPNEVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.L2VPNEVPNAddressType")
	proto.RegisterType((*BgpL2VpnMspwAddrT)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_l2vpn_mspw_addr_t")
	proto.RegisterType((*IPV6MVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.IPV6MVPNAddressType")
	proto.RegisterType((*IPV4MVPNAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.IPV4MVPNAddressType")
	proto.RegisterType((*LS_LSAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.LS_LSAddressType")
	proto.RegisterType((*IPv4FlowspecAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.IPv4FlowspecAddressType")
	proto.RegisterType((*IPv6FlowspecAddressType)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.IPv6FlowspecAddressType")
	proto.RegisterType((*BgpAddrtype)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_addrtype")
	proto.RegisterType((*BgpPrefixtype)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_prefixtype")
	proto.RegisterType((*BgpPfxlst_)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_pfxlst_")
	proto.RegisterType((*BgpPfxlst_Item)(nil), "cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_active.vrfs.vrf.afs.af.prefix_filters.prefix_filter.bgp_pfxlst__item")
}

func init() { proto.RegisterFile("bgp_rcv_pfxlst_bag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x6f, 0xe3, 0x54,
	0x14, 0xd6, 0x6d, 0xa7, 0xaf, 0xd3, 0xa4, 0x49, 0x6f, 0xfa, 0x48, 0x59, 0xa0, 0x92, 0x4a, 0x4c,
	0x19, 0x86, 0x20, 0x65, 0x22, 0xb3, 0x61, 0x83, 0xa0, 0xa0, 0x8a, 0xb4, 0x8a, 0xdc, 0x2a, 0x12,
	0xab, 0x2b, 0x27, 0xb5, 0x33, 0x96, 0x1c, 0xdb, 0xf8, 0xba, 0x6e, 0x2b, 0x10, 0x20, 0x1e, 0x82,
	0x1f, 0xc0, 0x76, 0x16, 0x20, 0x8d, 0x10, 0x0b, 0x04, 0x48, 0x03, 0x2b, 0xc4, 0x86, 0x0d, 0x0b,
	0xfe, 0x01, 0x3f, 0x06, 0x74, 0xcf, 0xbd, 0x76, 0x6c, 0x27, 0xa5, 0x65, 0x53, 0x67, 0x13, 0xd9,
	0xe7, 0x7c, 0x3e, 0xfe, 0xee, 0x79, 0xe5, 0xf8, 0x40, 0xbd, 0x3f, 0xf4, 0x59, 0x30, 0x88, 0x98,
	0x6f, 0x5d, 0x3a, 0x3c, 0x64, 0x7d, 0x63, 0xd8, 0xf4, 0x03, 0x2f, 0xf4, 0xa8, 0x3b, 0xb0, 0xf9,
	0xc0, 0x63, 0xb6, 0xc7, 0xd9, 0x65, 0xc0, 0x6c, 0x3f, 0x6a, 0x33, 0x81, 0xf5, 0x7c, 0x33, 0x68,
	0xf6, 0x87, 0x7e, 0xd3, 0x76, 0x79, 0x68, 0xb8, 0x03, 0x93, 0x27, 0x57, 0xc9, 0x05, 0x33, 0x06,
	0xa1, 0x1d, 0x99, 0xcd, 0x28, 0xb0, 0xb8, 0xf8, 0x69, 0x1a, 0x16, 0x6f, 0x1a, 0x56, 0xd3, 0x0f,
	0x4c, 0xcb, 0xbe, 0x64, 0x96, 0xed, 0x84, 0x66, 0xc0, 0xb3, 0xb7, 0x8d, 0x27, 0x04, 0xb6, 0x27,
	0xc9, 0xb0, 0x77, 0x0f, 0xde, 0x3b, 0xa1, 0x7b, 0x50, 0x4e, 0x6c, 0xbb, 0xc6, 0xc8, 0xac, 0x93,
	0x5d, 0xb2, 0xbf, 0xa2, 0x97, 0x62, 0xe1, 0xb1, 0x31, 0x32, 0xe9, 0x0e, 0x2c, 0x47, 0x81, 0x25,
	0xf5, 0x73, 0xa8, 0x5f, 0x8a, 0x02, 0x0b, 0x55, 0xdb, 0xb0, 0x64, 0x28, 0xcd, 0x3c, 0x6a, 0x16,
	0x0d, 0xa9, 0x78, 0x09, 0xaa, 0xae, 0x69, 0x0f, 0x1f, 0xf7, 0xbd, 0x80, 0x19, 0x67, 0x67, 0x81,
	0xc9, 0x79, 0xfd, 0x1e, 0x22, 0x2a, 0xb1, 0xfc, 0x0d, 0x29, 0x6e, 0xfc, 0x33, 0x07, 0x74, 0x92,
	0x5f, 0xda, 0x74, 0x2b, 0x63, 0xfa, 0x3b, 0x32, 0xc5, 0xf6, 0xa3, 0x5d, 0xb2, 0xbf, 0xda, 0xfa,
	0xb0, 0x79, 0xb7, 0xbe, 0x15, 0x36, 0x91, 0x42, 0x78, 0xe5, 0x9b, 0x13, 0x27, 0xa3, 0x4f, 0x09,
	0x54, 0x15, 0xde, 0xb1, 0x79, 0xc8, 0x6c, 0xd7, 0xf2, 0xea, 0x6d, 0x64, 0xfa, 0x41, 0x11, 0x4c,
	0x95, 0x77, 0xf5, 0x35, 0xa9, 0xea, 0xd8, 0x3c, 0x3c, 0x74, 0x2d, 0xaf, 0xf1, 0x0a, 0x6c, 0x1e,
	0x76, 0x7b, 0xed, 0xd3, 0x73, 0xd7, 0x35, 0x1d, 0x45, 0xfe, 0xf4, 0xca, 0x37, 0xe9, 0x06, 0x2c,
	0x44, 0x86, 0x73, 0x1e, 0xa7, 0x85, 0xbc, 0x69, 0x3c, 0x00, 0x2a, 0xe0, 0x47, 0x6f, 0x9d, 0xde,
	0x8c, 0x7d, 0x15, 0xb6, 0xf5, 0xd3, 0x37, 0x3d, 0x97, 0x87, 0x81, 0x61, 0xbb, 0xe1, 0xcd, 0x0f,
	0xdc, 0x87, 0xca, 0x61, 0xb7, 0xa7, 0xdd, 0x0c, 0x3c, 0x96, 0x25, 0x86, 0x9e, 0xe3, 0x81, 0xef,
	0x39, 0xf6, 0xe0, 0x0a, 0x63, 0xc1, 0x42, 0xda, 0x82, 0xcd, 0x49, 0xb9, 0x48, 0x13, 0x61, 0xa1,
	0xa4, 0xd7, 0x84, 0xf2, 0x44, 0xe9, 0xe2, 0x34, 0x1c, 0xdb, 0xd3, 0xae, 0xb1, 0xa7, 0xfd, 0x97,
	0x3d, 0x2d, 0x6f, 0xef, 0x35, 0xa8, 0x0a, 0x7b, 0x4e, 0x2b, 0xf2, 0xdd, 0xd8, 0xce, 0x1e, 0x94,
	0xc7, 0xf7, 0xe3, 0xe7, 0x4b, 0x28, 0x8c, 0x1f, 0x7c, 0x08, 0x1b, 0x9d, 0x56, 0xaf, 0x7b, 0x7c,
	0xd0, 0xeb, 0x1e, 0xdf, 0xec, 0x86, 0xd7, 0x61, 0x73, 0xfc, 0x9a, 0x11, 0xf7, 0x2f, 0xfe, 0xd7,
	0xbb, 0x5e, 0x86, 0x9a, 0xf0, 0xf6, 0xd1, 0xad, 0x5e, 0x25, 0xc1, 0xed, 0xdb, 0x81, 0xf7, 0xa1,
	0xda, 0x39, 0x61, 0x9d, 0x93, 0x5b, 0xa5, 0xc8, 0x61, 0x37, 0x6a, 0xbf, 0xed, 0x78, 0x17, 0xdc,
	0x37, 0x07, 0xb7, 0x7d, 0x40, 0xbb, 0xfd, 0x03, 0x7f, 0x3e, 0x0f, 0xa5, 0x74, 0xa5, 0xd2, 0x2a,
	0xcc, 0x1b, 0x96, 0xad, 0x40, 0xe2, 0x92, 0xbe, 0x00, 0x25, 0xcc, 0x98, 0xd8, 0x59, 0xb2, 0xcf,
	0xad, 0x0a, 0x59, 0x5c, 0xcd, 0x0f, 0x81, 0x22, 0x64, 0x34, 0x30, 0x78, 0x98, 0x00, 0x65, 0xdb,
	0xab, 0x0a, 0xcd, 0x91, 0x50, 0xe4, 0xd1, 0x8e, 0xd1, 0x37, 0x9d, 0x5c, 0x0b, 0x44, 0x74, 0x47,
	0x28, 0x62, 0xf4, 0xaf, 0x04, 0x30, 0x29, 0x59, 0x88, 0x35, 0x98, 0xe0, 0x17, 0xb0, 0x59, 0x7c,
	0x41, 0xee, 0xba, 0x5b, 0x4c, 0x6d, 0x07, 0xfa, 0xba, 0x78, 0x71, 0x46, 0x4c, 0x7f, 0x20, 0x50,
	0x95, 0x5e, 0x39, 0x1b, 0xfb, 0x64, 0x11, 0x59, 0x7f, 0x5a, 0x08, 0xeb, 0x6c, 0x57, 0xd2, 0xd7,
	0x30, 0x30, 0x67, 0x49, 0x58, 0xf6, 0x15, 0xdd, 0x74, 0x61, 0x2c, 0x61, 0x50, 0x10, 0xd9, 0x4b,
	0x4a, 0x23, 0xe9, 0x21, 0x91, 0xef, 0x1a, 0x32, 0xe6, 0x0a, 0xbe, 0x8c, 0xf0, 0x9a, 0x82, 0x1b,
	0x47, 0x63, 0x15, 0xfd, 0x96, 0x60, 0x1a, 0x69, 0x89, 0xe9, 0x15, 0xf4, 0xc4, 0xc7, 0x05, 0x38,
	0x22, 0xdd, 0x41, 0x31, 0x8f, 0xb5, 0x54, 0xc8, 0x28, 0x92, 0xcc, 0x26, 0x32, 0xcc, 0x06, 0x55,
	0x11, 0x1e, 0x2d, 0x53, 0x49, 0x09, 0xdf, 0x6c, 0x29, 0xad, 0xce, 0x10, 0xdf, 0x4c, 0x2d, 0x7f,
	0x2f, 0x4b, 0x42, 0xcb, 0xe4, 0x58, 0x69, 0x36, 0xd8, 0x8a, 0x24, 0xd7, 0x52, 0x49, 0xfe, 0x8c,
	0xc0, 0x56, 0xc2, 0x35, 0x9b, 0x0f, 0xe5, 0xd9, 0x60, 0x5c, 0x53, 0x8c, 0x33, 0x29, 0xf1, 0x23,
	0x01, 0xea, 0xb4, 0x04, 0xe9, 0xc8, 0x77, 0x78, 0x42, 0x79, 0x0d, 0x29, 0x7f, 0x42, 0x8a, 0x98,
	0xad, 0xd2, 0xff, 0xf3, 0x7a, 0xd5, 0x69, 0xf5, 0x24, 0xb7, 0x98, 0xf1, 0x6f, 0x04, 0x36, 0x83,
	0x90, 0x0d, 0x92, 0x49, 0x28, 0x21, 0x5d, 0x41, 0xd2, 0x5f, 0xde, 0x39, 0xe9, 0x6b, 0xc6, 0x32,
	0xbd, 0x16, 0x84, 0x13, 0x0a, 0xfa, 0x13, 0x81, 0x75, 0xd9, 0x33, 0xd2, 0x49, 0x5d, 0x45, 0xea,
	0x9f, 0x15, 0xd1, 0xe7, 0xf3, 0x23, 0x8b, 0x5e, 0xc1, 0xbe, 0x31, 0x1e, 0x6d, 0x62, 0xca, 0xed,
	0x2c, 0xe5, 0xf5, 0xe2, 0x28, 0xb7, 0xa7, 0x51, 0x6e, 0xa7, 0x29, 0x3f, 0x23, 0x50, 0x93, 0x69,
	0xcd, 0xcc, 0x34, 0x69, 0x8a, 0xa4, 0x3f, 0xbf, 0x73, 0xd2, 0xd3, 0xc6, 0x50, 0x95, 0xdb, 0x07,
	0x29, 0xda, 0x4f, 0x09, 0x94, 0x1d, 0xce, 0x52, 0x85, 0x58, 0x2b, 0xa8, 0x10, 0xf3, 0x13, 0xa7,
	0xbe, 0xea, 0xf0, 0x4e, 0x52, 0x83, 0xbf, 0x8c, 0xdd, 0x9b, 0x0c, 0xca, 0x82, 0xed, 0x46, 0x41,
	0x43, 0xd6, 0xd4, 0xb9, 0x5d, 0xf9, 0xf7, 0x88, 0xfb, 0x17, 0xe9, 0xde, 0x81, 0x6c, 0x2c, 0x35,
	0xf1, 0x26, 0xcc, 0x37, 0x0b, 0xea, 0x1d, 0xd7, 0xcc, 0xeb, 0x72, 0x28, 0xca, 0x29, 0x62, 0xfa,
	0xda, 0x24, 0xfd, 0xad, 0xe2, 0xe8, 0x6b, 0xd7, 0xd1, 0xcf, 0x2b, 0xe8, 0x1f, 0x04, 0x76, 0x92,
	0x91, 0x71, 0xe2, 0x08, 0xdb, 0x33, 0x16, 0x81, 0x2d, 0x35, 0x96, 0x5e, 0x73, 0x0a, 0x6d, 0xfa,
	0x29, 0xea, 0x33, 0x16, 0x88, 0x2d, 0xf5, 0xa7, 0x9f, 0x3f, 0xc5, 0xef, 0x72, 0x5c, 0x11, 0x1f,
	0xf6, 0x2c, 0xf7, 0x25, 0xbe, 0x83, 0x47, 0xf8, 0xaa, 0x90, 0x22, 0x9e, 0xb6, 0x83, 0x88, 0x97,
	0x0c, 0xdd, 0xf4, 0x52, 0x20, 0x3e, 0x80, 0x36, 0xe5, 0x00, 0xcf, 0x15, 0x7b, 0x00, 0x6d, 0xea,
	0x01, 0xb4, 0xdc, 0x01, 0x1a, 0x7f, 0x11, 0x58, 0xc3, 0x55, 0x12, 0xda, 0xc0, 0x8f, 0xe9, 0xaf,
	0x09, 0x2c, 0xca, 0x5b, 0xfc, 0xa0, 0x2e, 0x7a, 0x0b, 0xa7, 0xb8, 0xd0, 0x3d, 0x28, 0xc7, 0xbb,
	0x37, 0xd3, 0x1d, 0x86, 0x8f, 0xf1, 0x93, 0xbe, 0xac, 0x97, 0xd4, 0xee, 0x0b, 0x65, 0x8d, 0x9f,
	0x09, 0xac, 0xa6, 0x36, 0x63, 0xf4, 0x9b, 0xec, 0x7d, 0x9d, 0xec, 0xce, 0x17, 0x36, 0x51, 0x2a,
	0x0e, 0xcc, 0x0e, 0xcd, 0x91, 0xbe, 0xd2, 0x1f, 0xfa, 0x5d, 0x14, 0x34, 0xfe, 0x9e, 0x93, 0x9b,
	0xa5, 0xb4, 0x9e, 0x3e, 0x21, 0x00, 0xe3, 0xb8, 0xa8, 0x40, 0x7c, 0x54, 0x08, 0xed, 0x24, 0x33,
	0x24, 0x69, 0x19, 0x8d, 0xfb, 0x50, 0xe1, 0xe6, 0xfb, 0xe7, 0x26, 0x2e, 0x9a, 0xcf, 0x47, 0x7d,
	0x33, 0x50, 0xf1, 0x58, 0x8b, 0xc5, 0xc7, 0x28, 0xa5, 0x2f, 0x42, 0xc5, 0xe6, 0xca, 0x08, 0x1b,
	0x06, 0x86, 0x1b, 0xe2, 0x8a, 0x65, 0x59, 0x2f, 0xdb, 0x5c, 0xda, 0x7a, 0x47, 0x08, 0xe9, 0x03,
	0x58, 0x1f, 0xd9, 0x2e, 0xcb, 0x86, 0xf8, 0x1e, 0x9a, 0xac, 0x8c, 0x6c, 0xb7, 0x9b, 0x8a, 0x32,
	0x62, 0x8d, 0xcb, 0x1c, 0x76, 0x41, 0x61, 0x8d, 0xcb, 0x34, 0xb6, 0xbf, 0x88, 0x4b, 0xfa, 0x47,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xde, 0x43, 0xf9, 0x6b, 0xc0, 0x17, 0x00, 0x00,
}
